AvTranscoder: avtranscoder::ParamSet Class Reference
avtranscoder::ParamSet Class Reference
#include <common.hpp>
Public Member Functions
ParamSet (void *obj)
void set (const std::string &key, const std::string &flag, const bool enable)
void set (const std::string &key, const bool value)
void set (const std::string &key, const int value)
void set (const std::string &key, const int num, const int den)
void set (const std::string &key, const double value)
void set (const std::string &key, const std::string &value)
Private Attributes
void * _objContext
Detailed Description
Definition at line 67 of file common.hpp.
Constructor & Destructor Documentation
avtranscoder::ParamSet::ParamSet (void * obj) inline
Definition at line 70 of file common.hpp.
Member Function Documentation
void avtranscoder::ParamSet::set (const std::string & key, const std::string & flag, const bool enable)
Definition at line 21 of file common.cpp.
References _objContext, and AV_ERROR_MAX_STRING_SIZE.
Referenced by avtranscoder::InputVideo::setProfile(), avtranscoder::OutputAudio::setProfile(), avtranscoder::OutputVideo::setProfile(), and avtranscoder::InputFile::setProfile().
void avtranscoder::ParamSet::set (const std::string & key, const bool value)
Definition at line 55 of file common.cpp.
References _objContext, and AV_ERROR_MAX_STRING_SIZE.
void avtranscoder::ParamSet::set (const std::string & key, const int value)
Definition at line 66 of file common.cpp.
References _objContext, and AV_ERROR_MAX_STRING_SIZE.
void avtranscoder::ParamSet::set (const std::string & key, const int num, const int den)
Definition at line 81 of file common.cpp.
References _objContext, and AV_ERROR_MAX_STRING_SIZE.
void avtranscoder::ParamSet::set (const std::string & key, const double value)
Definition at line 97 of file common.cpp.
References _objContext, and AV_ERROR_MAX_STRING_SIZE.
void avtranscoder::ParamSet::set (const std::string & key, const std::string & value)
Definition at line 110 of file common.cpp.
References _objContext, and AV_ERROR_MAX_STRING_SIZE.
Field Documentation
void* avtranscoder::ParamSet::_objContext private
Definition at line 82 of file common.hpp.
Referenced by set().
The documentation for this class was generated from the following files:
src/AvTranscoder/common.hpp
src/AvTranscoder/common.cpp