AvTranscoder: avtranscoder::AudioEssenceTransform Class Reference
avtranscoder::AudioEssenceTransform Class Reference
#include <AudioEssenceTransform.hpp>
Public Member Functions
AudioEssenceTransform ()
void convert (const Frame &srcFrame, Frame &dstFrame)
Public Member Functions inherited from avtranscoder::EssenceTransform
EssenceTransform ()
virtual ~EssenceTransform ()
Private Member Functions
bool init (const Frame &srcFrame, const Frame &dstFrame)
Private Attributes
ResampleContext * _audioConvertContext
bool _isInit
Additional Inherited Members
Protected Member Functions inherited from avtranscoder::EssenceTransform
virtual bool init (const Frame &src, const Frame &dst)=0
Detailed Description
Definition at line 20 of file AudioEssenceTransform.hpp.
Constructor & Destructor Documentation
avtranscoder::AudioEssenceTransform::AudioEssenceTransform ()
Definition at line 36 of file AudioEssenceTransform.cpp.
Member Function Documentation
void avtranscoder::AudioEssenceTransform::convert (const Frame & srcFrame, Frame & dstFrame) virtual
Implements avtranscoder::EssenceTransform.
Definition at line 70 of file AudioEssenceTransform.cpp.
References _audioConvertContext, _isInit, avtranscoder::Frame::getBuffer(), avtranscoder::Frame::getPtr(), avtranscoder::Frame::getSize(), and init().
bool avtranscoder::AudioEssenceTransform::init (const Frame & srcFrame, const Frame & dstFrame) private
Definition at line 42 of file AudioEssenceTransform.cpp.
References _audioConvertContext, AllocResampleContext, avtranscoder::AudioFrame::desc(), FreeResampleContext, avtranscoder::AudioFrameDesc::getChannels(), avtranscoder::AudioFrameDesc::getSampleFormat(), avtranscoder::AudioFrameDesc::getSampleRate(), InitResampleContext, and SetSampleFormat.
Referenced by convert().
Field Documentation
ResampleContext* avtranscoder::AudioEssenceTransform::_audioConvertContext private
Definition at line 30 of file AudioEssenceTransform.hpp.
Referenced by convert(), and init().
bool avtranscoder::AudioEssenceTransform::_isInit private
Definition at line 32 of file AudioEssenceTransform.hpp.
Referenced by convert().
The documentation for this class was generated from the following files:
src/AvTranscoder/EssenceTransform/AudioEssenceTransform.hpp
src/AvTranscoder/EssenceTransform/AudioEssenceTransform.cpp