AvTranscoder: avtranscoder::json::JsonStreamWriter Class Reference
avtranscoder::json::JsonStreamWriter Class Reference abstract
Based class to write element to a stream.
#include <JsonWriter.hpp>
Public Member Functions
JsonStreamWriter ()
virtual ~JsonStreamWriter ()
virtual std::string build ()
template<>
JsonStreamWriter & operator<< (bool value)
template<>
JsonStreamWriter & operator<< (const char *string)
template<>
JsonStreamWriter & operator<< (JsonNull)
Protected Member Functions
template<typename T >
JsonStreamWriter & operator<< (T value)
JsonStreamWriter & addSep ()
virtual std::ostream & finish ()=0
std::string escapeJsonString (const std::string &input)
Protected Attributes
std::ostringstream stream
bool first
Friends
class JsonObjectStreamWriter
class JsonArrayStreamWriter
Detailed Description
Based class to write element to a stream.
Definition at line 24 of file JsonWriter.hpp.
Constructor & Destructor Documentation
avtranscoder::json::JsonStreamWriter::JsonStreamWriter () inline
Definition at line 27 of file JsonWriter.hpp.
virtual avtranscoder::json::JsonStreamWriter::~JsonStreamWriter () inline virtual
Definition at line 31 of file JsonWriter.hpp.
Member Function Documentation
JsonStreamWriter& avtranscoder::json::JsonStreamWriter::addSep () inline protected
Definition at line 52 of file JsonWriter.hpp.
virtual std::string avtranscoder::json::JsonStreamWriter::build () inline virtual
Definition at line 33 of file JsonWriter.hpp.
Referenced by avtranscoder::FileProperties::allPropertiesAsJson(), avtranscoder::StreamProperties::asJson(), and avtranscoder::FileProperties::asJson().
std::string avtranscoder::json::JsonStreamWriter::escapeJsonString (const std::string & input) protected
Definition at line 11 of file JsonWriter.cpp.
virtual std::ostream& avtranscoder::json::JsonStreamWriter::finish () protected pure virtual
Implemented in avtranscoder::json::JsonArrayStreamWriter, and avtranscoder::json::JsonObjectStreamWriter.
JsonStreamWriter & avtranscoder::json::JsonStreamWriter::operator<< (bool value)
Definition at line 39 of file JsonWriter.cpp.
References stream.
JsonStreamWriter & avtranscoder::json::JsonStreamWriter::operator<< (const char * string)
Definition at line 45 of file JsonWriter.cpp.
References stream.
template<typename T > JsonStreamWriter& avtranscoder::json::JsonStreamWriter::operator<< (T value) inline protected
Definition at line 46 of file JsonWriter.hpp.
JsonStreamWriter & avtranscoder::json::JsonStreamWriter::operator<< (JsonNull)
Definition at line 51 of file JsonWriter.cpp.
References stream.
Friends And Related Function Documentation
friend class JsonArrayStreamWriter friend
Definition at line 41 of file JsonWriter.hpp.
friend class JsonObjectStreamWriter friend
Definition at line 40 of file JsonWriter.hpp.
Field Documentation
bool avtranscoder::json::JsonStreamWriter::first protected
Definition at line 43 of file JsonWriter.hpp.
Referenced by avtranscoder::json::JsonObjectStreamWriter::operator<<().
std::ostringstream avtranscoder::json::JsonStreamWriter::stream protected
Definition at line 42 of file JsonWriter.hpp.
Referenced by operator<<().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/properties/JsonWriter.hpp
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/properties/JsonWriter.cpp