AvTranscoder: avtranscoder::FilterGraph Class Reference
avtranscoder::FilterGraph Class Reference
Manager of filters.
#include <FilterGraph.hpp>
Public Member Functions
FilterGraph (const ICodec &codec)
~FilterGraph ()
Filter & addFilter (const std::string &filterName, const std::string &filterOptions="", const std::string &instanceName="")
Add a filter.
void process (Frame &frame)
Pull filtered data from the filter graph, and put result to the given frame.
Private Member Functions
FilterGraph (const FilterGraph &otherFilterGraph)
FilterGraph & operator= (const FilterGraph &otherFilterGraph)
bool hasFilters () const
void init (const Frame &frame)
Initialize the graph of filters to process.
void pushFilter (Filter &filter)
Push the given Filter to the graph.
void pushInBuffer (const Frame &frame)
Push the input and output buffer at the beginning and the end of the graph.
void pushOutBuffer (const Frame &frame)
Private Attributes
AVFilterGraph * _graph
The graph which holds the filters.
std::vector< Filter * > _filters
List of filters to process.
const ICodec & _codec
Codec of the stream on which the filters will be applied.
bool _isInit
Is the FilterGraph initialized.
Detailed Description
Manager of filters.
Warning
Currently, the class manages only filters which has one input and one output.
Note
See 'complex graph' definition in ffmpeg documentation.
Definition at line 21 of file FilterGraph.hpp.
Constructor & Destructor Documentation
avtranscoder::FilterGraph::FilterGraph (const FilterGraph & otherFilterGraph) private
avtranscoder::FilterGraph::FilterGraph (const ICodec & codec)
Definition at line 19 of file FilterGraph.cpp.
References _graph.
avtranscoder::FilterGraph::~FilterGraph ()
Definition at line 29 of file FilterGraph.cpp.
References _filters, and _graph.
Member Function Documentation
Filter & avtranscoder::FilterGraph::addFilter (const std::string & filterName, const std::string & filterOptions = "", const std::string & instanceName = "")
Add a filter.
Parameters
filterName the method gets the filter definition from this name.
filterArgs options to initialize the filter with. This must be a ':'-separated list of options in the 'key=value' form.
instanceName name of the instance filter in the graph (if empty, same as filterName).
Returns
the filter added
Exceptions
runtime exception if the filter is not found
Warning
The filter will be added to the filter graph when calling process method.
See also
process
Definition at line 71 of file FilterGraph.cpp.
References _filters, and LOG_INFO.
Referenced by pushOutBuffer().
bool avtranscoder::FilterGraph::hasFilters () const inline private
Returns
If at least one filter has been added to the filter graph
Definition at line 56 of file FilterGraph.hpp.
Referenced by process().
void avtranscoder::FilterGraph::init (const Frame & frame) private
Initialize the graph of filters to process.
See also
pushFilterToGraph
pushInBuffer
pushOutBuffer
Definition at line 80 of file FilterGraph.cpp.
References _filters, _graph, _isInit, avtranscoder::getDescriptionFromErrorCode(), LOG_INFO, pushFilter(), pushInBuffer(), and pushOutBuffer().
Referenced by process().
FilterGraph& avtranscoder::FilterGraph::operator= (const FilterGraph & otherFilterGraph) private
void avtranscoder::FilterGraph::process (Frame & frame)
Pull filtered data from the filter graph, and put result to the given frame.
Parameters
frame both input and output data of the method.
Note
Do nothing if there was no filter added.
Definition at line 38 of file FilterGraph.cpp.
References _filters, _isInit, avtranscoder::Frame::getAVFrame(), avtranscoder::getDescriptionFromErrorCode(), hasFilters(), init(), and LOG_DEBUG.
Referenced by avtranscoder::StreamTranscoder::processTranscode().
void avtranscoder::FilterGraph::pushFilter (Filter & filter) private
Push the given Filter to the graph.
Definition at line 113 of file FilterGraph.cpp.
References _graph, avtranscoder::Filter::getAVFilter(), avtranscoder::getDescriptionFromErrorCode(), avtranscoder::Filter::getInstanceName(), avtranscoder::Filter::getName(), avtranscoder::Filter::getOptions(), and avtranscoder::Filter::setAVFilterContext().
Referenced by init(), pushInBuffer(), and pushOutBuffer().
void avtranscoder::FilterGraph::pushInBuffer (const Frame & frame) private
Push the input and output buffer at the beginning and the end of the graph.
Definition at line 131 of file FilterGraph.cpp.
References _codec, _filters, avtranscoder::ICodec::getAVCodecContext(), avtranscoder::AudioFrame::getChannelLayout(), avtranscoder::VideoFrame::getHeight(), avtranscoder::VideoFrame::getPixelFormat(), avtranscoder::getPixelFormatName(), avtranscoder::AudioFrame::getSampleFormat(), avtranscoder::getSampleFormatName(), avtranscoder::AudioFrame::getSampleRate(), avtranscoder::VideoFrame::getWidth(), avtranscoder::Frame::isAudioFrame(), avtranscoder::Frame::isVideoFrame(), LOG_INFO, and pushFilter().
Referenced by init().
void avtranscoder::FilterGraph::pushOutBuffer (const Frame & frame) private
Definition at line 169 of file FilterGraph.cpp.
References addFilter(), avtranscoder::Frame::isAudioFrame(), avtranscoder::Frame::isVideoFrame(), and pushFilter().
Referenced by init().
Field Documentation
const ICodec& avtranscoder::FilterGraph::_codec private
Codec of the stream on which the filters will be applied.
Definition at line 80 of file FilterGraph.hpp.
Referenced by pushInBuffer().
std::vector<Filter*> avtranscoder::FilterGraph::_filters private
List of filters to process.
Definition at line 79 of file FilterGraph.hpp.
Referenced by addFilter(), init(), process(), pushInBuffer(), and ~FilterGraph().
AVFilterGraph* avtranscoder::FilterGraph::_graph private
The graph which holds the filters.
Definition at line 78 of file FilterGraph.hpp.
Referenced by FilterGraph(), init(), pushFilter(), and ~FilterGraph().
bool avtranscoder::FilterGraph::_isInit private
Is the FilterGraph initialized.
See also
init
Definition at line 86 of file FilterGraph.hpp.
Referenced by init(), and process().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/filter/FilterGraph.hpp
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/filter/FilterGraph.cpp