AvTranscoder: avtranscoder::CodedDesc Class Reference
avtranscoder::CodedDesc Class Reference
#include <CodedDesc.hpp>
Public Member Functions
CodedDesc (const std::string &codecName)
CodedDesc (const AVCodecID codecId)
CodedDesc (AVCodec &avCodec, AVCodecContext &avCodecContext)
virtual ~CodedDesc ()
std::string getCodecName () const
AVCodecID getCodecId () const
int getLatency () const
void setCodec (const std::string &codecName)
void setCodec (const AVCodecID codecId)
AVCodec * getCodec () const
AVCodecContext * getCodecContext () const
Protected Attributes
AVCodec * m_codec
AVCodecContext * m_codecContext
Private Member Functions
void initCodecContext ()
void checkError (int error)
Detailed Description
Definition at line 14 of file CodedDesc.hpp.
Constructor & Destructor Documentation
avtranscoder::CodedDesc::CodedDesc (const std::string & codecName)
Definition at line 8 of file CodedDesc.cpp.
References setCodec().
avtranscoder::CodedDesc::CodedDesc (const AVCodecID codecId)
Definition at line 16 of file CodedDesc.cpp.
References setCodec().
avtranscoder::CodedDesc::CodedDesc (AVCodec & avCodec, AVCodecContext & avCodecContext)
Definition at line 23 of file CodedDesc.cpp.
virtual avtranscoder::CodedDesc::~CodedDesc () inline virtual
Definition at line 21 of file CodedDesc.hpp.
Member Function Documentation
void avtranscoder::CodedDesc::checkError (int error) private
AVCodec* avtranscoder::CodedDesc::getCodec () const inline
Definition at line 32 of file CodedDesc.hpp.
Referenced by avtranscoder::OutputFile::addAudioStream(), avtranscoder::OutputFile::addDataStream(), avtranscoder::OutputFile::addVideoStream(), avtranscoder::AudioDesc::AudioDesc(), avtranscoder::OutputVideo::setup(), avtranscoder::OutputAudio::setup(), and avtranscoder::VideoDesc::VideoDesc().
AVCodecContext* avtranscoder::CodedDesc::getCodecContext () const inline
Definition at line 33 of file CodedDesc.hpp.
Referenced by avtranscoder::OutputFile::addAudioStream(), avtranscoder::OutputFile::addVideoStream(), avtranscoder::AudioDesc::AudioDesc(), avtranscoder::OutputVideo::encodeFrame(), avtranscoder::OutputAudio::encodeFrame(), avtranscoder::DummyAudio::setAudioDesc(), avtranscoder::OutputVideo::setProfile(), avtranscoder::OutputAudio::setProfile(), avtranscoder::OutputVideo::setup(), avtranscoder::OutputAudio::setup(), and avtranscoder::VideoDesc::VideoDesc().
AVCodecID avtranscoder::CodedDesc::getCodecId () const
Definition at line 36 of file CodedDesc.cpp.
References m_codecContext.
Referenced by avtranscoder::InputAudio::setup(), and avtranscoder::InputVideo::setup().
std::string avtranscoder::CodedDesc::getCodecName () const
Definition at line 30 of file CodedDesc.cpp.
References m_codecContext.
int avtranscoder::CodedDesc::getLatency () const
Definition at line 42 of file CodedDesc.cpp.
References m_codecContext.
Referenced by avtranscoder::StreamTranscoder::init().
void avtranscoder::CodedDesc::initCodecContext () private
Definition at line 62 of file CodedDesc.cpp.
References m_codec, and m_codecContext.
Referenced by setCodec().
void avtranscoder::CodedDesc::setCodec (const std::string & codecName)
Definition at line 48 of file CodedDesc.cpp.
References initCodecContext(), and m_codec.
Referenced by CodedDesc(), avtranscoder::OutputVideo::setProfile(), and avtranscoder::OutputAudio::setProfile().
void avtranscoder::CodedDesc::setCodec (const AVCodecID codecId)
Definition at line 55 of file CodedDesc.cpp.
References initCodecContext(), and m_codec.
Field Documentation
AVCodec* avtranscoder::CodedDesc::m_codec protected
Definition at line 42 of file CodedDesc.hpp.
Referenced by avtranscoder::AudioDesc::AudioDesc(), initCodecContext(), setCodec(), and avtranscoder::VideoDesc::VideoDesc().
AVCodecContext* avtranscoder::CodedDesc::m_codecContext protected
Definition at line 43 of file CodedDesc.hpp.
Referenced by avtranscoder::AudioDesc::AudioDesc(), avtranscoder::AudioDesc::getChannels(), getCodecId(), getCodecName(), avtranscoder::AudioDesc::getFrameDesc(), getLatency(), avtranscoder::AudioDesc::getSampleFormat(), avtranscoder::AudioDesc::getSampleRate(), avtranscoder::VideoDesc::getTimeBase(), avtranscoder::VideoDesc::getVideoFrameDesc(), initCodecContext(), avtranscoder::AudioDesc::setAudioParameters(), avtranscoder::VideoDesc::setImageParameters(), avtranscoder::VideoDesc::setTimeBase(), and avtranscoder::VideoDesc::VideoDesc().
The documentation for this class was generated from the following files:
src/AvTranscoder/CodedStructures/CodedDesc.hpp
src/AvTranscoder/CodedStructures/CodedDesc.cpp