AvTranscoder: avtranscoder::AudioEncoder Class Reference
avtranscoder::AudioEncoder Class Reference
#include <AudioEncoder.hpp>
Public Member Functions
AudioEncoder (const std::string &audioCodecName)
~AudioEncoder ()
void setupAudioEncoder (const AudioFrameDesc &frameDesc, const ProfileLoader::Profile &profile=ProfileLoader::Profile())
void setupEncoder (const ProfileLoader::Profile &profile=ProfileLoader::Profile())
Setup the encoder.
bool encodeFrame (const Frame &sourceFrame, CodedData &codedFrame)
Encode a new frame, and get coded frame.
bool encodeFrame (CodedData &codedFrame)
Get the frames remaining into the encoder.
ICodec & getCodec ()
Get codec used for encoding.
AudioCodec & getAudioCodec ()
Public Member Functions inherited from avtranscoder::IEncoder
virtual ~IEncoder ()
Private Member Functions
bool encode (const AVFrame *decodedData, AVPacket &encodedData)
Private Attributes
AudioCodec _codec
Detailed Description
Definition at line 11 of file AudioEncoder.hpp.
Constructor & Destructor Documentation
avtranscoder::AudioEncoder::AudioEncoder (const std::string & audioCodecName)
Definition at line 14 of file AudioEncoder.cpp.
avtranscoder::AudioEncoder::~AudioEncoder ()
Definition at line 19 of file AudioEncoder.cpp.
Member Function Documentation
bool avtranscoder::AudioEncoder::encode (const AVFrame * decodedData, AVPacket & encodedData) private
Definition at line 117 of file AudioEncoder.cpp.
References _codec, avtranscoder::ICodec::getAVCodecContext(), and avtranscoder::getDescriptionFromErrorCode().
Referenced by encodeFrame().
bool avtranscoder::AudioEncoder::encodeFrame (const Frame & sourceFrame, CodedData & codedFrame) virtual
Encode a new frame, and get coded frame.
Parameters
sourceFrame frame that needs to be encoded
codedFrame output encoded coded data (first frames can be delayed)
Returns
status of encoding
Exceptions
runtime_error if the encoded process failed.
Implements avtranscoder::IEncoder.
Definition at line 94 of file AudioEncoder.cpp.
References _codec, encode(), avtranscoder::ICodec::getAVCodecContext(), avtranscoder::Frame::getAVFrame(), and avtranscoder::CodedData::getAVPacket().
bool avtranscoder::AudioEncoder::encodeFrame (CodedData & codedFrame) virtual
Get the frames remaining into the encoder.
Parameters
codedFrame output encoded data
Returns
status of encoding
Exceptions
runtime_error if the encoded process failed.
Implements avtranscoder::IEncoder.
Definition at line 112 of file AudioEncoder.cpp.
References encode(), and avtranscoder::CodedData::getAVPacket().
AudioCodec& avtranscoder::AudioEncoder::getAudioCodec () inline
Definition at line 25 of file AudioEncoder.hpp.
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
ICodec& avtranscoder::AudioEncoder::getCodec () inline virtual
Get codec used for encoding.
Returns
a reference to the codec
Implements avtranscoder::IEncoder.
Definition at line 24 of file AudioEncoder.hpp.
void avtranscoder::AudioEncoder::setupAudioEncoder (const AudioFrameDesc & frameDesc, const ProfileLoader::Profile & profile = ProfileLoader::Profile())
Definition at line 23 of file AudioEncoder.cpp.
References _codec, LOG_INFO, avtranscoder::AudioCodec::setAudioParameters(), and setupEncoder().
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::AudioEncoder::setupEncoder (const ProfileLoader::Profile & profile = ProfileLoader::Profile()) virtual
Setup the encoder.
Parameters
profile set encoder parameters from the given profile
Note
Open the encoder.
Implements avtranscoder::IEncoder.
Definition at line 37 of file AudioEncoder.cpp.
References _codec, avtranscoder::constants::avProfileCodec, avtranscoder::constants::avProfileIdentificator, avtranscoder::constants::avProfileIdentificatorHuman, avtranscoder::constants::avProfileSampleFormat, avtranscoder::constants::avProfileThreads, avtranscoder::constants::avProfileType, avtranscoder::ProfileLoader::checkAudioProfile(), avtranscoder::ICodec::getAVCodecContext(), avtranscoder::ICodec::getOption(), LOG_ERROR, LOG_WARN, avtranscoder::ICodec::openCodec(), avtranscoder::Option::setInt(), and avtranscoder::Option::setString().
Referenced by setupAudioEncoder().
Field Documentation
AudioCodec avtranscoder::AudioEncoder::_codec private
Definition at line 31 of file AudioEncoder.hpp.
Referenced by encode(), encodeFrame(), setupAudioEncoder(), and setupEncoder().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/encoder/AudioEncoder.hpp
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/encoder/AudioEncoder.cpp