AvTranscoder: /datas/cnt/workspace/avTranscoder_dev/avTranscoder/app/avProcessor/avProcessor.cpp File Reference
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/app/avProcessor/avProcessor.cpp File Reference
#include <AvTranscoder/transcoder/Transcoder.hpp>
#include <AvTranscoder/file/OutputFile.hpp>
#include <AvTranscoder/progress/ConsoleProgress.hpp>
#include <iostream>
#include <iomanip>
#include <vector>
#include <fstream>
#include <sstream>
#include <cstdlib>
Functions
void parseConfigFile (const std::string &configFilename, avtranscoder::Transcoder &transcoder)
int main (int argc, char **argv)
Variables
static const size_t dummyWidth = 1920
static const size_t dummyHeight = 1080
static const std::string dummyPixelFormat = "yuv420p"
static const std::string dummyVideoCodec = "mpeg2video"
static const size_t dummySampleRate = 48000
static const size_t dummyChannels = 1
static const std::string dummySampleFormat = "s16"
static const std::string dummyAudioCodec = "pcm_s16le"
static bool useVideoGenerator = false
Function Documentation
int main (int argc, char ** argv)
Definition at line 83 of file avProcessor.cpp.
References avtranscoder::Logger::logInFile(), parseConfigFile(), avtranscoder::preloadCodecsAndFormats(), avtranscoder::Transcoder::process(), avtranscoder::Logger::setLogLevel(), and useVideoGenerator.
void parseConfigFile (const std::string & configFilename, avtranscoder::Transcoder & transcoder)
Definition at line 24 of file avProcessor.cpp.
References avtranscoder::Transcoder::add(), dummyAudioCodec, dummyChannels, dummyHeight, dummyPixelFormat, dummySampleFormat, dummySampleRate, dummyVideoCodec, dummyWidth, avtranscoder::eCodecTypeEncoder, avtranscoder::separator, avtranscoder::AudioCodec::setAudioParameters(), avtranscoder::VideoCodec::setImageParameters(), and useVideoGenerator.
Referenced by main().
Variable Documentation
const std::string dummyAudioCodec = "pcm_s16le" [static]
Definition at line 20 of file avProcessor.cpp.
Referenced by parseConfigFile().
const size_t dummyChannels = 1 [static]
Definition at line 18 of file avProcessor.cpp.
Referenced by parseConfigFile().
const size_t dummyHeight = 1080 [static]
Definition at line 13 of file avProcessor.cpp.
Referenced by parseConfigFile().
const std::string dummyPixelFormat = "yuv420p" [static]
Definition at line 14 of file avProcessor.cpp.
Referenced by parseConfigFile().
const std::string dummySampleFormat = "s16" [static]
Definition at line 19 of file avProcessor.cpp.
Referenced by parseConfigFile().
const size_t dummySampleRate = 48000 [static]
Definition at line 17 of file avProcessor.cpp.
Referenced by parseConfigFile().
const std::string dummyVideoCodec = "mpeg2video" [static]
Definition at line 15 of file avProcessor.cpp.
Referenced by parseConfigFile().
const size_t dummyWidth = 1920 [static]
Definition at line 12 of file avProcessor.cpp.
Referenced by parseConfigFile().
bool useVideoGenerator = false [static]
Definition at line 22 of file avProcessor.cpp.
Referenced by main(), and parseConfigFile().