AvTranscoder: avtranscoder::InputAudio Class Reference
avtranscoder::InputAudio Class Reference
#include <InputAudio.hpp>
Public Member Functions
InputAudio (AvInputStream &inputStream)
~InputAudio ()
void setup ()
bool readNextFrame (Frame &frameBuffer)
bool readNextFrame (Frame &frameBuffer, const size_t subStreamIndex)
Public Member Functions inherited from avtranscoder::InputEssence
InputEssence ()
virtual ~InputEssence ()
Private Member Functions
bool getNextFrame ()
Private Attributes
AvInputStream * _inputStream
AVCodec * _codec
AVCodecContext * _codecContext
AVFrame * _frame
int _selectedStream
Detailed Description
Definition at line 15 of file InputAudio.hpp.
Constructor & Destructor Documentation
avtranscoder::InputAudio::InputAudio (AvInputStream & inputStream)
Definition at line 23 of file InputAudio.cpp.
avtranscoder::InputAudio::~InputAudio ()
Definition at line 33 of file InputAudio.cpp.
References _codecContext, and _frame.
Member Function Documentation
bool avtranscoder::InputAudio::getNextFrame () private
Definition at line 176 of file InputAudio.cpp.
References _codecContext, _frame, _inputStream, _selectedStream, avtranscoder::DataStream::getPtr(), avtranscoder::DataStream::getSize(), and avtranscoder::AvInputStream::readNextPacket().
Referenced by readNextFrame().
bool avtranscoder::InputAudio::readNextFrame (Frame & frameBuffer) virtual
Implements avtranscoder::InputEssence.
Definition at line 104 of file InputAudio.cpp.
References _codecContext, _frame, avtranscoder::Frame::getBuffer(), getNextFrame(), avtranscoder::Frame::getPtr(), avtranscoder::Frame::getSize(), and avtranscoder::AudioFrame::setNbSamples().
bool avtranscoder::InputAudio::readNextFrame (Frame & frameBuffer, const size_t subStreamIndex) virtual
Implements avtranscoder::InputEssence.
Definition at line 131 of file InputAudio.cpp.
References _codecContext, _frame, avtranscoder::Frame::getBuffer(), getNextFrame(), avtranscoder::Frame::getPtr(), avtranscoder::Frame::getSize(), and avtranscoder::AudioFrame::setNbSamples().
void avtranscoder::InputAudio::setup () virtual
Implements avtranscoder::InputEssence.
Definition at line 57 of file InputAudio.cpp.
References _codec, _codecContext, _frame, _inputStream, avtranscoder::AvInputStream::getAudioDesc(), avtranscoder::AudioDesc::getChannels(), and avtranscoder::CodedDesc::getCodecId().
Field Documentation
AVCodec* avtranscoder::InputAudio::_codec private
Definition at line 30 of file InputAudio.hpp.
Referenced by setup().
AVCodecContext* avtranscoder::InputAudio::_codecContext private
Definition at line 31 of file InputAudio.hpp.
Referenced by getNextFrame(), readNextFrame(), setup(), and ~InputAudio().
AVFrame* avtranscoder::InputAudio::_frame private
Definition at line 32 of file InputAudio.hpp.
Referenced by getNextFrame(), readNextFrame(), setup(), and ~InputAudio().
AvInputStream* avtranscoder::InputAudio::_inputStream private
Definition at line 29 of file InputAudio.hpp.
Referenced by getNextFrame(), and setup().
int avtranscoder::InputAudio::_selectedStream private
Definition at line 34 of file InputAudio.hpp.
Referenced by getNextFrame().
The documentation for this class was generated from the following files:
src/AvTranscoder/EssenceStream/InputAudio.hpp
src/AvTranscoder/EssenceStream/InputAudio.cpp