AvTranscoder: avtranscoder::AudioReader Class Reference
avtranscoder::AudioReader Class Reference
#include <AudioReader.hpp>
Public Member Functions
~AudioReader ()
void updateOutput (const size_t sampleRate, const size_t nbChannels, const std::string &sampleFormat)
Update sample rate, number of channels and sample format of the output.
const AudioProperties * getSourceAudioProperties () const
AudioReader (const std::string &filename, const size_t streamIndex=0, const int channelIndex=-1)
AudioReader (InputFile &inputFile, const size_t streamIndex=0, const int channelIndex=-1)
size_t getOutputSampleRate () const
size_t getOutputNbChannels () const
AVSampleFormat getOutputSampleFormat () const
Public Member Functions inherited from avtranscoder::IReader
IReader (const std::string &filename, const size_t streamIndex=0, const int channelIndex=-1)
Create a new InputFile and prepare to read the stream at the given index.
IReader (InputFile &inputFile, const size_t streamIndex=0, const int channelIndex=-1)
Get the existing InputFile and prepare to read the stream at the given index.
virtual ~IReader ()=0
Frame * readNextFrame ()
Frame * readPrevFrame ()
Frame * readFrameAt (const size_t frame)
const StreamProperties * getSourceProperties () const
Get the properties of the source stream read.
void continueWithGenerator (const bool continueWithGenerator=true)
Set the reader state to generate data (ie silence or black) when there is no more data to decode.
Private Member Functions
void init ()
Private Attributes
const AudioProperties * _audioStreamProperties
Properties of the source audio stream read (no ownership, has link)
size_t _outputSampleRate
size_t _outputNbChannels
AVSampleFormat _outputSampleFormat
Additional Inherited Members
Protected Attributes inherited from avtranscoder::IReader
InputFile * _inputFile
const StreamProperties * _streamProperties
IDecoder * _decoder
IDecoder * _generator
IDecoder * _currentDecoder
Link to _inputDecoder or _generator.
Frame * _srcFrame
Frame * _dstFrame
ITransform * _transform
size_t _streamIndex
int _channelIndex
Detailed Description
Definition at line 12 of file AudioReader.hpp.
Constructor & Destructor Documentation
avtranscoder::AudioReader::AudioReader (const std::string & filename, const size_t streamIndex = 0, const int channelIndex = -1)
Definition at line 13 of file AudioReader.cpp.
References init().
avtranscoder::AudioReader::AudioReader (InputFile & inputFile, const size_t streamIndex = 0, const int channelIndex = -1)
Definition at line 23 of file AudioReader.cpp.
References init().
avtranscoder::AudioReader::~AudioReader ()
Definition at line 62 of file AudioReader.cpp.
References avtranscoder::IReader::_decoder, avtranscoder::IReader::_dstFrame, avtranscoder::IReader::_generator, avtranscoder::IReader::_srcFrame, and avtranscoder::IReader::_transform.
Member Function Documentation
size_t avtranscoder::AudioReader::getOutputNbChannels () const inline
Definition at line 33 of file AudioReader.hpp.
AVSampleFormat avtranscoder::AudioReader::getOutputSampleFormat () const inline
Definition at line 34 of file AudioReader.hpp.
size_t avtranscoder::AudioReader::getOutputSampleRate () const inline
Definition at line 32 of file AudioReader.hpp.
const AudioProperties* avtranscoder::AudioReader::getSourceAudioProperties () const inline
Definition at line 38 of file AudioReader.hpp.
void avtranscoder::AudioReader::init () private
Definition at line 33 of file AudioReader.cpp.
References _audioStreamProperties, avtranscoder::IReader::_channelIndex, avtranscoder::IReader::_currentDecoder, avtranscoder::IReader::_decoder, avtranscoder::IReader::_dstFrame, avtranscoder::IReader::_generator, avtranscoder::IReader::_inputFile, _outputNbChannels, _outputSampleFormat, _outputSampleRate, avtranscoder::IReader::_srcFrame, avtranscoder::IReader::_streamIndex, avtranscoder::IReader::_streamProperties, avtranscoder::IReader::_transform, avtranscoder::InputFile::activateStream(), avtranscoder::InputFile::analyse(), avtranscoder::InputStream::getAudioCodec(), avtranscoder::AudioCodec::getAudioFrameDesc(), avtranscoder::InputFile::getProperties(), avtranscoder::InputFile::getStream(), avtranscoder::FileProperties::getStreamPropertiesWithIndex(), and avtranscoder::IDecoder::setupDecoder().
Referenced by AudioReader().
void avtranscoder::AudioReader::updateOutput (const size_t sampleRate, const size_t nbChannels, const std::string & sampleFormat)
Update sample rate, number of channels and sample format of the output.
Note
Will transform the decoded data when read the stream.
Definition at line 71 of file AudioReader.cpp.
References avtranscoder::IReader::_dstFrame, _outputNbChannels, _outputSampleFormat, _outputSampleRate, and avtranscoder::getAVSampleFormat().
Field Documentation
const AudioProperties* avtranscoder::AudioReader::_audioStreamProperties private
Properties of the source audio stream read (no ownership, has link)
Definition at line 44 of file AudioReader.hpp.
Referenced by init().
size_t avtranscoder::AudioReader::_outputNbChannels private
Definition at line 49 of file AudioReader.hpp.
Referenced by init(), and updateOutput().
AVSampleFormat avtranscoder::AudioReader::_outputSampleFormat private
Definition at line 50 of file AudioReader.hpp.
Referenced by init(), and updateOutput().
size_t avtranscoder::AudioReader::_outputSampleRate private
Definition at line 48 of file AudioReader.hpp.
Referenced by init(), and updateOutput().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/reader/AudioReader.hpp
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/reader/AudioReader.cpp