AvTranscoder: avtranscoder::IInputStream Class Reference
avtranscoder::IInputStream Class Reference abstract
#include <IInputStream.hpp>
Public Member Functions
virtual ~IInputStream ()
virtual bool readNextPacket (CodedData &data)=0
Read the next packet of the stream.
virtual const StreamProperties & getProperties () const =0
virtual size_t getStreamIndex () const =0
virtual VideoCodec & getVideoCodec ()=0
virtual AudioCodec & getAudioCodec ()=0
virtual DataCodec & getDataCodec ()=0
virtual void activate (const bool activate=true)=0
Functions about buffering Activate the stream will buffered its data when read packets.
virtual bool isActivated () const =0
virtual void clearBuffering ()=0
Detailed Description
Definition at line 15 of file IInputStream.hpp.
Constructor & Destructor Documentation
virtual avtranscoder::IInputStream::~IInputStream () inline virtual
Definition at line 18 of file IInputStream.hpp.
Member Function Documentation
virtual void avtranscoder::IInputStream::activate (const bool activate = true) pure virtual
Functions about buffering Activate the stream will buffered its data when read packets.
See also
IInputStream methods
Implemented in avtranscoder::InputStream.
virtual void avtranscoder::IInputStream::clearBuffering () pure virtual
Implemented in avtranscoder::InputStream.
virtual AudioCodec& avtranscoder::IInputStream::getAudioCodec () pure virtual
Implemented in avtranscoder::InputStream.
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
virtual DataCodec& avtranscoder::IInputStream::getDataCodec () pure virtual
Implemented in avtranscoder::InputStream.
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
virtual const StreamProperties& avtranscoder::IInputStream::getProperties () const pure virtual
Note
The returned object could be cast depending on the type of the stream (video, audio...)
See also
VideoProperties, AudioProperties...
Returns
the properties of the stream
Implemented in avtranscoder::InputStream.
Referenced by avtranscoder::Transcoder::fillProcessStat(), avtranscoder::StreamTranscoder::getDuration(), avtranscoder::StreamTranscoder::processFrame(), and avtranscoder::StreamTranscoder::StreamTranscoder().
virtual size_t avtranscoder::IInputStream::getStreamIndex () const pure virtual
Returns
the index of the stream
Implemented in avtranscoder::InputStream.
Referenced by avtranscoder::StreamTranscoder::needToSwitchToGenerator(), avtranscoder::StreamTranscoder::preProcessCodecLatency(), and avtranscoder::StreamTranscoder::StreamTranscoder().
virtual VideoCodec& avtranscoder::IInputStream::getVideoCodec () pure virtual
Return the codec informations of the stream
Exceptions
Raise a runtime error if the stream is not of the corresponding type
Implemented in avtranscoder::InputStream.
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
virtual bool avtranscoder::IInputStream::isActivated () const pure virtual
Implemented in avtranscoder::InputStream.
virtual bool avtranscoder::IInputStream::readNextPacket (CodedData & data) pure virtual
Read the next packet of the stream.
Parameters
data data of next packet read
Returns
if next packet was read succefully
Implemented in avtranscoder::InputStream.
Referenced by avtranscoder::StreamTranscoder::processRewrap().
The documentation for this class was generated from the following file:
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/stream/IInputStream.hpp