AvTranscoder: avtranscoder::AudioTransform Class Reference
avtranscoder::AudioTransform Class Reference
#include <AudioTransform.hpp>
Public Member Functions
AudioTransform ()
~AudioTransform ()
void convert (const Frame &srcFrame, Frame &dstFrame)
Private Member Functions
AudioTransform (const AudioTransform &audioTransform)
AudioTransform & operator= (const AudioTransform &audioTransform)
bool init (const Frame &srcFrame, const Frame &dstFrame)
void updateOutputFrame (const size_t nbInputSamples, Frame &dstFrame) const
Update output buffer if source has a different size from the last process.
Private Attributes
ResampleContext * _audioConvertContext
size_t _nbSamplesOfPreviousFrame
To check if the number of samples change between frames.
bool _isInit
Detailed Description
Definition at line 20 of file AudioTransform.hpp.
Constructor & Destructor Documentation
avtranscoder::AudioTransform::AudioTransform (const AudioTransform & audioTransform) [private]
avtranscoder::AudioTransform::AudioTransform ()
Definition at line 33 of file AudioTransform.cpp.
avtranscoder::AudioTransform::~AudioTransform ()
Definition at line 40 of file AudioTransform.cpp.
References _audioConvertContext, and FreeResampleContext.
Member Function Documentation
void avtranscoder::AudioTransform::convert (const Frame & srcFrame, Frame & dstFrame) [virtual]
Implements avtranscoder::ITransform.
Definition at line 85 of file AudioTransform.cpp.
References _audioConvertContext, _isInit, _nbSamplesOfPreviousFrame, avtranscoder::Frame::getData(), init(), and updateOutputFrame().
bool avtranscoder::AudioTransform::init (const Frame & srcFrame, const Frame & dstFrame) [private, virtual]
Implements avtranscoder::ITransform.
Definition at line 45 of file AudioTransform.cpp.
References _audioConvertContext, AllocResampleContext, avtranscoder::AudioFrame::desc(), FreeResampleContext, avtranscoder::AudioFrameDesc::getChannels(), avtranscoder::AudioFrameDesc::getSampleFormat(), avtranscoder::AudioFrameDesc::getSampleRate(), InitResampleContext, and SetSampleFormat.
Referenced by convert().
AudioTransform& avtranscoder::AudioTransform::operator= (const AudioTransform & audioTransform) [private]
void avtranscoder::AudioTransform::updateOutputFrame (const size_t nbInputSamples, Frame & dstFrame) const [private]
Update output buffer if source has a different size from the last process.
Definition at line 72 of file AudioTransform.cpp.
References avtranscoder::AudioFrame::desc(), avtranscoder::AudioFrameDesc::getChannels(), avtranscoder::AudioFrameDesc::getSampleFormat(), avtranscoder::Frame::resize(), and avtranscoder::AudioFrame::setNbSamples().
Referenced by convert().
Field Documentation
ResampleContext* avtranscoder::AudioTransform::_audioConvertContext [private]
Definition at line 39 of file AudioTransform.hpp.
Referenced by convert(), init(), and ~AudioTransform().
bool avtranscoder::AudioTransform::_isInit [private]
Definition at line 43 of file AudioTransform.hpp.
Referenced by convert().
size_t avtranscoder::AudioTransform::_nbSamplesOfPreviousFrame [private]
To check if the number of samples change between frames.
Definition at line 41 of file AudioTransform.hpp.
Referenced by convert().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/transform/AudioTransform.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/transform/AudioTransform.cpp