AvTranscoder: Window Class Reference
Window Class Reference
#include <Window.hpp>
Public Member Functions
Window (avtranscoder::VideoReader &reader)
void launch ()
Static Private Member Functions
static void display ()
static void keyboard (unsigned char k, int x, int y)
static void specialKeyboard (int k, int x, int y)
static void mouse (int button, int state, int x, int y)
static void motion (int x, int y)
static void reshape (int width, int height)
static void displayHelp ()
static void displayInformations ()
static void move (float x, float y)
static void zoom (float factor)
static void mapToImage (int x, int y, int &iX, int &iY)
static void setTransfert (float red, float green, float blue, float alpha=1.f)
static void displayChannelTexture (bool &channel, const float red, const float green, const float blue)
static void showRedChannelTexture ()
static void showGreenChannelTexture ()
static void showBlueChannelTexture ()
static void showAlphaChannelTexture ()
static void displayNextFrame ()
static void displayPrevFrame ()
static void displayFirstFrame ()
static void displayAtFrame (const size_t frame)
static void loopPlaying (int value)
Static Private Attributes
static avtranscoder::VideoReader * _reader = NULL
static size_t _width = 0
static size_t _height = 0
static int _x1 = -1.0
static int _x2 = 1.0
static int _y1 = 1.0
static int _y2 = -1.0
static int _xMinViewport = 0
static int _yMinViewport = 0
static int _xMouseRef = 0
static int _yMouseRef = 0
static int _windowId = 0
static float _currentZoom = 1.0
static float _factorZoom = 1.25
static float _scale = 1.0
static bool _play = false
static bool _flip = false
static bool _flop = false
static bool _showRedChannel = false
static bool _showGreenChannel = false
static bool _showBlueChannel = false
static bool _showAlphaChannel = false
Detailed Description
Definition at line 8 of file Window.hpp.
Constructor & Destructor Documentation
Window::Window (avtranscoder::VideoReader & reader)
Definition at line 102 of file Window.cpp.
References _height, _reader, _width, _windowId, display(), avtranscoder::VideoReader::getOutputHeight(), avtranscoder::VideoReader::getOutputWidth(), keyboard(), motion(), mouse(), reshape(), and specialKeyboard().
Member Function Documentation
void Window::display () static private
Definition at line 136 of file Window.cpp.
References _flip, _flop, _x1, _x2, _y1, and _y2.
Referenced by displayAtFrame(), displayNextFrame(), displayPrevFrame(), and Window().
void Window::displayAtFrame (const size_t frame) static private
Definition at line 570 of file Window.cpp.
References _reader, display(), avtranscoder::Frame::getData(), avtranscoder::VideoReader::getOutputHeight(), avtranscoder::VideoReader::getOutputNbComponents(), avtranscoder::VideoReader::getOutputWidth(), loadNewTexture(), and avtranscoder::IReader::readFrameAt().
Referenced by displayFirstFrame().
void Window::displayChannelTexture (bool & channel, const float red, const float green, const float blue) static private
Definition at line 507 of file Window.cpp.
References _imageProperties, _showAlphaChannel, _showBlueChannel, _showGreenChannel, _showRedChannel, loadNewTexture(), and setTransfert().
Referenced by showBlueChannelTexture(), showGreenChannelTexture(), and showRedChannelTexture().
void Window::displayFirstFrame () static private
Definition at line 565 of file Window.cpp.
References displayAtFrame().
Referenced by launch(), and specialKeyboard().
void Window::displayHelp () static private
Definition at line 397 of file Window.cpp.
Referenced by keyboard(), and specialKeyboard().
void Window::displayInformations () static private
Definition at line 411 of file Window.cpp.
References _height, _reader, _width, ImgProperties::format, avtranscoder::VideoReader::getSourceVideoProperties(), and ImgProperties::type.
Referenced by keyboard().
void Window::displayNextFrame () static private
Definition at line 549 of file Window.cpp.
References _reader, display(), avtranscoder::Frame::getData(), avtranscoder::VideoReader::getOutputHeight(), avtranscoder::VideoReader::getOutputNbComponents(), avtranscoder::VideoReader::getOutputWidth(), loadNewTexture(), and avtranscoder::IReader::readNextFrame().
Referenced by loopPlaying(), and specialKeyboard().
void Window::displayPrevFrame () static private
Definition at line 557 of file Window.cpp.
References _reader, display(), avtranscoder::Frame::getData(), avtranscoder::VideoReader::getOutputHeight(), avtranscoder::VideoReader::getOutputNbComponents(), avtranscoder::VideoReader::getOutputWidth(), loadNewTexture(), and avtranscoder::IReader::readPrevFrame().
Referenced by specialKeyboard().
void Window::keyboard (unsigned char k, int x, int y) static private
Definition at line 179 of file Window.cpp.
References _currentZoom, _flip, _flop, _height, _play, _width, _windowId, _x1, _x2, _y1, _y2, displayHelp(), displayInformations(), loopPlaying(), showAlphaChannelTexture(), showBlueChannelTexture(), showGreenChannelTexture(), and showRedChannelTexture().
Referenced by Window().
void Window::launch ()
Definition at line 130 of file Window.cpp.
References displayFirstFrame().
Referenced by main().
void Window::loopPlaying (int value) static private
Definition at line 578 of file Window.cpp.
References _play, and displayNextFrame().
Referenced by keyboard().
void Window::mapToImage (int x, int y, int & iX, int & iY) static private
Definition at line 462 of file Window.cpp.
References _currentZoom, _flip, _flop, _scale, _x1, _xMinViewport, _y1, _yMinViewport, ImgProperties::height, and ImgProperties::width.
Referenced by mouse().
void Window::motion (int x, int y) static private
Definition at line 344 of file Window.cpp.
References _currentZoom, _flip, _flop, _xMouseRef, _yMouseRef, ImgProperties::height, move(), and ImgProperties::width.
Referenced by Window().
void Window::mouse (int button, int state, int x, int y) static private
Definition at line 275 of file Window.cpp.
References _currentZoom, _factorZoom, _xMouseRef, _yMouseRef, ImgProperties::component, ImgProperties::data, ImgProperties::height, mapToImage(), move(), ImgProperties::type, ImgProperties::width, and zoom().
Referenced by Window().
void Window::move (float x, float y) static private
Definition at line 446 of file Window.cpp.
References _x1, _x2, _y1, and _y2.
Referenced by motion(), and mouse().
void Window::reshape (int width, int height) static private
Definition at line 369 of file Window.cpp.
References _height, _scale, _width, _xMinViewport, and _yMinViewport.
Referenced by Window().
void Window::setTransfert (float red, float green, float blue, float alpha = 1.f) static private
Definition at line 487 of file Window.cpp.
References ImgProperties::format.
Referenced by displayChannelTexture().
void Window::showAlphaChannelTexture () static private
Definition at line 544 of file Window.cpp.
Referenced by keyboard().
void Window::showBlueChannelTexture () static private
Definition at line 539 of file Window.cpp.
References _showBlueChannel, and displayChannelTexture().
Referenced by keyboard().
void Window::showGreenChannelTexture () static private
Definition at line 534 of file Window.cpp.
References _showGreenChannel, and displayChannelTexture().
Referenced by keyboard().
void Window::showRedChannelTexture () static private
Definition at line 529 of file Window.cpp.
References _showRedChannel, and displayChannelTexture().
Referenced by keyboard().
void Window::specialKeyboard (int k, int x, int y) static private
Definition at line 246 of file Window.cpp.
References displayFirstFrame(), displayHelp(), displayNextFrame(), and displayPrevFrame().
Referenced by Window().
void Window::zoom (float factor) static private
Definition at line 454 of file Window.cpp.
References _x1, _x2, _y1, and _y2.
Referenced by mouse().
Field Documentation
float Window::_currentZoom = 1.0 static private
Definition at line 64 of file Window.hpp.
Referenced by keyboard(), mapToImage(), motion(), and mouse().
float Window::_factorZoom = 1.25 static private
Definition at line 65 of file Window.hpp.
Referenced by mouse().
bool Window::_flip = false static private
Definition at line 71 of file Window.hpp.
Referenced by display(), keyboard(), mapToImage(), and motion().
bool Window::_flop = false static private
Definition at line 72 of file Window.hpp.
Referenced by display(), keyboard(), mapToImage(), and motion().
size_t Window::_height = 0 static private
Definition at line 48 of file Window.hpp.
Referenced by displayInformations(), keyboard(), reshape(), and Window().
bool Window::_play = false static private
Definition at line 69 of file Window.hpp.
Referenced by keyboard(), and loopPlaying().
avtranscoder::VideoReader * Window::_reader = NULL static private
Definition at line 45 of file Window.hpp.
Referenced by displayAtFrame(), displayInformations(), displayNextFrame(), displayPrevFrame(), and Window().
float Window::_scale = 1.0 static private
Definition at line 67 of file Window.hpp.
Referenced by mapToImage(), and reshape().
bool Window::_showAlphaChannel = false static private
Definition at line 77 of file Window.hpp.
Referenced by displayChannelTexture().
bool Window::_showBlueChannel = false static private
Definition at line 76 of file Window.hpp.
Referenced by displayChannelTexture(), and showBlueChannelTexture().
bool Window::_showGreenChannel = false static private
Definition at line 75 of file Window.hpp.
Referenced by displayChannelTexture(), and showGreenChannelTexture().
bool Window::_showRedChannel = false static private
Definition at line 74 of file Window.hpp.
Referenced by displayChannelTexture(), and showRedChannelTexture().
size_t Window::_width = 0 static private
Definition at line 47 of file Window.hpp.
Referenced by displayInformations(), keyboard(), reshape(), and Window().
int Window::_windowId = 0 static private
Definition at line 61 of file Window.hpp.
Referenced by keyboard(), and Window().
int Window::_x1 = -1.0 static private
Definition at line 50 of file Window.hpp.
Referenced by display(), keyboard(), mapToImage(), move(), and zoom().
int Window::_x2 = 1.0 static private
Definition at line 51 of file Window.hpp.
Referenced by display(), keyboard(), move(), and zoom().
int Window::_xMinViewport = 0 static private
Definition at line 55 of file Window.hpp.
Referenced by mapToImage(), and reshape().
int Window::_xMouseRef = 0 static private
Definition at line 58 of file Window.hpp.
Referenced by motion(), and mouse().
int Window::_y1 = 1.0 static private
Definition at line 52 of file Window.hpp.
Referenced by display(), keyboard(), mapToImage(), move(), and zoom().
int Window::_y2 = -1.0 static private
Definition at line 53 of file Window.hpp.
Referenced by display(), keyboard(), move(), and zoom().
int Window::_yMinViewport = 0 static private
Definition at line 56 of file Window.hpp.
Referenced by mapToImage(), and reshape().
int Window::_yMouseRef = 0 static private
Definition at line 59 of file Window.hpp.
Referenced by motion(), and mouse().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder/app/avPlayer/Window.hpp
/datas/cnt/workspace/avTranscoder/app/avPlayer/Window.cpp