var searchData=
[
  ['videocodec',['VideoCodec',['../de/d3d/classavtranscoder_1_1VideoCodec.html',1,'avtranscoder']]],
  ['videocodec',['VideoCodec',['../de/d3d/classavtranscoder_1_1VideoCodec.html#af486922c29ad437fca19d2394afa5068',1,'avtranscoder::VideoCodec::VideoCodec(const ECodecType type, const std::string &amp;codecName=&quot;&quot;)'],['../de/d3d/classavtranscoder_1_1VideoCodec.html#a85a743da95dc31a56d7a33d7976d6c33',1,'avtranscoder::VideoCodec::VideoCodec(const ECodecType type, const AVCodecID codecId)'],['../de/d3d/classavtranscoder_1_1VideoCodec.html#aa2eb2fd25b1ace6431e978964e16e316',1,'avtranscoder::VideoCodec::VideoCodec(const ECodecType type, AVCodecContext &amp;avCodecContext)']]],
  ['videocodec_2ecpp',['VideoCodec.cpp',['../d7/da2/VideoCodec_8cpp.html',1,'']]],
  ['videocodec_2ehpp',['VideoCodec.hpp',['../de/d28/VideoCodec_8hpp.html',1,'']]],
  ['videodecoder',['VideoDecoder',['../dd/d47/classavtranscoder_1_1VideoDecoder.html',1,'avtranscoder']]],
  ['videodecoder',['VideoDecoder',['../dd/d47/classavtranscoder_1_1VideoDecoder.html#aef42312d3fb783c2543f6d6d9986ba4f',1,'avtranscoder::VideoDecoder']]],
  ['videodecoder_2ecpp',['VideoDecoder.cpp',['../db/d02/VideoDecoder_8cpp.html',1,'']]],
  ['videodecoder_2ehpp',['VideoDecoder.hpp',['../d2/dd8/VideoDecoder_8hpp.html',1,'']]],
  ['videoencoder',['VideoEncoder',['../d8/d7e/classavtranscoder_1_1VideoEncoder.html',1,'avtranscoder']]],
  ['videoencoder',['VideoEncoder',['../d8/d7e/classavtranscoder_1_1VideoEncoder.html#ac921b6e28d2d1a8ad61d65de94cffde4',1,'avtranscoder::VideoEncoder']]],
  ['videoencoder_2ecpp',['VideoEncoder.cpp',['../d3/d55/VideoEncoder_8cpp.html',1,'']]],
  ['videoencoder_2ehpp',['VideoEncoder.hpp',['../de/d2c/VideoEncoder_8hpp.html',1,'']]],
  ['videoframe',['VideoFrame',['../d3/da8/classavtranscoder_1_1VideoFrame.html',1,'avtranscoder']]],
  ['videoframe',['VideoFrame',['../d3/da8/classavtranscoder_1_1VideoFrame.html#ac3f835d9fec00a5e35c1be76d3c67008',1,'avtranscoder::VideoFrame::VideoFrame(const VideoFrameDesc &amp;ref)'],['../d3/da8/classavtranscoder_1_1VideoFrame.html#a4f2101b5cdc511070bcb144d317abb99',1,'avtranscoder::VideoFrame::VideoFrame(const Frame &amp;otherFrame)']]],
  ['videoframe_2ecpp',['VideoFrame.cpp',['../d1/de2/VideoFrame_8cpp.html',1,'']]],
  ['videoframe_2ehpp',['VideoFrame.hpp',['../d3/dc8/VideoFrame_8hpp.html',1,'']]],
  ['videoframedesc',['VideoFrameDesc',['../d3/dfb/structavtranscoder_1_1VideoFrameDesc.html',1,'avtranscoder']]],
  ['videoframedesc',['VideoFrameDesc',['../d3/dfb/structavtranscoder_1_1VideoFrameDesc.html#a5e6042159301a0524dd825a9090c9d66',1,'avtranscoder::VideoFrameDesc::VideoFrameDesc(const size_t width=0, const size_t height=0, const AVPixelFormat pixelFormat=AV_PIX_FMT_NONE)'],['../d3/dfb/structavtranscoder_1_1VideoFrameDesc.html#ae1f0be3bf077c4e0616df2afb6227b35',1,'avtranscoder::VideoFrameDesc::VideoFrameDesc(const size_t width, const size_t height, const std::string &amp;pixelFormatName)']]],
  ['videogenerator',['VideoGenerator',['../d3/da8/classavtranscoder_1_1VideoFrame.html#ad0ae5d0f80202ca70b8b151dc977746c',1,'avtranscoder::VideoFrame::VideoGenerator()'],['../df/d9d/classavtranscoder_1_1VideoGenerator.html#a1cbbde8c89b588dd0fdb6b41dbe40007',1,'avtranscoder::VideoGenerator::VideoGenerator(const VideoGenerator &amp;videoGenerator)'],['../df/d9d/classavtranscoder_1_1VideoGenerator.html#ac314587b1b5f50ffc25276a81821ef85',1,'avtranscoder::VideoGenerator::VideoGenerator(const VideoFrameDesc &amp;frameDesc)']]],
  ['videogenerator',['VideoGenerator',['../df/d9d/classavtranscoder_1_1VideoGenerator.html',1,'avtranscoder']]],
  ['videogenerator_2ecpp',['VideoGenerator.cpp',['../db/dbf/VideoGenerator_8cpp.html',1,'']]],
  ['videogenerator_2ehpp',['VideoGenerator.hpp',['../d0/d25/VideoGenerator_8hpp.html',1,'']]],
  ['videoproperties',['VideoProperties',['../df/d47/classavtranscoder_1_1VideoProperties.html#af3b20afb518112e6a4ce423e1e85997e',1,'avtranscoder::VideoProperties']]],
  ['videoproperties',['VideoProperties',['../df/d47/classavtranscoder_1_1VideoProperties.html',1,'avtranscoder']]],
  ['videoproperties_2ecpp',['VideoProperties.cpp',['../d7/d2f/VideoProperties_8cpp.html',1,'']]],
  ['videoproperties_2ehpp',['VideoProperties.hpp',['../d8/d13/VideoProperties_8hpp.html',1,'']]],
  ['videoreader',['VideoReader',['../d7/d8e/classavtranscoder_1_1VideoReader.html',1,'avtranscoder']]],
  ['videoreader',['VideoReader',['../d7/d8e/classavtranscoder_1_1VideoReader.html#a0932ab57333bcf64d4a061ae77c9d070',1,'avtranscoder::VideoReader::VideoReader(const std::string &amp;filename, const size_t videoStreamIndex=0)'],['../d7/d8e/classavtranscoder_1_1VideoReader.html#ac217c6a43d063d9e70b0eeead326bb1f',1,'avtranscoder::VideoReader::VideoReader(InputFile &amp;inputFile, const size_t videoStreamIndex=0)']]],
  ['videoreader_2ecpp',['VideoReader.cpp',['../d0/dae/VideoReader_8cpp.html',1,'']]],
  ['videoreader_2ehpp',['VideoReader.hpp',['../d7/d76/VideoReader_8hpp.html',1,'']]],
  ['videostat',['VideoStat',['../d4/d8d/classavtranscoder_1_1VideoStat.html',1,'avtranscoder']]],
  ['videostat',['VideoStat',['../d4/d8d/classavtranscoder_1_1VideoStat.html#ae730c99d31b3d6f65d607c54c6c1f137',1,'avtranscoder::VideoStat']]],
  ['videostat_2ecpp',['VideoStat.cpp',['../d2/d5f/VideoStat_8cpp.html',1,'']]],
  ['videostat_2ehpp',['VideoStat.hpp',['../d6/db3/VideoStat_8hpp.html',1,'']]],
  ['videotransform',['VideoTransform',['../d4/d60/classavtranscoder_1_1VideoTransform.html',1,'avtranscoder']]],
  ['videotransform',['VideoTransform',['../d4/d60/classavtranscoder_1_1VideoTransform.html#ab3b22b5ff5a4eb6c8e5c9b0c76d5c641',1,'avtranscoder::VideoTransform::VideoTransform(const VideoTransform &amp;videoTransform)'],['../d4/d60/classavtranscoder_1_1VideoTransform.html#a1724be80af3607e635d683a7303f1f4a',1,'avtranscoder::VideoTransform::VideoTransform()']]],
  ['videotransform_2ecpp',['VideoTransform.cpp',['../d4/de8/VideoTransform_8cpp.html',1,'']]],
  ['videotransform_2ehpp',['VideoTransform.hpp',['../de/d5a/VideoTransform_8hpp.html',1,'']]]
];
