AvTranscoder: avtranscoder::OutputVideo Class Reference
avtranscoder::OutputVideo Class Reference
#include <OutputVideo.hpp>
Public Member Functions
OutputVideo ()
void setup ()
Setup the encoder.
bool encodeFrame (const Frame &sourceFrame, DataStream &codedFrame)
bool encodeFrame (DataStream &codedFrame)
void setProfile (const Profile::ProfileDesc &desc, const avtranscoder::VideoFrameDesc &frameDesc)
VideoDesc getVideoDesc ()
Public Member Functions inherited from avtranscoder::OutputEssence
OutputEssence (const std::string &codecName)
virtual ~OutputEssence ()
CodedDesc & getCodedDesc ()
Additional Inherited Members
Protected Attributes inherited from avtranscoder::OutputEssence
CodedDesc _codedDesc
Detailed Description
Definition at line 15 of file OutputVideo.hpp.
Constructor & Destructor Documentation
avtranscoder::OutputVideo::OutputVideo ()
Definition at line 19 of file OutputVideo.cpp.
Member Function Documentation
bool avtranscoder::OutputVideo::encodeFrame (const Frame & sourceFrame, DataStream & codedFrame) virtual
Parameters
[out] codedFrame blabla
Implements avtranscoder::OutputEssence.
Definition at line 48 of file OutputVideo.cpp.
References avtranscoder::OutputEssence::_codedDesc, avtranscoder::DataStream::getBuffer(), avtranscoder::CodedDesc::getCodecContext(), avtranscoder::DataStream::getPtr(), and avtranscoder::Frame::getPtr().
bool avtranscoder::OutputVideo::encodeFrame (DataStream & codedFrame) virtual
get delayed encoded frames
Implements avtranscoder::OutputEssence.
Definition at line 141 of file OutputVideo.cpp.
References avtranscoder::OutputEssence::_codedDesc, avtranscoder::DataStream::getBuffer(), avtranscoder::CodedDesc::getCodecContext(), and avtranscoder::DataStream::getPtr().
VideoDesc avtranscoder::OutputVideo::getVideoDesc () inline
Definition at line 34 of file OutputVideo.hpp.
Referenced by main(), and avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::OutputVideo::setProfile (const Profile::ProfileDesc & desc, const avtranscoder::VideoFrameDesc & frameDesc)
Definition at line 176 of file OutputVideo.cpp.
References avtranscoder::OutputEssence::_codedDesc, avtranscoder::Profile::avProfileCodec, avtranscoder::Profile::avProfileFrameRate, avtranscoder::Profile::avProfileIdentificator, avtranscoder::Profile::avProfileIdentificatorHuman, avtranscoder::Profile::avProfilePixelFormat, avtranscoder::Profile::avProfileType, avtranscoder::CodedDesc::getCodecContext(), avtranscoder::ParamSet::set(), avtranscoder::CodedDesc::setCodec(), and setup().
Referenced by main(), avtranscoder::StreamTranscoder::StreamTranscoder(), and transcodeVideo().
void avtranscoder::OutputVideo::setup () virtual
Setup the encoder.
Implements avtranscoder::OutputEssence.
Definition at line 24 of file OutputVideo.cpp.
References avtranscoder::OutputEssence::_codedDesc, avtranscoder::CodedDesc::getCodec(), and avtranscoder::CodedDesc::getCodecContext().
Referenced by setProfile().
The documentation for this class was generated from the following files:
src/AvTranscoder/EssenceStream/OutputVideo.hpp
src/AvTranscoder/EssenceStream/OutputVideo.cpp