AvTranscoder: avtranscoder::VideoTransform Class Reference
avtranscoder::VideoTransform Class Reference
#include <VideoTransform.hpp>
Public Member Functions
VideoTransform ()
~VideoTransform ()
void convert (const Frame &srcFrame, Frame &dstFrame)
Private Member Functions
VideoTransform (const VideoTransform &videoTransform)
VideoTransform & operator= (const VideoTransform &videoTransform)
bool init (const Frame &srcFrame, const Frame &dstFrame)
Private Attributes
SwsContext * _imageConvertContext
std::vector< uint8_t * > _srcData
std::vector< uint8_t * > _dstData
std::vector< int > _srcLineSize
std::vector< int > _dstLineSize
bool _isInit
Detailed Description
Definition at line 15 of file VideoTransform.hpp.
Constructor & Destructor Documentation
avtranscoder::VideoTransform::VideoTransform (const VideoTransform & videoTransform) [private]
avtranscoder::VideoTransform::VideoTransform ()
Definition at line 25 of file VideoTransform.cpp.
avtranscoder::VideoTransform::~VideoTransform ()
Definition at line 35 of file VideoTransform.cpp.
References _imageConvertContext.
Member Function Documentation
void avtranscoder::VideoTransform::convert (const Frame & srcFrame, Frame & dstFrame) [virtual]
Implements avtranscoder::ITransform.
Definition at line 77 of file VideoTransform.cpp.
References _dstData, _dstLineSize, _imageConvertContext, _isInit, _srcData, _srcLineSize, AV_PIX_FMT_NONE, AVPixelFormat, avtranscoder::VideoFrame::desc(), avtranscoder::Frame::getData(), avtranscoder::VideoFrameDesc::getHeight(), avtranscoder::VideoFrameDesc::getPixelFormat(), avtranscoder::VideoFrameDesc::getWidth(), and init().
Referenced by avtranscoder::VideoGenerator::decodeNextFrame().
bool avtranscoder::VideoTransform::init (const Frame & srcFrame, const Frame & dstFrame) [private, virtual]
Implements avtranscoder::ITransform.
Definition at line 40 of file VideoTransform.cpp.
References _dstLineSize, _imageConvertContext, _srcLineSize, AVPixelFormat, avtranscoder::VideoFrame::desc(), avtranscoder::VideoFrameDesc::getHeight(), avtranscoder::VideoFrameDesc::getPixelFormat(), avtranscoder::VideoFrameDesc::getWidth(), and LOG_DEBUG.
Referenced by convert().
VideoTransform& avtranscoder::VideoTransform::operator= (const VideoTransform & videoTransform) [private]
Field Documentation
std::vector<uint8_t *> avtranscoder::VideoTransform::_dstData [private]
Definition at line 33 of file VideoTransform.hpp.
Referenced by convert().
std::vector<int> avtranscoder::VideoTransform::_dstLineSize [private]
Definition at line 35 of file VideoTransform.hpp.
Referenced by convert(), and init().
SwsContext* avtranscoder::VideoTransform::_imageConvertContext [private]
Definition at line 30 of file VideoTransform.hpp.
Referenced by convert(), init(), and ~VideoTransform().
bool avtranscoder::VideoTransform::_isInit [private]
Definition at line 37 of file VideoTransform.hpp.
Referenced by convert().
std::vector<uint8_t *> avtranscoder::VideoTransform::_srcData [private]
Definition at line 32 of file VideoTransform.hpp.
Referenced by convert().
std::vector<int> avtranscoder::VideoTransform::_srcLineSize [private]
Definition at line 34 of file VideoTransform.hpp.
Referenced by convert(), and init().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/transform/VideoTransform.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/transform/VideoTransform.cpp