AvTranscoder: avtranscoder::AudioDecoder Class Reference
avtranscoder::AudioDecoder Class Reference
#include <AudioDecoder.hpp>
Public Member Functions
AudioDecoder (InputStream &inputStream)
~AudioDecoder ()
void setupDecoder (const ProfileLoader::Profile &profile=ProfileLoader::Profile())
Setup the decoder.
bool decodeNextFrame (Frame &frameBuffer)
Decode next frame.
bool decodeNextFrame (Frame &frameBuffer, const size_t subStreamIndex)
Decode substream of next frame.
void flushDecoder ()
Reset the internal decoder state / flush internal buffers.
Private Member Functions
bool decodeNextFrame ()
Private Attributes
InputStream * _inputStream
Stream from which we read next frames (no ownership, has link)
AVFrame * _frame
Libav object to store decoded data (has ownership)
bool _isSetup
Detailed Description
Definition at line 13 of file AudioDecoder.hpp.
Constructor & Destructor Documentation
avtranscoder::AudioDecoder::AudioDecoder (InputStream & inputStream)
Definition at line 20 of file AudioDecoder.cpp.
References _frame.
avtranscoder::AudioDecoder::~AudioDecoder ()
Definition at line 36 of file AudioDecoder.cpp.
References _frame.
Member Function Documentation
bool avtranscoder::AudioDecoder::decodeNextFrame (Frame & frameBuffer) [virtual]
Decode next frame.
Parameters:
frameBuffer,: the frame decoded
Returns:
status of decoding
Implements avtranscoder::IDecoder.
Definition at line 100 of file AudioDecoder.cpp.
References _frame, _inputStream, decodeNextFrame(), avtranscoder::InputStream::getAudioCodec(), avtranscoder::ICodec::getAVCodecContext(), avtranscoder::Frame::getData(), avtranscoder::Frame::resize(), and avtranscoder::AudioFrame::setNbSamples().
bool avtranscoder::AudioDecoder::decodeNextFrame (Frame & frameBuffer, const size_t subStreamIndex) [virtual]
Decode substream of next frame.
Parameters:
frameBuffer,: the frame decoded
subStreamIndex,: index of substream to extract
Returns:
status of decoding
Implements avtranscoder::IDecoder.
Definition at line 124 of file AudioDecoder.cpp.
References _frame, _inputStream, decodeNextFrame(), avtranscoder::InputStream::getAudioCodec(), avtranscoder::ICodec::getAVCodecContext(), avtranscoder::Frame::getData(), avtranscoder::Frame::resize(), and avtranscoder::AudioFrame::setNbSamples().
bool avtranscoder::AudioDecoder::decodeNextFrame () [private]
Definition at line 167 of file AudioDecoder.cpp.
References _frame, _inputStream, _isSetup, avtranscoder::Frame::clear(), avtranscoder::InputStream::getAudioCodec(), avtranscoder::ICodec::getAVCodecContext(), avtranscoder::Frame::getAVPacket(), avtranscoder::getDescriptionFromErrorCode(), avtranscoder::InputStream::readNextPacket(), and setupDecoder().
Referenced by decodeNextFrame().
void avtranscoder::AudioDecoder::flushDecoder () [virtual]
Reset the internal decoder state / flush internal buffers.
Note:
Should be called when seeking or when switching to a different stream.
Not sense for generators.
Reimplemented from avtranscoder::IDecoder.
Definition at line 193 of file AudioDecoder.cpp.
References _inputStream, avtranscoder::InputStream::getAudioCodec(), and avtranscoder::ICodec::getAVCodecContext().
void avtranscoder::AudioDecoder::setupDecoder (const ProfileLoader::Profile & profile = ProfileLoader::Profile()) [virtual]
Setup the decoder.
Parameters:
profile,: set decoder parameters from the given profile
Note:
Open the decoder.
Reimplemented from avtranscoder::IDecoder.
Definition at line 54 of file AudioDecoder.cpp.
References _inputStream, _isSetup, avtranscoder::constants::avProfileIdentificator, avtranscoder::constants::avProfileIdentificatorHuman, avtranscoder::constants::avProfileThreads, avtranscoder::constants::avProfileType, avtranscoder::ProfileLoader::checkAudioProfile(), avtranscoder::InputStream::getAudioCodec(), avtranscoder::ICodec::getAVCodecContext(), avtranscoder::ICodec::getOption(), LOG_ERROR, LOG_INFO, LOG_WARN, avtranscoder::ICodec::openCodec(), avtranscoder::Option::setInt(), and avtranscoder::Option::setString().
Referenced by decodeNextFrame(), and avtranscoder::StreamTranscoder::StreamTranscoder().
Field Documentation
AVFrame* avtranscoder::AudioDecoder::_frame [private]
Libav object to store decoded data (has ownership)
Definition at line 31 of file AudioDecoder.hpp.
Referenced by AudioDecoder(), decodeNextFrame(), and ~AudioDecoder().
InputStream* avtranscoder::AudioDecoder::_inputStream [private]
Stream from which we read next frames (no ownership, has link)
Definition at line 30 of file AudioDecoder.hpp.
Referenced by decodeNextFrame(), flushDecoder(), and setupDecoder().
bool avtranscoder::AudioDecoder::_isSetup [private]
Definition at line 33 of file AudioDecoder.hpp.
Referenced by decodeNextFrame(), and setupDecoder().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/decoder/AudioDecoder.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/decoder/AudioDecoder.cpp