AvTranscoder: AvReader Class Reference
AvReader Class Reference
#include <AvReader.hpp>
Public Member Functions
AvReader (const std::string &filename)
~AvReader ()
size_t getWidth ()
size_t getHeight ()
size_t getComponents ()
size_t getBitDepth ()
const char * readNextFrame ()
const char * readPrevFrame ()
const char * readFrameAt (const size_t frame)
void printMetadatas ()
Public Member Functions inherited from Reader
Reader ()
Private Attributes
avtranscoder::InputFile m_inputFile
avtranscoder::InputVideo * m_inputVideo
avtranscoder::VideoFrame * m_sourceImage
avtranscoder::VideoFrame * m_imageToDisplay
avtranscoder::Pixel pixel
avtranscoder::VideoFrameDesc VideoFrameDescToDisplay
avtranscoder::VideoEssenceTransform m_videoEssenceTransform
size_t m_videoStream
Additional Inherited Members
Protected Attributes inherited from Reader
size_t currentFrame
Detailed Description
Definition at line 12 of file AvReader.hpp.
Constructor & Destructor Documentation
AvReader::AvReader (const std::string & filename) inline
Definition at line 15 of file AvReader.hpp.
References avtranscoder::InputFile::analyse(), avtranscoder::VideoFrame::desc(), avtranscoder::eComponentRgb, avtranscoder::eSubsamplingNone, avtranscoder::Pixel::findPixel(), getBitDepth(), getComponents(), avtranscoder::VideoFrameDesc::getDar(), avtranscoder::VideoFrameDesc::getHeight(), avtranscoder::InputFile::getProperties(), avtranscoder::InputFile::getStream(), avtranscoder::AvInputStream::getVideoDesc(), avtranscoder::VideoDesc::getVideoFrameDesc(), avtranscoder::VideoFrameDesc::getWidth(), m_imageToDisplay, m_inputFile, m_inputVideo, m_sourceImage, m_videoStream, pixel, avtranscoder::InputFile::readStream(), avtranscoder::Pixel::setAlpha(), avtranscoder::Pixel::setBitsPerPixel(), avtranscoder::Pixel::setColorComponents(), avtranscoder::Pixel::setComponents(), avtranscoder::VideoFrameDesc::setDar(), avtranscoder::VideoFrameDesc::setHeight(), avtranscoder::VideoFrameDesc::setPixel(), avtranscoder::Pixel::setPlanar(), avtranscoder::Pixel::setSubsampling(), avtranscoder::InputVideo::setup(), avtranscoder::VideoFrameDesc::setWidth(), VideoFrameDescToDisplay, and avtranscoder::Properties::videoStreams.
AvReader::~AvReader () inline
Definition at line 50 of file AvReader.hpp.
References m_imageToDisplay, m_inputVideo, and m_sourceImage.
Member Function Documentation
size_t AvReader::getBitDepth () inline virtual
Implements Reader.
Definition at line 72 of file AvReader.hpp.
Referenced by AvReader().
size_t AvReader::getComponents () inline virtual
Implements Reader.
Definition at line 67 of file AvReader.hpp.
References avtranscoder::InputFile::getProperties(), m_inputFile, and avtranscoder::Properties::videoStreams.
Referenced by AvReader().
size_t AvReader::getHeight () inline virtual
Implements Reader.
Definition at line 62 of file AvReader.hpp.
References avtranscoder::InputFile::getProperties(), m_inputFile, and avtranscoder::Properties::videoStreams.
size_t AvReader::getWidth () inline virtual
Implements Reader.
Definition at line 57 of file AvReader.hpp.
References avtranscoder::InputFile::getProperties(), m_inputFile, and avtranscoder::Properties::videoStreams.
void AvReader::printMetadatas () inline virtual
Implements Reader.
Definition at line 99 of file AvReader.hpp.
References m_inputFile.
const char* AvReader::readFrameAt (const size_t frame) inline virtual
Implements Reader.
Definition at line 91 of file AvReader.hpp.
References avtranscoder::InputVideo::flushDecoder(), m_inputFile, m_inputVideo, readNextFrame(), and avtranscoder::InputFile::seekAtFrame().
Referenced by readPrevFrame().
const char* AvReader::readNextFrame () inline virtual
Implements Reader.
Definition at line 77 of file AvReader.hpp.
References avtranscoder::VideoEssenceTransform::convert(), Reader::currentFrame, avtranscoder::Frame::getPtr(), m_imageToDisplay, m_inputVideo, m_sourceImage, m_videoEssenceTransform, and avtranscoder::InputVideo::readNextFrame().
Referenced by readFrameAt().
const char* AvReader::readPrevFrame () inline virtual
Implements Reader.
Definition at line 85 of file AvReader.hpp.
References Reader::currentFrame, and readFrameAt().
Field Documentation
avtranscoder::VideoFrame* AvReader::m_imageToDisplay private
Definition at line 110 of file AvReader.hpp.
Referenced by AvReader(), readNextFrame(), and ~AvReader().
avtranscoder::InputFile AvReader::m_inputFile private
Definition at line 105 of file AvReader.hpp.
Referenced by AvReader(), getComponents(), getHeight(), getWidth(), printMetadatas(), and readFrameAt().
avtranscoder::InputVideo* AvReader::m_inputVideo private
Definition at line 107 of file AvReader.hpp.
Referenced by AvReader(), readFrameAt(), readNextFrame(), and ~AvReader().
avtranscoder::VideoFrame* AvReader::m_sourceImage private
Definition at line 109 of file AvReader.hpp.
Referenced by AvReader(), readNextFrame(), and ~AvReader().
avtranscoder::VideoEssenceTransform AvReader::m_videoEssenceTransform private
Definition at line 115 of file AvReader.hpp.
Referenced by readNextFrame().
size_t AvReader::m_videoStream private
Definition at line 116 of file AvReader.hpp.
Referenced by AvReader().
avtranscoder::Pixel AvReader::pixel private
Definition at line 112 of file AvReader.hpp.
Referenced by AvReader().
avtranscoder::VideoFrameDesc AvReader::VideoFrameDescToDisplay private
Definition at line 113 of file AvReader.hpp.
Referenced by AvReader().
The documentation for this class was generated from the following file:
app/cpp/avplay/AvReader.hpp