AvTranscoder: avtranscoder::AvInputStream Class Reference
avtranscoder::AvInputStream Class Reference
#include <AvInputStream.hpp>
Public Member Functions
AvInputStream ()
AvInputStream (InputFile &inputFile, const size_t streamIndex)
~AvInputStream ()
AvInputStream (const AvInputStream &inputStream)
size_t getStreamIndex () const
bool readNextPacket (DataStream &data)
VideoDesc getVideoDesc () const
AudioDesc getAudioDesc () const
DataDesc getDataDesc () const
AVMediaType getStreamType () const
double getDuration () const
double getPacketDuration () const
void addPacket (AVPacket &packet)
void setBufferred (const bool bufferized)
bool getBufferred () const
void clearBuffering ()
Public Member Functions inherited from avtranscoder::InputStream
InputStream ()
virtual ~InputStream ()
Private Attributes
InputFile * _inputFile
std::vector< DataStream > _streamCache
VideoDesc _videoDesc
AudioDesc _audioDesc
int _packetDuration
size_t _streamIndex
bool _bufferized
Detailed Description
Definition at line 13 of file AvInputStream.hpp.
Constructor & Destructor Documentation
avtranscoder::AvInputStream::AvInputStream ()
Definition at line 20 of file AvInputStream.cpp.
avtranscoder::AvInputStream::AvInputStream (InputFile & inputFile, const size_t streamIndex)
Definition at line 29 of file AvInputStream.cpp.
References _inputFile, _streamIndex, and avtranscoder::InputFile::getFormatContext().
avtranscoder::AvInputStream::~AvInputStream ()
Definition at line 48 of file AvInputStream.cpp.
avtranscoder::AvInputStream::AvInputStream (const AvInputStream & inputStream) inline
Definition at line 21 of file AvInputStream.hpp.
Member Function Documentation
void avtranscoder::AvInputStream::addPacket (AVPacket & packet)
Definition at line 70 of file AvInputStream.cpp.
References _bufferized, _packetDuration, and _streamCache.
void avtranscoder::AvInputStream::clearBuffering () virtual
Implements avtranscoder::InputStream.
Definition at line 155 of file AvInputStream.cpp.
References _streamCache.
AudioDesc avtranscoder::AvInputStream::getAudioDesc () const virtual
Implements avtranscoder::InputStream.
Definition at line 116 of file AvInputStream.cpp.
References _inputFile, _streamIndex, avtranscoder::InputFile::getFormatContext(), and avtranscoder::AudioDesc::setAudioParameters().
Referenced by avtranscoder::InputAudio::setup().
bool avtranscoder::AvInputStream::getBufferred () const inline
Definition at line 46 of file AvInputStream.hpp.
DataDesc avtranscoder::AvInputStream::getDataDesc () const virtual
Implements avtranscoder::InputStream.
Definition at line 134 of file AvInputStream.cpp.
double avtranscoder::AvInputStream::getDuration () const virtual
Implements avtranscoder::InputStream.
Definition at line 145 of file AvInputStream.cpp.
References _inputFile, and avtranscoder::InputFile::getFormatContext().
double avtranscoder::AvInputStream::getPacketDuration () const virtual
Implements avtranscoder::InputStream.
Definition at line 150 of file AvInputStream.cpp.
References _inputFile, _packetDuration, _streamIndex, and avtranscoder::InputFile::getFormatContext().
size_t avtranscoder::AvInputStream::getStreamIndex () const inline virtual
Implements avtranscoder::InputStream.
Definition at line 29 of file AvInputStream.hpp.
AVMediaType avtranscoder::AvInputStream::getStreamType () const virtual
Implements avtranscoder::InputStream.
Definition at line 140 of file AvInputStream.cpp.
References _inputFile, _streamIndex, and avtranscoder::InputFile::getStreamType().
VideoDesc avtranscoder::AvInputStream::getVideoDesc () const virtual
Implements avtranscoder::InputStream.
Definition at line 97 of file AvInputStream.cpp.
References _inputFile, _streamIndex, avtranscoder::InputFile::getFormatContext(), avtranscoder::VideoDesc::setImageParameters(), and avtranscoder::VideoDesc::setTimeBase().
Referenced by AvReader::AvReader(), avtranscoder::InputVideo::setup(), and transcodeVideo().
bool avtranscoder::AvInputStream::readNextPacket (DataStream & data) virtual
Implements avtranscoder::InputStream.
Definition at line 52 of file AvInputStream.cpp.
References _bufferized, _inputFile, _streamCache, _streamIndex, avtranscoder::DataStream::getBuffer(), and avtranscoder::InputFile::readNextPacket().
Referenced by avtranscoder::InputAudio::getNextFrame(), and avtranscoder::InputVideo::readNextFrame().
void avtranscoder::AvInputStream::setBufferred (const bool bufferized) inline virtual
Implements avtranscoder::InputStream.
Definition at line 45 of file AvInputStream.hpp.
Field Documentation
AudioDesc avtranscoder::AvInputStream::_audioDesc private
Definition at line 55 of file AvInputStream.hpp.
bool avtranscoder::AvInputStream::_bufferized private
Definition at line 59 of file AvInputStream.hpp.
Referenced by addPacket(), and readNextPacket().
InputFile* avtranscoder::AvInputStream::_inputFile private
Definition at line 51 of file AvInputStream.hpp.
Referenced by AvInputStream(), getAudioDesc(), getDuration(), getPacketDuration(), getStreamType(), getVideoDesc(), and readNextPacket().
int avtranscoder::AvInputStream::_packetDuration private
Definition at line 57 of file AvInputStream.hpp.
Referenced by addPacket(), and getPacketDuration().
std::vector<DataStream> avtranscoder::AvInputStream::_streamCache private
Definition at line 52 of file AvInputStream.hpp.
Referenced by addPacket(), clearBuffering(), and readNextPacket().
size_t avtranscoder::AvInputStream::_streamIndex private
Definition at line 58 of file AvInputStream.hpp.
Referenced by AvInputStream(), getAudioDesc(), getPacketDuration(), getStreamType(), getVideoDesc(), and readNextPacket().
VideoDesc avtranscoder::AvInputStream::_videoDesc private
Definition at line 54 of file AvInputStream.hpp.
The documentation for this class was generated from the following files:
src/AvTranscoder/CodedStream/AvInputStream.hpp
src/AvTranscoder/CodedStream/AvInputStream.cpp