AvTranscoder: avtranscoder::AudioFrameDesc Class Reference
avtranscoder::AudioFrameDesc Class Reference
Description of a number of samples, which corresponds to one video frame.
#include <AudioFrame.hpp>
Public Member Functions
AudioFrameDesc (const size_t sampleRate=0, const size_t channels=0, const AVSampleFormat sampleFormat=AV_SAMPLE_FMT_NONE)
AudioFrameDesc (const size_t sampleRate, const size_t channels, const std::string &sampleFormat)
size_t getSampleRate () const
size_t getChannels () const
AVSampleFormat getSampleFormat () const
std::string getSampleFormatName () const
double getFps () const
size_t getDataSize () const
void setSampleRate (const size_t sampleRate)
void setChannels (const size_t channels)
void setSampleFormat (const std::string &sampleFormatName)
void setSampleFormat (const AVSampleFormat sampleFormat)
void setFps (const double fps)
void setParameters (const ProfileLoader::Profile &profile)
Private Attributes
size_t _sampleRate
size_t _channels
AVSampleFormat _sampleFormat
double _fps
Detailed Description
Description of a number of samples, which corresponds to one video frame.
Definition at line 15 of file AudioFrame.hpp.
Constructor & Destructor Documentation
avtranscoder::AudioFrameDesc::AudioFrameDesc (const size_t sampleRate = 0, const size_t channels = 0, const AVSampleFormat sampleFormat = AV_SAMPLE_FMT_NONE)
Definition at line 9 of file AudioFrame.cpp.
avtranscoder::AudioFrameDesc::AudioFrameDesc (const size_t sampleRate, const size_t channels, const std::string & sampleFormat)
Definition at line 16 of file AudioFrame.cpp.
Member Function Documentation
size_t avtranscoder::AudioFrameDesc::getChannels () const [inline]
Definition at line 23 of file AudioFrame.hpp.
Referenced by avtranscoder::AudioTransform::init(), avtranscoder::AudioCodec::setAudioParameters(), and avtranscoder::AudioTransform::updateOutputFrame().
size_t avtranscoder::AudioFrameDesc::getDataSize () const
Definition at line 29 of file AudioFrame.cpp.
References _channels, _fps, _sampleFormat, and _sampleRate.
Referenced by avtranscoder::AudioGenerator::decodeNextFrame().
double avtranscoder::AudioFrameDesc::getFps () const [inline]
Definition at line 26 of file AudioFrame.hpp.
Referenced by avtranscoder::AudioGenerator::decodeNextFrame().
AVSampleFormat avtranscoder::AudioFrameDesc::getSampleFormat () const [inline]
Definition at line 24 of file AudioFrame.hpp.
Referenced by avtranscoder::AudioTransform::init(), avtranscoder::AudioCodec::setAudioParameters(), and avtranscoder::AudioTransform::updateOutputFrame().
std::string avtranscoder::AudioFrameDesc::getSampleFormatName () const
Definition at line 23 of file AudioFrame.cpp.
References _sampleFormat.
size_t avtranscoder::AudioFrameDesc::getSampleRate () const [inline]
Definition at line 22 of file AudioFrame.hpp.
Referenced by avtranscoder::AudioGenerator::decodeNextFrame(), avtranscoder::AudioTransform::init(), and avtranscoder::AudioCodec::setAudioParameters().
void avtranscoder::AudioFrameDesc::setChannels (const size_t channels) [inline]
Definition at line 31 of file AudioFrame.hpp.
Referenced by setParameters(), and avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::AudioFrameDesc::setFps (const double fps) [inline]
Definition at line 34 of file AudioFrame.hpp.
Referenced by avtranscoder::AudioGenerator::setAudioFrameDesc(), and setParameters().
void avtranscoder::AudioFrameDesc::setParameters (const ProfileLoader::Profile & profile)
Definition at line 46 of file AudioFrame.cpp.
References avtranscoder::constants::avProfileChannel, avtranscoder::constants::avProfileFrameRate, avtranscoder::constants::avProfileSampleFormat, avtranscoder::constants::avProfileSampleRate, setChannels(), setFps(), setSampleFormat(), and setSampleRate().
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::AudioFrameDesc::setSampleFormat (const std::string & sampleFormatName)
Definition at line 41 of file AudioFrame.cpp.
References _sampleFormat.
Referenced by setParameters().
void avtranscoder::AudioFrameDesc::setSampleFormat (const AVSampleFormat sampleFormat) [inline]
Definition at line 33 of file AudioFrame.hpp.
void avtranscoder::AudioFrameDesc::setSampleRate (const size_t sampleRate) [inline]
Definition at line 30 of file AudioFrame.hpp.
Referenced by setParameters().
Field Documentation
size_t avtranscoder::AudioFrameDesc::_channels [private]
Definition at line 40 of file AudioFrame.hpp.
Referenced by getDataSize().
double avtranscoder::AudioFrameDesc::_fps [private]
Definition at line 42 of file AudioFrame.hpp.
Referenced by getDataSize().
AVSampleFormat avtranscoder::AudioFrameDesc::_sampleFormat [private]
Definition at line 41 of file AudioFrame.hpp.
Referenced by getDataSize(), getSampleFormatName(), and setSampleFormat().
size_t avtranscoder::AudioFrameDesc::_sampleRate [private]
Definition at line 39 of file AudioFrame.hpp.
Referenced by getDataSize().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/frame/AudioFrame.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/frame/AudioFrame.cpp