AvTranscoder: app/cpp/genericProcessor/genericProcessor.cpp File Reference
genericProcessor.cpp File Reference
#include <AvTranscoder/Transcoder/Transcoder.hpp>
#include <iostream>
#include <iomanip>
#include <vector>
#include <fstream>
#include <sstream>
#include <cstdlib>
Functions
void parseConfigFile (const std::string &configFilename, avtranscoder::Transcoder &transcoder, avtranscoder::Profile &profile)
int main (int argc, char **argv)
Variables
static const size_t dummyWidth = 1920
static const size_t dummyHeight = 1080
static const std::string dummyPixelFormat = "yuv420p"
static const std::string dummyVideoCodec = "mpeg2video"
static const std::string dummyAudioCodec = "pcm_s16le"
bool verbose = true
Function Documentation
int main (int argc, char ** argv)
Definition at line 84 of file genericProcessor.cpp.
References avtranscoder::eProcessMethodInfinity, avtranscoder::Transcoder::init(), parseConfigFile(), avtranscoder::Transcoder::process(), avtranscoder::Transcoder::setProcessMethod(), avtranscoder::Transcoder::setVerbose(), and verbose.
void parseConfigFile (const std::string & configFilename, avtranscoder::Transcoder & transcoder, avtranscoder::Profile & profile)
Definition at line 20 of file genericProcessor.cpp.
References avtranscoder::Transcoder::add(), dummyHeight, dummyPixelFormat, dummyVideoCodec, dummyWidth, avtranscoder::separator, avtranscoder::VideoFrameDesc::setDar(), avtranscoder::VideoFrameDesc::setHeight(), avtranscoder::VideoDesc::setImageParameters(), avtranscoder::VideoFrameDesc::setPixel(), avtranscoder::VideoFrameDesc::setWidth(), and verbose.
Referenced by main().
Variable Documentation
const std::string dummyAudioCodec = "pcm_s16le" static
Definition at line 15 of file genericProcessor.cpp.
const size_t dummyHeight = 1080 static
Definition at line 12 of file genericProcessor.cpp.
Referenced by parseConfigFile().
const std::string dummyPixelFormat = "yuv420p" static
Definition at line 13 of file genericProcessor.cpp.
Referenced by parseConfigFile().
const std::string dummyVideoCodec = "mpeg2video" static
Definition at line 14 of file genericProcessor.cpp.
Referenced by parseConfigFile().
const size_t dummyWidth = 1920 static
Definition at line 11 of file genericProcessor.cpp.
Referenced by parseConfigFile().
bool verbose = true
Definition at line 18 of file genericProcessor.cpp.
Referenced by main(), parseConfigFile(), avtranscoder::VideoEssenceTransform::setVerbose(), avtranscoder::StreamTranscoder::setVerbose(), avtranscoder::OutputFile::setVerbose(), and avtranscoder::Transcoder::setVerbose().