AvTranscoder: avtranscoder::VideoEncoder Class Reference
avtranscoder::VideoEncoder Class Reference
#include <VideoEncoder.hpp>
Public Member Functions
VideoEncoder (const std::string &videoCodecName)
~VideoEncoder ()
void setupVideoEncoder (const VideoFrameDesc &frameDesc, const ProfileLoader::Profile &profile=ProfileLoader::Profile())
void setupEncoder (const ProfileLoader::Profile &profile=ProfileLoader::Profile())
Setup the encoder.
bool encodeFrame (const Frame &sourceFrame, Frame &codedFrame)
Encode a new frame, and get coded frame.
bool encodeFrame (Frame &codedFrame)
Get delayed encoded frames.
ICodec & getCodec ()
Get codec used for encoding.
VideoCodec & getVideoCodec ()
Private Attributes
VideoCodec _codec
AVFrame * _frame
Contains the encoded data to pass to the Frame when encodeFrame.
Detailed Description
Definition at line 11 of file VideoEncoder.hpp.
Constructor & Destructor Documentation
avtranscoder::VideoEncoder::VideoEncoder (const std::string & videoCodecName)
Definition at line 15 of file VideoEncoder.cpp.
References _frame.
avtranscoder::VideoEncoder::~VideoEncoder ()
Definition at line 26 of file VideoEncoder.cpp.
References _frame.
Member Function Documentation
bool avtranscoder::VideoEncoder::encodeFrame (const Frame & sourceFrame, Frame & codedFrame) [virtual]
Encode a new frame, and get coded frame.
Parameters:
sourceFrame frame need to be encoded
codedFrame data of the coded frame if present (first frames can be delayed)
Returns:
status of encoding
Implements avtranscoder::IEncoder.
Definition at line 126 of file VideoEncoder.cpp.
References _codec, _frame, avtranscoder::ICodec::getAVCodecContext(), avtranscoder::Frame::getAVPacket(), avtranscoder::Frame::getData(), and avtranscoder::getDescriptionFromErrorCode().
bool avtranscoder::VideoEncoder::encodeFrame (Frame & codedFrame) [virtual]
Get delayed encoded frames.
Parameters:
codedFrame data of the coded frame if present (first frames can be delayed)
Returns:
status of encoding
Implements avtranscoder::IEncoder.
Definition at line 185 of file VideoEncoder.cpp.
References _codec, avtranscoder::ICodec::getAVCodecContext(), avtranscoder::Frame::getAVPacket(), and avtranscoder::getDescriptionFromErrorCode().
ICodec& avtranscoder::VideoEncoder::getCodec () [inline, virtual]
Get codec used for encoding.
Returns:
a reference to the codec
Implements avtranscoder::IEncoder.
Definition at line 23 of file VideoEncoder.hpp.
VideoCodec& avtranscoder::VideoEncoder::getVideoCodec () [inline]
Definition at line 24 of file VideoEncoder.hpp.
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::VideoEncoder::setupEncoder (const ProfileLoader::Profile & profile = ProfileLoader::Profile()) [virtual]
Setup the encoder.
Parameters:
profile,: set encoder parameters from the given profile
Note:
Open the encoder.
Implements avtranscoder::IEncoder.
Definition at line 50 of file VideoEncoder.cpp.
References _codec, avtranscoder::constants::avProfileCodec, avtranscoder::constants::avProfileFrameRate, avtranscoder::constants::avProfileHeight, avtranscoder::constants::avProfileIdentificator, avtranscoder::constants::avProfileIdentificatorHuman, avtranscoder::constants::avProfilePixelFormat, avtranscoder::constants::avProfileProcessStat, avtranscoder::constants::avProfileThreads, avtranscoder::constants::avProfileType, avtranscoder::constants::avProfileWidth, avtranscoder::ProfileLoader::checkVideoProfile(), avtranscoder::ICodec::getAVCodecContext(), avtranscoder::ICodec::getOption(), LOG_ERROR, LOG_INFO, LOG_WARN, avtranscoder::ICodec::openCodec(), avtranscoder::Option::setInt(), and avtranscoder::Option::setString().
Referenced by setupVideoEncoder().
void avtranscoder::VideoEncoder::setupVideoEncoder (const VideoFrameDesc & frameDesc, const ProfileLoader::Profile & profile = ProfileLoader::Profile())
Definition at line 39 of file VideoEncoder.cpp.
References _codec, LOG_INFO, avtranscoder::VideoCodec::setImageParameters(), and setupEncoder().
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
Field Documentation
VideoCodec avtranscoder::VideoEncoder::_codec [private]
Definition at line 27 of file VideoEncoder.hpp.
Referenced by encodeFrame(), setupEncoder(), and setupVideoEncoder().
AVFrame* avtranscoder::VideoEncoder::_frame [private]
Contains the encoded data to pass to the Frame when encodeFrame.
Definition at line 28 of file VideoEncoder.hpp.
Referenced by encodeFrame(), VideoEncoder(), and ~VideoEncoder().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/encoder/VideoEncoder.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/encoder/VideoEncoder.cpp