AvTranscoder: avtranscoder::InputStream Class Reference
avtranscoder::InputStream Class Reference
#include <InputStream.hpp>
Public Member Functions
InputStream (InputFile &inputFile, const size_t streamIndex)
~InputStream ()
bool readNextPacket (CodedData &data)
Read the next packet of the stream.
size_t getStreamIndex () const
float getDuration () const
Get duration of the stream, in seconds.
AVMediaType getStreamType () const
VideoCodec & getVideoCodec ()
AudioCodec & getAudioCodec ()
DataCodec & getDataCodec ()
void activate (const bool activate=true)
Functions about buffering.
bool isActivated () const
void addPacket (const AVPacket &packet)
void clearBuffering ()
Private Member Functions
InputStream (const InputStream &inputStream)
InputStream & operator= (const InputStream &inputStream)
Private Attributes
InputFile * _inputFile
Has link (no ownership)
ICodec * _codec
Has ownership.
std::queue< CodedData > _streamCache
Cache of packet data already read and corresponding to this stream.
size_t _streamIndex
Index of the stream in the input file.
bool _isActivated
If the stream is activated, data read from it will be buffered.
Detailed Description
Definition at line 15 of file InputStream.hpp.
Constructor & Destructor Documentation
avtranscoder::InputStream::InputStream (const InputStream & inputStream) [private]
avtranscoder::InputStream::InputStream (InputFile & inputFile, const size_t streamIndex)
Definition at line 16 of file InputStream.cpp.
References _codec, _inputFile, _streamIndex, avtranscoder::eCodecTypeDecoder, avtranscoder::FormatContext::getAVStream(), and avtranscoder::InputFile::getFormatContext().
avtranscoder::InputStream::~InputStream ()
Definition at line 48 of file InputStream.cpp.
References _codec.
Member Function Documentation
void avtranscoder::InputStream::activate (const bool activate = true) [inline, virtual]
Functions about buffering.
See also:
IInputStream methods
Implements avtranscoder::IInputStream.
Definition at line 41 of file InputStream.hpp.
References activate().
Referenced by activate(), and avtranscoder::InputFile::activateStream().
void avtranscoder::InputStream::addPacket (const AVPacket & packet)
Definition at line 121 of file InputStream.cpp.
References _isActivated, _streamCache, _streamIndex, and LOG_DEBUG.
void avtranscoder::InputStream::clearBuffering () [virtual]
Implements avtranscoder::IInputStream.
Definition at line 135 of file InputStream.cpp.
References _streamCache.
AudioCodec & avtranscoder::InputStream::getAudioCodec () [virtual]
Implements avtranscoder::IInputStream.
Definition at line 87 of file InputStream.cpp.
References _codec, and getStreamType().
Referenced by avtranscoder::AudioDecoder::decodeNextFrame(), avtranscoder::AudioDecoder::flushDecoder(), avtranscoder::AudioReader::init(), and avtranscoder::AudioDecoder::setupDecoder().
DataCodec & avtranscoder::InputStream::getDataCodec () [virtual]
Implements avtranscoder::IInputStream.
Definition at line 99 of file InputStream.cpp.
References _codec, and getStreamType().
float avtranscoder::InputStream::getDuration () const [virtual]
Get duration of the stream, in seconds.
Implements avtranscoder::IInputStream.
Definition at line 116 of file InputStream.cpp.
References _inputFile, _streamIndex, avtranscoder::StreamProperties::getDuration(), avtranscoder::InputFile::getProperties(), and avtranscoder::FileProperties::getStreamPropertiesWithIndex().
size_t avtranscoder::InputStream::getStreamIndex () const [inline, virtual]
Implements avtranscoder::IInputStream.
Definition at line 27 of file InputStream.hpp.
AVMediaType avtranscoder::InputStream::getStreamType () const [virtual]
Implements avtranscoder::IInputStream.
Definition at line 111 of file InputStream.cpp.
References _inputFile, _streamIndex, avtranscoder::FormatContext::getAVStream(), and avtranscoder::InputFile::getFormatContext().
Referenced by getAudioCodec(), getDataCodec(), avtranscoder::Transcoder::getProfileFromFile(), and getVideoCodec().
VideoCodec & avtranscoder::InputStream::getVideoCodec () [virtual]
Return the codec informations of the stream
Exceptions:
Raise a runtime error if the stream is not of the corresponding type
Implements avtranscoder::IInputStream.
Definition at line 75 of file InputStream.cpp.
References _codec, and getStreamType().
Referenced by avtranscoder::VideoDecoder::decodeNextFrame(), avtranscoder::VideoDecoder::flushDecoder(), avtranscoder::VideoReader::init(), and avtranscoder::VideoDecoder::setupDecoder().
bool avtranscoder::InputStream::isActivated () const [inline, virtual]
Implements avtranscoder::IInputStream.
Definition at line 42 of file InputStream.hpp.
InputStream& avtranscoder::InputStream::operator= (const InputStream & inputStream) [private]
bool avtranscoder::InputStream::readNextPacket (CodedData & data) [virtual]
Read the next packet of the stream.
Parameters:
data,: data of next packet read
Returns:
if next packet was read succefully
Implements avtranscoder::IInputStream.
Definition at line 53 of file InputStream.cpp.
References _inputFile, _isActivated, _streamCache, _streamIndex, avtranscoder::Frame::copyData(), LOG_DEBUG, and avtranscoder::InputFile::readNextPacket().
Referenced by avtranscoder::AudioDecoder::decodeNextFrame(), and avtranscoder::VideoDecoder::decodeNextFrame().
Field Documentation
ICodec* avtranscoder::InputStream::_codec [private]
Has ownership.
Definition at line 49 of file InputStream.hpp.
Referenced by getAudioCodec(), getDataCodec(), getVideoCodec(), InputStream(), and ~InputStream().
InputFile* avtranscoder::InputStream::_inputFile [private]
Has link (no ownership)
Definition at line 48 of file InputStream.hpp.
Referenced by getDuration(), getStreamType(), InputStream(), and readNextPacket().
bool avtranscoder::InputStream::_isActivated [private]
If the stream is activated, data read from it will be buffered.
Definition at line 54 of file InputStream.hpp.
Referenced by addPacket(), and readNextPacket().
std::queue<CodedData> avtranscoder::InputStream::_streamCache [private]
Cache of packet data already read and corresponding to this stream.
Definition at line 51 of file InputStream.hpp.
Referenced by addPacket(), clearBuffering(), and readNextPacket().
size_t avtranscoder::InputStream::_streamIndex [private]
Index of the stream in the input file.
Definition at line 53 of file InputStream.hpp.
Referenced by addPacket(), getDuration(), getStreamType(), InputStream(), and readNextPacket().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/stream/InputStream.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/stream/InputStream.cpp