AvTranscoder: avtranscoder::IOutputFile Class Reference
avtranscoder::IOutputFile Class Reference
IOutputfile is the interface to wrap and write medias. It can be overloaded to integrate custom wrapper.
#include <IOutputFile.hpp>
Public Member Functions
virtual ~IOutputFile ()
virtual IOutputStream & addVideoStream (const VideoCodec &videoCodec)
Add a video output stream.
virtual IOutputStream & addAudioStream (const AudioCodec &audioCodec)
Add an audio output stream.
virtual IOutputStream & addDataStream (const DataCodec &dataCodec)
Add a data output stream.
virtual bool beginWrap ()=0
Write the header of file (if necessary)
virtual
IOutputStream::EWrappingStatus wrap (const CodedData &data, const size_t streamIndex)=0
Wrap a packet of data in the output ressource.
virtual bool endWrap ()=0
Write the footer of file (if necessary)
virtual IOutputStream & getStream (const size_t streamIndex)=0
Get the output stream.
Detailed Description
IOutputfile is the interface to wrap and write medias. It can be overloaded to integrate custom wrapper.
Definition at line 22 of file IOutputFile.hpp.
Constructor & Destructor Documentation
virtual avtranscoder::IOutputFile::~IOutputFile () [inline, virtual]
Definition at line 25 of file IOutputFile.hpp.
Member Function Documentation
virtual IOutputStream& avtranscoder::IOutputFile::addAudioStream (const AudioCodec & audioCodec) [inline, virtual]
Add an audio output stream.
Note:
call setup() before adding any stream
Parameters:
audioCodec description of output stream
Reimplemented in avtranscoder::OutputFile.
Definition at line 42 of file IOutputFile.hpp.
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
virtual IOutputStream& avtranscoder::IOutputFile::addDataStream (const DataCodec & dataCodec) [inline, virtual]
Add a data output stream.
Note:
call setup() before adding any stream
Parameters:
dataCodec description of output stream
Reimplemented in avtranscoder::OutputFile.
Definition at line 52 of file IOutputFile.hpp.
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
virtual IOutputStream& avtranscoder::IOutputFile::addVideoStream (const VideoCodec & videoCodec) [inline, virtual]
Add a video output stream.
Note:
call setup() before adding any stream
Parameters:
videoCodec description of output stream
Reimplemented in avtranscoder::OutputFile.
Definition at line 32 of file IOutputFile.hpp.
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
virtual bool avtranscoder::IOutputFile::beginWrap () [pure virtual]
Write the header of file (if necessary)
Implemented in avtranscoder::OutputFile.
Referenced by avtranscoder::Transcoder::process().
virtual bool avtranscoder::IOutputFile::endWrap () [pure virtual]
Write the footer of file (if necessary)
Implemented in avtranscoder::OutputFile.
Referenced by avtranscoder::Transcoder::process().
virtual IOutputStream& avtranscoder::IOutputFile::getStream (const size_t streamIndex) [pure virtual]
Get the output stream.
Parameters:
streamId select the output stream
Returns:
the output stream reference
Implemented in avtranscoder::OutputFile.
Referenced by avtranscoder::Transcoder::process().
virtual IOutputStream::EWrappingStatus avtranscoder::IOutputFile::wrap (const CodedData & data, const size_t streamIndex) [pure virtual]
Wrap a packet of data in the output ressource.
Parameters:
data coded packet information for the current stream
streamId refers to the stream in output ressource
Implemented in avtranscoder::OutputFile.
The documentation for this class was generated from the following file:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/file/IOutputFile.hpp