AvTranscoder: avtranscoder::AudioProperties Class Reference
avtranscoder::AudioProperties Class Reference
#include <AudioProperties.hpp>
Public Member Functions
AudioProperties (const FormatContext &formatContext, const size_t index)
std::string getCodecName () const
std::string getCodecLongName () const
std::string getSampleFormatName () const
std::string getSampleFormatLongName () const
std::string getChannelLayout () const
std::string getChannelName () const
std::string getChannelDescription () const
size_t getCodecId () const
size_t getSampleRate () const
size_t getChannels () const
size_t getBitRate () const
0 if unknown
size_t getNbSamples () const
size_t getTicksPerFrame () const
AVCodecContext & getAVCodecContext ()
PropertyVector getPropertiesAsVector () const
Same data with a specific order.
Private Member Functions
template<typename T >
void addProperty (PropertyVector &data, const std::string &key, T(AudioProperties::*getter)(void) const) const
Private Attributes
AVCodecContext * _codecContext
Has link (no ownership)
AVCodec * _codec
Has link (no ownership)
Detailed Description
Definition at line 11 of file AudioProperties.hpp.
Constructor & Destructor Documentation
avtranscoder::AudioProperties::AudioProperties (const FormatContext & formatContext, const size_t index)
Definition at line 16 of file AudioProperties.cpp.
References _codec, _codecContext, and avtranscoder::StreamProperties::_formatContext.
Member Function Documentation
template<typename T > void avtranscoder::AudioProperties::addProperty (PropertyVector & data, const std::string & key, T(AudioProperties::*)(void) const getter) const [inline, private]
Definition at line 41 of file AudioProperties.hpp.
References avtranscoder::detail::add().
Referenced by getPropertiesAsVector().
AVCodecContext& avtranscoder::AudioProperties::getAVCodecContext () [inline]
Definition at line 33 of file AudioProperties.hpp.
size_t avtranscoder::AudioProperties::getBitRate () const
0 if unknown
Definition at line 145 of file AudioProperties.cpp.
References _codecContext.
Referenced by getPropertiesAsVector().
std::string avtranscoder::AudioProperties::getChannelDescription () const
Definition at line 109 of file AudioProperties.cpp.
References _codecContext.
Referenced by getPropertiesAsVector().
std::string avtranscoder::AudioProperties::getChannelLayout () const
Definition at line 87 of file AudioProperties.cpp.
References _codecContext.
Referenced by getPropertiesAsVector().
std::string avtranscoder::AudioProperties::getChannelName () const
Definition at line 97 of file AudioProperties.cpp.
References _codecContext.
Referenced by getPropertiesAsVector().
size_t avtranscoder::AudioProperties::getChannels () const
Definition at line 138 of file AudioProperties.cpp.
References _codecContext.
Referenced by getNbSamples(), avtranscoder::Transcoder::getProfileFromFile(), and getPropertiesAsVector().
size_t avtranscoder::AudioProperties::getCodecId () const
Definition at line 124 of file AudioProperties.cpp.
References _codecContext.
Referenced by getPropertiesAsVector().
std::string avtranscoder::AudioProperties::getCodecLongName () const
Definition at line 33 of file AudioProperties.cpp.
References _codec.
Referenced by getPropertiesAsVector().
std::string avtranscoder::AudioProperties::getCodecName () const
Definition at line 26 of file AudioProperties.cpp.
References _codec.
Referenced by avtranscoder::Transcoder::getProfileFromFile(), and getPropertiesAsVector().
size_t avtranscoder::AudioProperties::getNbSamples () const
Definition at line 159 of file AudioProperties.cpp.
References avtranscoder::StreamProperties::_formatContext, avtranscoder::StreamProperties::_streamIndex, getChannels(), avtranscoder::StreamProperties::getDuration(), and getSampleRate().
Referenced by getPropertiesAsVector().
PropertyVector avtranscoder::AudioProperties::getPropertiesAsVector () const [virtual]
Same data with a specific order.
Reimplemented from avtranscoder::StreamProperties.
Definition at line 176 of file AudioProperties.cpp.
References addProperty(), getBitRate(), getChannelDescription(), getChannelLayout(), getChannelName(), getChannels(), getCodecId(), getCodecLongName(), getCodecName(), getNbSamples(), getSampleFormatLongName(), getSampleFormatName(), getSampleRate(), and getTicksPerFrame().
Referenced by avtranscoder::operator<<().
std::string avtranscoder::AudioProperties::getSampleFormatLongName () const
Definition at line 52 of file AudioProperties.cpp.
References _codecContext.
Referenced by getPropertiesAsVector().
std::string avtranscoder::AudioProperties::getSampleFormatName () const
Definition at line 40 of file AudioProperties.cpp.
References _codecContext.
Referenced by avtranscoder::Transcoder::getProfileFromFile(), and getPropertiesAsVector().
size_t avtranscoder::AudioProperties::getSampleRate () const
Definition at line 131 of file AudioProperties.cpp.
References _codecContext.
Referenced by getNbSamples(), avtranscoder::Transcoder::getProfileFromFile(), and getPropertiesAsVector().
size_t avtranscoder::AudioProperties::getTicksPerFrame () const
Definition at line 169 of file AudioProperties.cpp.
References _codecContext.
Referenced by getPropertiesAsVector().
Field Documentation
AVCodec* avtranscoder::AudioProperties::_codec [private]
Has link (no ownership)
Definition at line 56 of file AudioProperties.hpp.
Referenced by AudioProperties(), getCodecLongName(), and getCodecName().
AVCodecContext* avtranscoder::AudioProperties::_codecContext [private]
Has link (no ownership)
Definition at line 55 of file AudioProperties.hpp.
Referenced by AudioProperties(), getBitRate(), getChannelDescription(), getChannelLayout(), getChannelName(), getChannels(), getCodecId(), getSampleFormatLongName(), getSampleFormatName(), getSampleRate(), and getTicksPerFrame().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/mediaProperty/AudioProperties.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/mediaProperty/AudioProperties.cpp