AvTranscoder: avtranscoder::IOutputStream Class Reference
avtranscoder::IOutputStream Class Reference abstract
#include <IOutputStream.hpp>
Public Types
enum EWrappingStatus { eWrappingSuccess = 0, eWrappingWaitingForData, eWrappingError }
define wrapping result status
Public Member Functions
virtual ~IOutputStream ()
virtual size_t getStreamIndex () const =0
virtual float getStreamDuration () const =0
virtual size_t getNbFrames () const =0
virtual EWrappingStatus wrap (const CodedData &data)=0
Wrap a packet of data.
Detailed Description
Definition at line 11 of file IOutputStream.hpp.
Member Enumeration Documentation
enum avtranscoder::IOutputStream::EWrappingStatus
define wrapping result status
Enumerator
eWrappingSuccess
eWrappingWaitingForData
eWrappingError
Definition at line 17 of file IOutputStream.hpp.
Constructor & Destructor Documentation
virtual avtranscoder::IOutputStream::~IOutputStream () inline virtual
Definition at line 24 of file IOutputStream.hpp.
Member Function Documentation
virtual size_t avtranscoder::IOutputStream::getNbFrames () const pure virtual
Returns
The current number of frame of the stream.
Implemented in avtranscoder::OutputStream.
Referenced by avtranscoder::Transcoder::fillProcessStat().
virtual float avtranscoder::IOutputStream::getStreamDuration () const pure virtual
Returns
The current duration of the stream, in seconds.
Implemented in avtranscoder::OutputStream.
Referenced by avtranscoder::Transcoder::fillProcessStat(), avtranscoder::Transcoder::getCurrentOutputDuration(), and avtranscoder::StreamTranscoder::processFrame().
virtual size_t avtranscoder::IOutputStream::getStreamIndex () const pure virtual
Implemented in avtranscoder::OutputStream.
virtual EWrappingStatus avtranscoder::IOutputStream::wrap (const CodedData & data) pure virtual
Wrap a packet of data.
Returns
the wrapping status after wrapping
See also
EWrappingStatus
Implemented in avtranscoder::OutputStream.
Referenced by avtranscoder::StreamTranscoder::processRewrap(), and avtranscoder::StreamTranscoder::processTranscode().
The documentation for this class was generated from the following file:
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/stream/IOutputStream.hpp