AvTranscoder: app/cpp/optionChecker/optionChecker.cpp File Reference
optionChecker.cpp File Reference
#include <AvTranscoder/OptionLoader.hpp>
#include <AvTranscoder/Option.hpp>
#include <string>
#include <iostream>
#include <map>
#include <vector>
#include <utility>
Functions
void displayOptions (avtranscoder::OptionLoader::OptionArray &options)
void optionChecker (const std::string &inputfilename)
int main (int argc, char **argv)
Function Documentation
void displayOptions (avtranscoder::OptionLoader::OptionArray & options)
Definition at line 10 of file optionChecker.cpp.
References avtranscoder::TypeBool, avtranscoder::TypeChoice, avtranscoder::TypeDouble, avtranscoder::TypeGroup, avtranscoder::TypeInt, avtranscoder::TypeRatio, and avtranscoder::TypeString.
Referenced by optionChecker().
int main (int argc, char ** argv)
Definition at line 80 of file optionChecker.cpp.
References optionChecker().
void optionChecker (const std::string & inputfilename)
Definition at line 63 of file optionChecker.cpp.
References displayOptions(), and avtranscoder::OptionLoader::loadOutputFormatOptions().
Referenced by main().