AvTranscoder: avtranscoder::Logger Class Reference
avtranscoder::Logger Class Reference
Logger class which contains static functions to use ffmpeg/libav log system.
#include <log.hpp>
Static Public Member Functions
static void setLogLevel (const int level)
Set the log level of ffmpeg/libav.
static void log (const int level, const std::string &msg)
Log with the ffmpeg/libav log system.
static void logInFile ()
Log ffmpeg/libav and avtranscoder informations in a text file.
Detailed Description
Logger class which contains static functions to use ffmpeg/libav log system.
Definition at line 23 of file log.hpp.
Member Function Documentation
void avtranscoder::Logger::log (const int level, const std::string & msg) [static]
Log with the ffmpeg/libav log system.
Note:
you can use macro LOG_* to log at DEBUG/INFO/WARN/ERROR level
Parameters:
msg,: the message will be prefixed by '[avTranscoder - <level>]'
msg,: the message will be suffixed by '
'
Definition at line 29 of file log.cpp.
void avtranscoder::Logger::logInFile () [static]
Log ffmpeg/libav and avtranscoder informations in a text file.
Note:
log filename is avtranscoder.log
Definition at line 59 of file log.cpp.
References avtranscoder::callbackToWriteInFile(), and LOG_FILE.
Referenced by main().
void avtranscoder::Logger::setLogLevel (const int level) [static]
Set the log level of ffmpeg/libav.
Parameters:
level,: refer to define AV_LOG_xxx (from AV_LOG_QUIET to AV_LOG_DEBUG)
Note:
By default AV_LOG_INFO
See also:
SWIG interface avLogLevel.i
Definition at line 24 of file log.cpp.
Referenced by main().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/log.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/log.cpp