AvTranscoder: avtranscoder::InputVideo Class Reference
avtranscoder::InputVideo Class Reference
#include <InputVideo.hpp>
Public Member Functions
InputVideo (AvInputStream &inputStream)
~InputVideo ()
void setup ()
bool readNextFrame (Frame &frameBuffer)
bool readNextFrame (Frame &frameBuffer, const size_t subStreamIndex)
void flushDecoder ()
void setProfile (const Profile::ProfileDesc &desc)
Public Member Functions inherited from avtranscoder::InputEssence
InputEssence ()
virtual ~InputEssence ()
Private Attributes
AvInputStream * _inputStream
AVCodec * _codec
AVCodecContext * _codecContext
AVFrame * _frame
int _selectedStream
Detailed Description
Definition at line 17 of file InputVideo.hpp.
Constructor & Destructor Documentation
avtranscoder::InputVideo::InputVideo (AvInputStream & inputStream)
Definition at line 22 of file InputVideo.cpp.
avtranscoder::InputVideo::~InputVideo ()
Definition at line 32 of file InputVideo.cpp.
References _codecContext, and _frame.
Member Function Documentation
void avtranscoder::InputVideo::flushDecoder ()
Definition at line 145 of file InputVideo.cpp.
References _codecContext.
Referenced by AvReader::readFrameAt().
bool avtranscoder::InputVideo::readNextFrame (Frame & frameBuffer) virtual
Implements avtranscoder::InputEssence.
Definition at line 98 of file InputVideo.cpp.
References _codecContext, _frame, _inputStream, _selectedStream, AVPixelFormat, avtranscoder::Frame::getBuffer(), avtranscoder::DataStream::getPtr(), avtranscoder::DataStream::getSize(), and avtranscoder::AvInputStream::readNextPacket().
Referenced by AvReader::readNextFrame().
bool avtranscoder::InputVideo::readNextFrame (Frame & frameBuffer, const size_t subStreamIndex) virtual
Implements avtranscoder::InputEssence.
Definition at line 140 of file InputVideo.cpp.
void avtranscoder::InputVideo::setProfile (const Profile::ProfileDesc & desc)
Definition at line 150 of file InputVideo.cpp.
References _codecContext, avtranscoder::Profile::avProfileIdentificator, avtranscoder::Profile::avProfileIdentificatorHuman, avtranscoder::Profile::avProfileType, and avtranscoder::ParamSet::set().
void avtranscoder::InputVideo::setup () virtual
Implements avtranscoder::InputEssence.
Definition at line 55 of file InputVideo.cpp.
References _codec, _codecContext, _frame, _inputStream, avtranscoder::CodedDesc::getCodecId(), and avtranscoder::AvInputStream::getVideoDesc().
Referenced by AvReader::AvReader().
Field Documentation
AVCodec* avtranscoder::InputVideo::_codec private
Definition at line 34 of file InputVideo.hpp.
Referenced by setup().
AVCodecContext* avtranscoder::InputVideo::_codecContext private
Definition at line 35 of file InputVideo.hpp.
Referenced by flushDecoder(), readNextFrame(), setProfile(), setup(), and ~InputVideo().
AVFrame* avtranscoder::InputVideo::_frame private
Definition at line 36 of file InputVideo.hpp.
Referenced by readNextFrame(), setup(), and ~InputVideo().
AvInputStream* avtranscoder::InputVideo::_inputStream private
Definition at line 33 of file InputVideo.hpp.
Referenced by readNextFrame(), and setup().
int avtranscoder::InputVideo::_selectedStream private
Definition at line 38 of file InputVideo.hpp.
Referenced by readNextFrame().
The documentation for this class was generated from the following files:
src/AvTranscoder/EssenceStream/InputVideo.hpp
src/AvTranscoder/EssenceStream/InputVideo.cpp