AvTranscoder: avtranscoder::InputFile Class Reference
avtranscoder::InputFile Class Reference
#include <InputFile.hpp>
Public Member Functions
InputFile (const std::string &filename)
Open a media file.
virtual ~InputFile ()
void analyse (IProgress &progress, const EAnalyseLevel level=eAnalyseLevelFirstGop)
Run the analyse on the file after a setup. call this function before getProperties().
bool readNextPacket (CodedData &data, const size_t streamIndex)
Read the next packet of the specified stream.
bool seekAtFrame (const size_t frame, const int flag=AVSEEK_FLAG_ANY)
Seek at a specific frame / time (in seconds)
bool seekAtTime (const double time, const int flag=AVSEEK_FLAG_ANY)
void activateStream (const size_t streamIndex, const bool activate=true)
Activate the indicated stream.
const FileProperties & getProperties () const
Return media properties on the current InputFile.
InputStream & getStream (size_t index)
Get stream type: video, audio, subtitle, etc.
std::string getFilename () const
std::string getFormatName () const
A comma separated list of short names for the format, or empty if unknown.
std::string getFormatLongName () const
Descriptive name for the format, meant to be more human-readable than name, or empty if unknown.
std::string getFormatMimeType () const
Comma-separated list of mime types, or empty if unknown.
FormatContext & getFormatContext ()
virtual void setupUnwrapping (const ProfileLoader::Profile &profile)
Set the format of the input file.
Static Public Member Functions
static FileProperties analyseFile (const std::string &filename, IProgress &progress, const EAnalyseLevel level=eAnalyseLevelFirstGop)
Get media file properties using static method.
Protected Attributes
FormatContext _formatContext
FileProperties _properties
std::string _filename
std::vector< InputStream * > _inputStreams
Has ownership.
Private Member Functions
InputFile (const InputFile &inputFile)
InputFile & operator= (const InputFile &inputFile)
double getFps ()
Get Fps from first video stream.
Detailed Description
Definition at line 18 of file InputFile.hpp.
Constructor & Destructor Documentation
avtranscoder::InputFile::InputFile (const InputFile & inputFile) [private]
avtranscoder::InputFile::InputFile (const std::string & filename)
Open a media file.
Note:
The constructor also analyses header of input file
Parameters:
filename resource to access
Exceptions:
ios_base::failure launched if unable to open file
Definition at line 23 of file InputFile.cpp.
References _formatContext, _inputStreams, avtranscoder::FormatContext::findStreamInfo(), and avtranscoder::FormatContext::getNbStreams().
avtranscoder::InputFile::~InputFile () [virtual]
Definition at line 38 of file InputFile.cpp.
References _inputStreams.
Member Function Documentation
void avtranscoder::InputFile::activateStream (const size_t streamIndex, const bool activate = true)
Activate the indicated stream.
Note:
Activate a stream results in buffered its data when processing
Definition at line 100 of file InputFile.cpp.
References avtranscoder::InputStream::activate(), and getStream().
Referenced by avtranscoder::Transcoder::addInputFile(), avtranscoder::AudioReader::init(), and avtranscoder::VideoReader::init().
void avtranscoder::InputFile::analyse (IProgress & progress, const EAnalyseLevel level = eAnalyseLevelFirstGop)
Run the analyse on the file after a setup. call this function before getProperties().
Parameters:
progress callback to get analysis progression
level by default eAnalyseLevelFirstGop
Definition at line 46 of file InputFile.cpp.
References _properties, and avtranscoder::FileProperties::extractStreamProperties().
Referenced by analyseFile(), avtranscoder::AudioReader::init(), avtranscoder::VideoReader::init(), and main().
FileProperties avtranscoder::InputFile::analyseFile (const std::string & filename, IProgress & progress, const EAnalyseLevel level = eAnalyseLevelFirstGop) [static]
Get media file properties using static method.
Parameters:
filename input filename
progress callback to get analysis progression
Returns:
structure of media metadatas
Definition at line 51 of file InputFile.cpp.
References analyse(), and getProperties().
std::string avtranscoder::InputFile::getFilename () const [inline]
Definition at line 80 of file InputFile.hpp.
Referenced by getStream().
FormatContext& avtranscoder::InputFile::getFormatContext () [inline]
Definition at line 97 of file InputFile.hpp.
Referenced by avtranscoder::InputStream::getStreamType(), and avtranscoder::InputStream::InputStream().
std::string avtranscoder::InputFile::getFormatLongName () const
Descriptive name for the format, meant to be more human-readable than name, or empty if unknown.
Definition at line 132 of file InputFile.cpp.
References _filename, _formatContext, avtranscoder::FormatContext::getAVInputFormat(), and LOG_WARN.
std::string avtranscoder::InputFile::getFormatMimeType () const
Comma-separated list of mime types, or empty if unknown.
Definition at line 142 of file InputFile.cpp.
References _filename, _formatContext, avtranscoder::FormatContext::getAVInputFormat(), and LOG_WARN.
std::string avtranscoder::InputFile::getFormatName () const
A comma separated list of short names for the format, or empty if unknown.
Definition at line 122 of file InputFile.cpp.
References _filename, _formatContext, avtranscoder::FormatContext::getAVInputFormat(), and LOG_WARN.
double avtranscoder::InputFile::getFps () [private]
Get Fps from first video stream.
Note:
if there is no video stream, return 1.
Definition at line 157 of file InputFile.cpp.
References _properties, avtranscoder::FileProperties::getNbVideoStreams(), and avtranscoder::FileProperties::getVideoProperties().
Referenced by seekAtFrame().
const FileProperties& avtranscoder::InputFile::getProperties () const [inline]
Return media properties on the current InputFile.
Note:
require to launch analyse() before to fill the property struture
Returns:
structure of media metadatas
Definition at line 71 of file InputFile.hpp.
Referenced by analyseFile(), avtranscoder::InputStream::getDuration(), avtranscoder::Transcoder::getProfileFromFile(), avtranscoder::AudioReader::init(), avtranscoder::VideoReader::init(), and avtranscoder::operator<<().
InputStream & avtranscoder::InputFile::getStream (size_t index)
Get stream type: video, audio, subtitle, etc.
Parameters:
index stream index
Returns:
media stream type of specified index stream
Definition at line 105 of file InputFile.cpp.
References _inputStreams, and getFilename().
Referenced by activateStream(), avtranscoder::Transcoder::addRewrapStream(), avtranscoder::Transcoder::getProfileFromFile(), avtranscoder::AudioReader::init(), and avtranscoder::VideoReader::init().
InputFile& avtranscoder::InputFile::operator= (const InputFile & inputFile) [private]
bool avtranscoder::InputFile::readNextPacket (CodedData & data, const size_t streamIndex)
Read the next packet of the specified stream.
Parameters:
data,: data of next packet read
Returns:
if next packet was read succefully
Definition at line 58 of file InputFile.cpp.
References _filename, _formatContext, _inputStreams, avtranscoder::Frame::clear(), avtranscoder::FormatContext::getAVFormatContext(), avtranscoder::Frame::getAVPacket(), LOG_DEBUG, and LOG_INFO.
Referenced by avtranscoder::InputStream::readNextPacket().
bool avtranscoder::InputFile::seekAtFrame (const size_t frame, const int flag = AVSEEK_FLAG_ANY)
Seek at a specific frame / time (in seconds)
Note:
Seek in file by using the default stream (according to ffmpeg)
Parameters:
flag,: ffmpeg seek flag (by default seek to any frame, even non-keyframes)
Warning:
If the seek is done to a non key-frame, the decoding will start from the next key-frame
Returns:
seek status
Definition at line 88 of file InputFile.cpp.
References _formatContext, getFps(), and avtranscoder::FormatContext::seek().
Referenced by avtranscoder::IReader::readFrameAt().
bool avtranscoder::InputFile::seekAtTime (const double time, const int flag = AVSEEK_FLAG_ANY)
Definition at line 94 of file InputFile.cpp.
References _formatContext, and avtranscoder::FormatContext::seek().
Referenced by avtranscoder::Transcoder::addInputFile().
void avtranscoder::InputFile::setupUnwrapping (const ProfileLoader::Profile & profile) [virtual]
Set the format of the input file.
Parameters:
profile,: the profile of the input format
Definition at line 165 of file InputFile.cpp.
References _formatContext, avtranscoder::constants::avProfileIdentificator, avtranscoder::constants::avProfileIdentificatorHuman, avtranscoder::constants::avProfileType, avtranscoder::ProfileLoader::checkFormatProfile(), avtranscoder::FormatContext::getOption(), LOG_ERROR, LOG_INFO, LOG_WARN, and avtranscoder::Option::setString().
Field Documentation
std::string avtranscoder::InputFile::_filename [protected]
Definition at line 124 of file InputFile.hpp.
Referenced by getFormatLongName(), getFormatMimeType(), getFormatName(), and readNextPacket().
FormatContext avtranscoder::InputFile::_formatContext [protected]
Definition at line 122 of file InputFile.hpp.
Referenced by getFormatLongName(), getFormatMimeType(), getFormatName(), InputFile(), readNextPacket(), seekAtFrame(), seekAtTime(), and setupUnwrapping().
std::vector<InputStream*> avtranscoder::InputFile::_inputStreams [protected]
Has ownership.
Definition at line 125 of file InputFile.hpp.
Referenced by getStream(), InputFile(), readNextPacket(), and ~InputFile().
FileProperties avtranscoder::InputFile::_properties [protected]
Definition at line 123 of file InputFile.hpp.
Referenced by analyse(), and getFps().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/file/InputFile.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/file/InputFile.cpp