AvTranscoder: avtranscoder::OutputAudio Class Reference
avtranscoder::OutputAudio Class Reference
#include <OutputAudio.hpp>
Public Member Functions
OutputAudio ()
void setup ()
Setup the encoder.
bool encodeFrame (const Frame &sourceFrame, DataStream &codedFrame)
bool encodeFrame (DataStream &codedFrame)
void setProfile (const Profile::ProfileDesc &desc, const AudioFrameDesc &frameDesc)
AudioDesc getAudioDesc ()
Public Member Functions inherited from avtranscoder::OutputEssence
OutputEssence (const std::string &codecName)
virtual ~OutputEssence ()
CodedDesc & getCodedDesc ()
Additional Inherited Members
Protected Attributes inherited from avtranscoder::OutputEssence
CodedDesc _codedDesc
Detailed Description
Definition at line 15 of file OutputAudio.hpp.
Constructor & Destructor Documentation
avtranscoder::OutputAudio::OutputAudio ()
Definition at line 18 of file OutputAudio.cpp.
Member Function Documentation
bool avtranscoder::OutputAudio::encodeFrame (const Frame & sourceFrame, DataStream & codedFrame) virtual
Parameters
[out] codedFrame
Implements avtranscoder::OutputEssence.
Definition at line 46 of file OutputAudio.cpp.
References avtranscoder::OutputEssence::_codedDesc, avtranscoder::DataStream::getBuffer(), avtranscoder::CodedDesc::getCodecContext(), avtranscoder::AudioFrame::getNbSamples(), avtranscoder::DataStream::getPtr(), and avtranscoder::Frame::getPtr().
bool avtranscoder::OutputAudio::encodeFrame (DataStream & codedFrame) virtual
get delayed encoded frames
Implements avtranscoder::OutputEssence.
Definition at line 140 of file OutputAudio.cpp.
References avtranscoder::OutputEssence::_codedDesc, avtranscoder::DataStream::getBuffer(), avtranscoder::CodedDesc::getCodecContext(), and avtranscoder::DataStream::getPtr().
AudioDesc avtranscoder::OutputAudio::getAudioDesc () inline
Definition at line 34 of file OutputAudio.hpp.
References avtranscoder::OutputEssence::_codedDesc.
Referenced by main(), and avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::OutputAudio::setProfile (const Profile::ProfileDesc & desc, const AudioFrameDesc & frameDesc)
Definition at line 175 of file OutputAudio.cpp.
References avtranscoder::OutputEssence::_codedDesc, avtranscoder::Profile::avProfileCodec, avtranscoder::Profile::avProfileIdentificator, avtranscoder::Profile::avProfileIdentificatorHuman, avtranscoder::Profile::avProfileSampleFormat, avtranscoder::Profile::avProfileType, avtranscoder::CodedDesc::getCodecContext(), avtranscoder::ParamSet::set(), avtranscoder::CodedDesc::setCodec(), and setup().
Referenced by main(), and avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::OutputAudio::setup () virtual
Setup the encoder.
Implements avtranscoder::OutputEssence.
Definition at line 23 of file OutputAudio.cpp.
References avtranscoder::OutputEssence::_codedDesc, avtranscoder::CodedDesc::getCodec(), and avtranscoder::CodedDesc::getCodecContext().
Referenced by setProfile().
The documentation for this class was generated from the following files:
src/AvTranscoder/EssenceStream/OutputAudio.hpp
src/AvTranscoder/EssenceStream/OutputAudio.cpp