AvTranscoder: avtranscoder::AudioDesc Class Reference
avtranscoder::AudioDesc Class Reference
#include <AudioDesc.hpp>
Public Member Functions
AudioDesc (const std::string &codecName="")
AudioDesc (const AVCodecID codecId)
AudioDesc (const CodedDesc &essenceDesc)
AudioFrameDesc getFrameDesc () const
const size_t getSampleRate () const
const size_t getChannels () const
const AVSampleFormat getSampleFormat () const
void setAudioParameters (const AudioFrameDesc &audioFrameDesc)
void setAudioParameters (const size_t sampleRate, const size_t channels, const AVSampleFormat sampleFormat)
Public Member Functions inherited from avtranscoder::CodedDesc
CodedDesc (const std::string &codecName)
CodedDesc (const AVCodecID codecId)
CodedDesc (AVCodec &avCodec, AVCodecContext &avCodecContext)
virtual ~CodedDesc ()
std::string getCodecName () const
AVCodecID getCodecId () const
int getLatency () const
void setCodec (const std::string &codecName)
void setCodec (const AVCodecID codecId)
AVCodec * getCodec () const
AVCodecContext * getCodecContext () const
Additional Inherited Members
Protected Attributes inherited from avtranscoder::CodedDesc
AVCodec * m_codec
AVCodecContext * m_codecContext
Detailed Description
Definition at line 15 of file AudioDesc.hpp.
Constructor & Destructor Documentation
avtranscoder::AudioDesc::AudioDesc (const std::string & codecName = "")
Definition at line 8 of file AudioDesc.cpp.
avtranscoder::AudioDesc::AudioDesc (const AVCodecID codecId)
Definition at line 13 of file AudioDesc.cpp.
avtranscoder::AudioDesc::AudioDesc (const CodedDesc & essenceDesc)
Definition at line 18 of file AudioDesc.cpp.
References avtranscoder::CodedDesc::getCodec(), avtranscoder::CodedDesc::getCodecContext(), avtranscoder::CodedDesc::m_codec, and avtranscoder::CodedDesc::m_codecContext.
Member Function Documentation
const size_t avtranscoder::AudioDesc::getChannels () const
Definition at line 44 of file AudioDesc.cpp.
References avtranscoder::CodedDesc::m_codecContext.
Referenced by avtranscoder::InputAudio::setup().
AudioFrameDesc avtranscoder::AudioDesc::getFrameDesc () const
Definition at line 25 of file AudioDesc.cpp.
References avtranscoder::CodedDesc::m_codecContext, avtranscoder::AudioFrameDesc::setChannels(), avtranscoder::AudioFrameDesc::setSampleFormat(), and avtranscoder::AudioFrameDesc::setSampleRate().
Referenced by main(), and avtranscoder::StreamTranscoder::StreamTranscoder().
const AVSampleFormat avtranscoder::AudioDesc::getSampleFormat () const
Definition at line 50 of file AudioDesc.cpp.
References avtranscoder::CodedDesc::m_codecContext.
const size_t avtranscoder::AudioDesc::getSampleRate () const
Definition at line 38 of file AudioDesc.cpp.
References avtranscoder::CodedDesc::m_codecContext.
void avtranscoder::AudioDesc::setAudioParameters (const AudioFrameDesc & audioFrameDesc)
Definition at line 56 of file AudioDesc.cpp.
References avtranscoder::AudioFrameDesc::getChannels(), avtranscoder::AudioFrameDesc::getSampleFormat(), and avtranscoder::AudioFrameDesc::getSampleRate().
Referenced by avtranscoder::AvInputStream::getAudioDesc().
void avtranscoder::AudioDesc::setAudioParameters (const size_t sampleRate, const size_t channels, const AVSampleFormat sampleFormat)
Definition at line 61 of file AudioDesc.cpp.
References avtranscoder::CodedDesc::m_codecContext.
The documentation for this class was generated from the following files:
src/AvTranscoder/CodedStructures/AudioDesc.hpp
src/AvTranscoder/CodedStructures/AudioDesc.cpp