AvTranscoder: avtranscoder::ProfileLoader Class Reference
avtranscoder::ProfileLoader Class Reference
#include <ProfileLoader.hpp>
Public Types
typedef std::map< std::string,
std::string > Profile
typedef std::vector< Profile > Profiles
Public Member Functions
ProfileLoader (const bool autoload=true)
void loadProfiles (const std::string &avProfilesPath="")
Load profiles from files in avProfilesPath directory.
void loadProfile (const std::string &avProfileFileName)
Load the profile defines in the given file.
void loadProfile (const Profile &profile)
Load the given profile
Exceptions
throw std::runtime_error if the profile is invalid.
bool hasProfile (const Profile &profile) const
const Profiles & getProfiles () const
Profiles getFormatProfiles () const
Profiles getVideoProfiles () const
Profiles getAudioProfiles () const
const Profile & getProfile (const std::string &avProfileIdentificator) const
Static Public Member Functions
static bool checkFormatProfile (const Profile &profileToCheck)
static bool checkVideoProfile (const Profile &profileToCheck)
static bool checkAudioProfile (const Profile &profileToCheck)
Private Attributes
Profiles _profiles
Detailed Description
Definition at line 35 of file ProfileLoader.hpp.
Member Typedef Documentation
typedef std::map<std::string, std::string> avtranscoder::ProfileLoader::Profile
Definition at line 38 of file ProfileLoader.hpp.
typedef std::vector<Profile> avtranscoder::ProfileLoader::Profiles
Definition at line 39 of file ProfileLoader.hpp.
Constructor & Destructor Documentation
avtranscoder::ProfileLoader::ProfileLoader (const bool autoload = true)
Parameters
autoload load profiles defined as text files at AVPROFILES
Definition at line 12 of file ProfileLoader.cpp.
References loadProfiles().
Member Function Documentation
bool avtranscoder::ProfileLoader::checkAudioProfile (const Profile & profileToCheck) static
Definition at line 207 of file ProfileLoader.cpp.
References avtranscoder::constants::avProfileCodec, avtranscoder::constants::avProfileIdentificator, avtranscoder::constants::avProfileIdentificatorHuman, and avtranscoder::constants::avProfileType.
Referenced by loadProfile(), avtranscoder::AudioDecoder::setupDecoder(), and avtranscoder::AudioEncoder::setupEncoder().
bool avtranscoder::ProfileLoader::checkFormatProfile (const Profile & profileToCheck) static
Definition at line 179 of file ProfileLoader.cpp.
References avtranscoder::constants::avProfileFormat, avtranscoder::constants::avProfileIdentificator, avtranscoder::constants::avProfileIdentificatorHuman, and avtranscoder::constants::avProfileType.
Referenced by loadProfile(), avtranscoder::InputFile::setupUnwrapping(), and avtranscoder::OutputFile::setupWrapping().
bool avtranscoder::ProfileLoader::checkVideoProfile (const Profile & profileToCheck) static
Definition at line 193 of file ProfileLoader.cpp.
References avtranscoder::constants::avProfileCodec, avtranscoder::constants::avProfileIdentificator, avtranscoder::constants::avProfileIdentificatorHuman, and avtranscoder::constants::avProfileType.
Referenced by loadProfile(), avtranscoder::VideoDecoder::setupDecoder(), and avtranscoder::VideoEncoder::setupEncoder().
ProfileLoader::Profiles avtranscoder::ProfileLoader::getAudioProfiles () const
Definition at line 154 of file ProfileLoader.cpp.
References _profiles, avtranscoder::constants::avProfileType, and avtranscoder::constants::avProfileTypeAudio.
ProfileLoader::Profiles avtranscoder::ProfileLoader::getFormatProfiles () const
Definition at line 128 of file ProfileLoader.cpp.
References _profiles, avtranscoder::constants::avProfileType, and avtranscoder::constants::avProfileTypeFormat.
const ProfileLoader::Profile & avtranscoder::ProfileLoader::getProfile (const std::string & avProfileIdentificator) const
Definition at line 167 of file ProfileLoader.cpp.
References _profiles, and avtranscoder::constants::avProfileIdentificator.
Referenced by avtranscoder::Transcoder::add().
const ProfileLoader::Profiles & avtranscoder::ProfileLoader::getProfiles () const
Definition at line 123 of file ProfileLoader.cpp.
References _profiles.
ProfileLoader::Profiles avtranscoder::ProfileLoader::getVideoProfiles () const
Definition at line 141 of file ProfileLoader.cpp.
References _profiles, avtranscoder::constants::avProfileType, and avtranscoder::constants::avProfileTypeVideo.
bool avtranscoder::ProfileLoader::hasProfile (const Profile & profile) const
Definition at line 107 of file ProfileLoader.cpp.
References _profiles, and avtranscoder::constants::avProfileIdentificator.
Referenced by avtranscoder::Transcoder::addDummyStream(), and avtranscoder::Transcoder::addTranscodeStream().
void avtranscoder::ProfileLoader::loadProfile (const std::string & avProfileFileName)
Load the profile defines in the given file.
Definition at line 18 of file ProfileLoader.cpp.
References avtranscoder::split().
Referenced by avtranscoder::Transcoder::addDummyStream(), avtranscoder::Transcoder::addTranscodeStream(), and loadProfiles().
void avtranscoder::ProfileLoader::loadProfile (const Profile & profile)
Load the given profile
Exceptions
throw std::runtime_error if the profile is invalid.
Definition at line 72 of file ProfileLoader.cpp.
References _profiles, avtranscoder::constants::avProfileIdentificator, avtranscoder::constants::avProfileIdentificatorHuman, avtranscoder::constants::avProfileType, avtranscoder::constants::avProfileTypeAudio, avtranscoder::constants::avProfileTypeFormat, avtranscoder::constants::avProfileTypeVideo, checkAudioProfile(), checkFormatProfile(), checkVideoProfile(), and LOG_INFO.
void avtranscoder::ProfileLoader::loadProfiles (const std::string & avProfilesPath = "")
Load profiles from files in avProfilesPath directory.
Parameters
avProfilesPath if empty, the path is replaced by value of AVPROFILES environment variable
Definition at line 36 of file ProfileLoader.cpp.
References avtranscoder::getFilesInDir(), loadProfile(), LOG_WARN, and avtranscoder::split().
Referenced by ProfileLoader().
Field Documentation
Profiles avtranscoder::ProfileLoader::_profiles private
Definition at line 80 of file ProfileLoader.hpp.
Referenced by getAudioProfiles(), getFormatProfiles(), getProfile(), getProfiles(), getVideoProfiles(), hasProfile(), and loadProfile().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/profile/ProfileLoader.hpp
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/profile/ProfileLoader.cpp