AvTranscoder: Reader Class Reference
Reader Class Reference
#include <Reader.hpp>
Public Member Functions
Reader ()
virtual size_t getWidth ()=0
virtual size_t getHeight ()=0
virtual size_t getComponents ()=0
virtual size_t getBitDepth ()=0
virtual const char * readNextFrame ()=0
virtual const char * readPrevFrame ()=0
virtual const char * readFrameAt (const size_t frame)=0
virtual void printMetadatas ()=0
Protected Attributes
size_t currentFrame
Detailed Description
Definition at line 4 of file Reader.hpp.
Constructor & Destructor Documentation
Reader::Reader () inline
Definition at line 7 of file Reader.hpp.
Member Function Documentation
virtual size_t Reader::getBitDepth () pure virtual
Implemented in AvReader.
virtual size_t Reader::getComponents () pure virtual
Implemented in AvReader.
Referenced by Window::displayAtFrame(), Window::displayNextFrame(), and Window::displayPrevFrame().
virtual size_t Reader::getHeight () pure virtual
Implemented in AvReader.
Referenced by Window::displayAtFrame(), Window::displayNextFrame(), Window::displayPrevFrame(), and Window::Window().
virtual size_t Reader::getWidth () pure virtual
Implemented in AvReader.
Referenced by Window::displayAtFrame(), Window::displayNextFrame(), Window::displayPrevFrame(), and Window::Window().
virtual void Reader::printMetadatas () pure virtual
Implemented in AvReader.
Referenced by Window::keyboard().
virtual const char* Reader::readFrameAt (const size_t frame) pure virtual
Implemented in AvReader.
Referenced by Window::displayAtFrame().
virtual const char* Reader::readNextFrame () pure virtual
Implemented in AvReader.
Referenced by Window::displayNextFrame().
virtual const char* Reader::readPrevFrame () pure virtual
Implemented in AvReader.
Referenced by Window::displayPrevFrame().
Field Documentation
size_t Reader::currentFrame protected
Definition at line 24 of file Reader.hpp.
Referenced by AvReader::readNextFrame(), and AvReader::readPrevFrame().
The documentation for this class was generated from the following file:
app/cpp/avplay/Reader.hpp