AvTranscoder: avtranscoder::Pixel Class Reference
avtranscoder::Pixel Class Reference
#include <Pixel.hpp>
Public Member Functions
Pixel ()
Pixel (const std::string &avPixelFormat)
Pixel (const AVPixelFormat avPixelFormat)
void setBitsPerPixel (const size_t pixelSize)
void setBigEndian (const bool endianess)
void setComponents (const size_t components)
void setColorComponents (const EComponentType componentType)
void setSubsampling (const ESubsamplingType subsamplingType=eSubsamplingNone)
void setAlpha (const bool withAlpha=true)
void setPlanar (const bool isPlanar)
size_t getBitsPerPixel () const
bool getBigEndian () const
size_t getComponents () const
EComponentType getColorComponents () const
ESubsamplingType getSubsampling () const
bool getAlpha () const
bool getPlanar () const
AVPixelFormat findPixel () const
Private Member Functions
void init (const AVPixelFormat avPixelFormat)
bool asCorrectColorComponents (const AVPixFmtDescriptor *pix_desc, const EComponentType componentType) const
bool asCorrectSubsampling (const AVPixFmtDescriptor *pix_desc, const ESubsamplingType subsamplingType) const
Private Attributes
size_t m_pixelSize
size_t m_components
EComponentType m_componentType
ESubsamplingType m_subsamplingType
bool m_endianess
bool m_withAlpha
bool m_planar
Detailed Description
Definition at line 34 of file Pixel.hpp.
Constructor & Destructor Documentation
avtranscoder::Pixel::Pixel () inline
Definition at line 37 of file Pixel.hpp.
avtranscoder::Pixel::Pixel (const std::string & avPixelFormat)
Definition at line 18 of file Pixel.cpp.
References init().
avtranscoder::Pixel::Pixel (const AVPixelFormat avPixelFormat)
Definition at line 23 of file Pixel.cpp.
References init().
Member Function Documentation
bool avtranscoder::Pixel::asCorrectColorComponents (const AVPixFmtDescriptor * pix_desc, const EComponentType componentType) const private
Definition at line 105 of file Pixel.cpp.
References avtranscoder::eComponentRgb.
Referenced by findPixel().
bool avtranscoder::Pixel::asCorrectSubsampling (const AVPixFmtDescriptor * pix_desc, const ESubsamplingType subsamplingType) const private
Definition at line 114 of file Pixel.cpp.
References avtranscoder::eSubsampling420, avtranscoder::eSubsampling422, and avtranscoder::eSubsamplingNone.
Referenced by findPixel().
AVPixelFormat avtranscoder::Pixel::findPixel () const
Definition at line 35 of file Pixel.cpp.
References asCorrectColorComponents(), asCorrectSubsampling(), AV_PIX_FMT_NONE, AVPixelFormat, m_components, m_componentType, m_endianess, m_pixelSize, m_planar, m_subsamplingType, and m_withAlpha.
Referenced by AvReader::AvReader(), avtranscoder::VideoEssenceTransform::init(), and avtranscoder::VideoDesc::setImageParameters().
bool avtranscoder::Pixel::getAlpha () const inline
Definition at line 64 of file Pixel.hpp.
References m_withAlpha.
bool avtranscoder::Pixel::getBigEndian () const inline
Definition at line 60 of file Pixel.hpp.
References m_endianess.
size_t avtranscoder::Pixel::getBitsPerPixel () const inline
Definition at line 59 of file Pixel.hpp.
References m_pixelSize.
EComponentType avtranscoder::Pixel::getColorComponents () const inline
Definition at line 62 of file Pixel.hpp.
References m_componentType.
size_t avtranscoder::Pixel::getComponents () const inline
Definition at line 61 of file Pixel.hpp.
References m_components.
Referenced by avtranscoder::VideoEssenceTransform::convert().
bool avtranscoder::Pixel::getPlanar () const inline
Definition at line 65 of file Pixel.hpp.
References m_planar.
ESubsamplingType avtranscoder::Pixel::getSubsampling () const inline
Definition at line 63 of file Pixel.hpp.
References m_subsamplingType.
void avtranscoder::Pixel::init (const AVPixelFormat avPixelFormat) private
Definition at line 68 of file Pixel.cpp.
References avtranscoder::eComponentGray, avtranscoder::eComponentRgb, avtranscoder::eComponentYuv, avtranscoder::eSubsampling420, avtranscoder::eSubsampling422, avtranscoder::eSubsamplingNone, setAlpha(), setBigEndian(), setBitsPerPixel(), setColorComponents(), setComponents(), setPlanar(), and setSubsampling().
Referenced by Pixel().
void avtranscoder::Pixel::setAlpha (const bool withAlpha = true) inline
Definition at line 56 of file Pixel.hpp.
References m_withAlpha.
Referenced by AvReader::AvReader(), and init().
void avtranscoder::Pixel::setBigEndian (const bool endianess) inline
Definition at line 52 of file Pixel.hpp.
References m_endianess.
Referenced by init().
void avtranscoder::Pixel::setBitsPerPixel (const size_t pixelSize) inline
Definition at line 51 of file Pixel.hpp.
References m_pixelSize.
Referenced by AvReader::AvReader(), and init().
void avtranscoder::Pixel::setColorComponents (const EComponentType componentType) inline
Definition at line 54 of file Pixel.hpp.
References m_componentType.
Referenced by AvReader::AvReader(), init(), and avtranscoder::DummyVideo::readNextFrame().
void avtranscoder::Pixel::setComponents (const size_t components) inline
Definition at line 53 of file Pixel.hpp.
References m_components.
Referenced by AvReader::AvReader(), and init().
void avtranscoder::Pixel::setPlanar (const bool isPlanar) inline
Definition at line 57 of file Pixel.hpp.
References m_planar.
Referenced by AvReader::AvReader(), and init().
void avtranscoder::Pixel::setSubsampling (const ESubsamplingType subsamplingType = eSubsamplingNone) inline
Definition at line 55 of file Pixel.hpp.
References m_subsamplingType.
Referenced by AvReader::AvReader(), and init().
Field Documentation
size_t avtranscoder::Pixel::m_components private
Definition at line 76 of file Pixel.hpp.
Referenced by findPixel(), getComponents(), and setComponents().
EComponentType avtranscoder::Pixel::m_componentType private
Definition at line 77 of file Pixel.hpp.
Referenced by findPixel(), getColorComponents(), and setColorComponents().
bool avtranscoder::Pixel::m_endianess private
Definition at line 79 of file Pixel.hpp.
Referenced by findPixel(), getBigEndian(), and setBigEndian().
size_t avtranscoder::Pixel::m_pixelSize private
Definition at line 75 of file Pixel.hpp.
Referenced by findPixel(), getBitsPerPixel(), and setBitsPerPixel().
bool avtranscoder::Pixel::m_planar private
Definition at line 81 of file Pixel.hpp.
Referenced by findPixel(), getPlanar(), and setPlanar().
ESubsamplingType avtranscoder::Pixel::m_subsamplingType private
Definition at line 78 of file Pixel.hpp.
Referenced by findPixel(), getSubsampling(), and setSubsampling().
bool avtranscoder::Pixel::m_withAlpha private
Definition at line 80 of file Pixel.hpp.
Referenced by findPixel(), getAlpha(), and setAlpha().
The documentation for this class was generated from the following files:
src/AvTranscoder/EssenceStructures/Pixel.hpp
src/AvTranscoder/EssenceStructures/Pixel.cpp