AvTranscoder: avtranscoder::VideoDesc Class Reference
avtranscoder::VideoDesc Class Reference
#include <VideoDesc.hpp>
Public Member Functions
VideoDesc (const std::string &codecName="")
VideoDesc (const AVCodecID codecId)
VideoDesc (const CodedDesc &essenceDesc)
VideoFrameDesc getVideoFrameDesc () const
std::pair< size_t, size_t > getTimeBase () const
void setImageParameters (const VideoFrameDesc &videoFrameDesc)
void setImageParameters (const size_t width, const size_t height, const Pixel &pixel)
void setImageParameters (const size_t width, const size_t height, const AVPixelFormat &pixel)
void setTimeBase (const size_t num, const size_t den, const size_t ticksPerFrame=1)
Public Member Functions inherited from avtranscoder::CodedDesc
CodedDesc (const std::string &codecName)
CodedDesc (const AVCodecID codecId)
CodedDesc (AVCodec &avCodec, AVCodecContext &avCodecContext)
virtual ~CodedDesc ()
std::string getCodecName () const
AVCodecID getCodecId () const
int getLatency () const
void setCodec (const std::string &codecName)
void setCodec (const AVCodecID codecId)
AVCodec * getCodec () const
AVCodecContext * getCodecContext () const
Additional Inherited Members
Protected Attributes inherited from avtranscoder::CodedDesc
AVCodec * m_codec
AVCodecContext * m_codecContext
Detailed Description
Definition at line 15 of file VideoDesc.hpp.
Constructor & Destructor Documentation
avtranscoder::VideoDesc::VideoDesc (const std::string & codecName = "")
Definition at line 8 of file VideoDesc.cpp.
avtranscoder::VideoDesc::VideoDesc (const AVCodecID codecId)
Definition at line 13 of file VideoDesc.cpp.
avtranscoder::VideoDesc::VideoDesc (const CodedDesc & essenceDesc)
Definition at line 18 of file VideoDesc.cpp.
References avtranscoder::CodedDesc::getCodec(), avtranscoder::CodedDesc::getCodecContext(), avtranscoder::CodedDesc::m_codec, and avtranscoder::CodedDesc::m_codecContext.
Member Function Documentation
std::pair< size_t, size_t > avtranscoder::VideoDesc::getTimeBase () const
Definition at line 38 of file VideoDesc.cpp.
References avtranscoder::CodedDesc::m_codecContext.
VideoFrameDesc avtranscoder::VideoDesc::getVideoFrameDesc () const
Definition at line 25 of file VideoDesc.cpp.
References avtranscoder::CodedDesc::m_codecContext, avtranscoder::VideoFrameDesc::setDar(), avtranscoder::VideoFrameDesc::setHeight(), avtranscoder::VideoFrameDesc::setPixel(), and avtranscoder::VideoFrameDesc::setWidth().
Referenced by AvReader::AvReader(), main(), avtranscoder::DummyVideo::readNextFrame(), avtranscoder::DummyVideo::setVideoDesc(), avtranscoder::StreamTranscoder::StreamTranscoder(), and transcodeVideo().
void avtranscoder::VideoDesc::setImageParameters (const VideoFrameDesc & videoFrameDesc)
Definition at line 47 of file VideoDesc.cpp.
References avtranscoder::VideoFrameDesc::getHeight(), avtranscoder::VideoFrameDesc::getPixelDesc(), and avtranscoder::VideoFrameDesc::getWidth().
Referenced by avtranscoder::AvInputStream::getVideoDesc(), parseConfigFile(), and setImageParameters().
void avtranscoder::VideoDesc::setImageParameters (const size_t width, const size_t height, const Pixel & pixel)
Definition at line 53 of file VideoDesc.cpp.
References avtranscoder::Pixel::findPixel(), and setImageParameters().
void avtranscoder::VideoDesc::setImageParameters (const size_t width, const size_t height, const AVPixelFormat & pixel)
Definition at line 58 of file VideoDesc.cpp.
References avtranscoder::CodedDesc::m_codecContext.
void avtranscoder::VideoDesc::setTimeBase (const size_t num, const size_t den, const size_t ticksPerFrame = 1)
Definition at line 65 of file VideoDesc.cpp.
References avtranscoder::CodedDesc::m_codecContext.
Referenced by avtranscoder::AvInputStream::getVideoDesc().
The documentation for this class was generated from the following files:
src/AvTranscoder/CodedStructures/VideoDesc.hpp
src/AvTranscoder/CodedStructures/VideoDesc.cpp