AvTranscoder: avtranscoder::Filter Class Reference
avtranscoder::Filter Class Reference
Describe a filter and its options.
#include <Filter.hpp>
Public Member Functions
Filter (const std::string &name, const std::string &options="", const std::string &instanceName="")
~Filter ()
std::string getName () const
std::string getOptions () const
std::string getInstanceName () const
AVFilter & getAVFilter ()
AVFilterContext * getAVFilterContext ()
void setAVFilterContext (AVFilterContext *newContext)
Private Attributes
AVFilter * _filter
AVFilterContext * _context
std::string _options
std::string _instanceName
Detailed Description
Describe a filter and its options.
Definition at line 15 of file Filter.hpp.
Constructor & Destructor Documentation
avtranscoder::Filter::Filter (const std::string & name, const std::string & options = "", const std::string & instanceName = "")
Definition at line 12 of file Filter.cpp.
References _filter.
avtranscoder::Filter::~Filter ()
Definition at line 28 of file Filter.cpp.
References _context.
Member Function Documentation
AVFilter& avtranscoder::Filter::getAVFilter () inline
Definition at line 26 of file Filter.hpp.
Referenced by avtranscoder::FilterGraph::pushFilter().
AVFilterContext* avtranscoder::Filter::getAVFilterContext () inline
Definition at line 27 of file Filter.hpp.
std::string avtranscoder::Filter::getInstanceName () const inline
Definition at line 23 of file Filter.hpp.
Referenced by avtranscoder::FilterGraph::pushFilter().
std::string avtranscoder::Filter::getName () const
Definition at line 33 of file Filter.cpp.
References _filter.
Referenced by avtranscoder::FilterGraph::pushFilter().
std::string avtranscoder::Filter::getOptions () const inline
Definition at line 22 of file Filter.hpp.
Referenced by avtranscoder::FilterGraph::pushFilter().
void avtranscoder::Filter::setAVFilterContext (AVFilterContext * newContext) inline
Definition at line 29 of file Filter.hpp.
Referenced by avtranscoder::FilterGraph::pushFilter().
Field Documentation
AVFilterContext* avtranscoder::Filter::_context private
Definition at line 34 of file Filter.hpp.
Referenced by ~Filter().
AVFilter* avtranscoder::Filter::_filter private
Definition at line 33 of file Filter.hpp.
Referenced by Filter(), and getName().
std::string avtranscoder::Filter::_instanceName private
Definition at line 36 of file Filter.hpp.
std::string avtranscoder::Filter::_options private
Definition at line 35 of file Filter.hpp.
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/filter/Filter.hpp
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/filter/Filter.cpp