AvTranscoder: avtranscoder::DummyAudio Class Reference
avtranscoder::DummyAudio Class Reference
#include <DummyAudio.hpp>
Public Member Functions
DummyAudio ()
~DummyAudio ()
void setAudioDesc (const AudioDesc &audioDesc)
AudioDesc getAudioDesc () const
void setup ()
void setFrame (Frame &inputFrame)
bool readNextFrame (Frame &frameBuffer)
bool readNextFrame (Frame &frameBuffer, const size_t subStreamIndex)
Public Member Functions inherited from avtranscoder::InputEssence
InputEssence ()
virtual ~InputEssence ()
Private Attributes
AudioDesc _audioDesc
AudioFrameDesc _frameDesc
Frame * _inputFrame
Detailed Description
Definition at line 13 of file DummyAudio.hpp.
Constructor & Destructor Documentation
avtranscoder::DummyAudio::DummyAudio ()
Definition at line 6 of file DummyAudio.cpp.
avtranscoder::DummyAudio::~DummyAudio ()
Definition at line 12 of file DummyAudio.cpp.
Member Function Documentation
AudioDesc avtranscoder::DummyAudio::getAudioDesc () const
Definition at line 26 of file DummyAudio.cpp.
References _audioDesc.
bool avtranscoder::DummyAudio::readNextFrame (Frame & frameBuffer) virtual
Implements avtranscoder::InputEssence.
Definition at line 36 of file DummyAudio.cpp.
References _frameDesc, _inputFrame, avtranscoder::Frame::getBuffer(), avtranscoder::AudioFrameDesc::getDataSize(), avtranscoder::AudioFrameDesc::getFps(), avtranscoder::Frame::getPtr(), avtranscoder::AudioFrameDesc::getSampleFormat(), avtranscoder::AudioFrameDesc::getSampleRate(), avtranscoder::Frame::getSize(), and avtranscoder::AudioFrame::setNbSamples().
bool avtranscoder::DummyAudio::readNextFrame (Frame & frameBuffer, const size_t subStreamIndex) virtual
Implements avtranscoder::InputEssence.
Definition at line 61 of file DummyAudio.cpp.
void avtranscoder::DummyAudio::setAudioDesc (const AudioDesc & audioDesc)
Definition at line 16 of file DummyAudio.cpp.
References _audioDesc, _frameDesc, avtranscoder::CodedDesc::getCodecContext(), avtranscoder::AudioFrameDesc::setChannels(), avtranscoder::AudioFrameDesc::setFps(), avtranscoder::AudioFrameDesc::setSampleFormat(), and avtranscoder::AudioFrameDesc::setSampleRate().
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::DummyAudio::setFrame (Frame & inputFrame)
Definition at line 31 of file DummyAudio.cpp.
References _inputFrame.
void avtranscoder::DummyAudio::setup () inline virtual
Implements avtranscoder::InputEssence.
Definition at line 25 of file DummyAudio.hpp.
Field Documentation
AudioDesc avtranscoder::DummyAudio::_audioDesc private
Definition at line 33 of file DummyAudio.hpp.
Referenced by getAudioDesc(), and setAudioDesc().
AudioFrameDesc avtranscoder::DummyAudio::_frameDesc private
Definition at line 34 of file DummyAudio.hpp.
Referenced by readNextFrame(), and setAudioDesc().
Frame* avtranscoder::DummyAudio::_inputFrame private
Definition at line 36 of file DummyAudio.hpp.
Referenced by readNextFrame(), and setFrame().
The documentation for this class was generated from the following files:
src/AvTranscoder/EssenceStream/DummyAudio.hpp
src/AvTranscoder/EssenceStream/DummyAudio.cpp