AvTranscoder: avtranscoder::VideoGenerator Class Reference
avtranscoder::VideoGenerator Class Reference
#include <VideoGenerator.hpp>
Public Member Functions
VideoGenerator ()
VideoGenerator (const VideoGenerator &videoGenerator)
VideoGenerator & operator= (const VideoGenerator &videoGenerator)
~VideoGenerator ()
bool decodeNextFrame (Frame &frameBuffer)
Decode next frame.
bool decodeNextFrame (Frame &frameBuffer, const size_t subStreamIndex)
Decode substream of next frame.
const VideoFrameDesc & getVideoFrameDesc () const
void setVideoFrameDesc (const VideoFrameDesc &frameDesc)
void setNextFrame (Frame &inputFrame)
Set the next frame of the input stream (which bypass the work of decoding)
Private Attributes
Frame * _inputFrame
A frame given from outside (has link, no ownership)
VideoFrame * _blackImage
The generated black image (has ownership)
VideoFrameDesc _frameDesc
The description of the black image (width, height...)
Detailed Description
Definition at line 10 of file VideoGenerator.hpp.
Constructor & Destructor Documentation
avtranscoder::VideoGenerator::VideoGenerator ()
Definition at line 8 of file VideoGenerator.cpp.
avtranscoder::VideoGenerator::VideoGenerator (const VideoGenerator & videoGenerator)
Definition at line 15 of file VideoGenerator.cpp.
avtranscoder::VideoGenerator::~VideoGenerator ()
Definition at line 30 of file VideoGenerator.cpp.
References _blackImage.
Member Function Documentation
bool avtranscoder::VideoGenerator::decodeNextFrame (Frame & frameBuffer) [virtual]
Decode next frame.
Parameters:
frameBuffer,: the frame decoded
Returns:
status of decoding
Implements avtranscoder::IDecoder.
Definition at line 45 of file VideoGenerator.cpp.
References _blackImage, _frameDesc, _inputFrame, avtranscoder::Frame::assign(), avtranscoder::VideoTransform::convert(), avtranscoder::VideoFrame::desc(), avtranscoder::Frame::getData(), avtranscoder::VideoFrameDesc::getDataSize(), avtranscoder::Frame::getSize(), avtranscoder::Frame::refData(), and avtranscoder::VideoFrameDesc::setPixelFormat().
bool avtranscoder::VideoGenerator::decodeNextFrame (Frame & frameBuffer, const size_t subStreamIndex) [virtual]
Decode substream of next frame.
Parameters:
frameBuffer,: the frame decoded
subStreamIndex,: index of substream to extract
Returns:
status of decoding
Implements avtranscoder::IDecoder.
Definition at line 81 of file VideoGenerator.cpp.
const VideoFrameDesc& avtranscoder::VideoGenerator::getVideoFrameDesc () const [inline]
Definition at line 22 of file VideoGenerator.hpp.
Referenced by operator=().
VideoGenerator & avtranscoder::VideoGenerator::operator= (const VideoGenerator & videoGenerator)
Definition at line 22 of file VideoGenerator.cpp.
References _blackImage, _frameDesc, _inputFrame, and getVideoFrameDesc().
void avtranscoder::VideoGenerator::setNextFrame (Frame & inputFrame) [virtual]
Set the next frame of the input stream (which bypass the work of decoding)
Note:
Not yet implemented for VideoDecoder and AudioDecoder
Parameters:
inputFrame,: the new next frame
Reimplemented from avtranscoder::IDecoder.
Definition at line 40 of file VideoGenerator.cpp.
References _inputFrame.
void avtranscoder::VideoGenerator::setVideoFrameDesc (const VideoFrameDesc & frameDesc)
Definition at line 35 of file VideoGenerator.cpp.
References _frameDesc.
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
Field Documentation
VideoFrame* avtranscoder::VideoGenerator::_blackImage [private]
The generated black image (has ownership)
Definition at line 28 of file VideoGenerator.hpp.
Referenced by decodeNextFrame(), operator=(), and ~VideoGenerator().
VideoFrameDesc avtranscoder::VideoGenerator::_frameDesc [private]
The description of the black image (width, height...)
Definition at line 29 of file VideoGenerator.hpp.
Referenced by decodeNextFrame(), operator=(), and setVideoFrameDesc().
Frame* avtranscoder::VideoGenerator::_inputFrame [private]
A frame given from outside (has link, no ownership)
Definition at line 27 of file VideoGenerator.hpp.
Referenced by decodeNextFrame(), operator=(), and setNextFrame().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/decoder/VideoGenerator.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/decoder/VideoGenerator.cpp