AvTranscoder: avtranscoder::VideoDecoder Class Reference
avtranscoder::VideoDecoder Class Reference
#include <VideoDecoder.hpp>
Public Member Functions
VideoDecoder (InputStream &inputStream)
~VideoDecoder ()
void setupDecoder (const ProfileLoader::Profile &profile=ProfileLoader::Profile())
Setup the decoder.
bool decodeNextFrame (Frame &frameBuffer)
Decode next frame.
bool decodeNextFrame (Frame &frameBuffer, const size_t subStreamIndex)
Decode substream of next frame.
void flushDecoder ()
Reset the internal decoder state / flush internal buffers.
Private Member Functions
bool decodeNextFrame ()
Private Attributes
InputStream * _inputStream
Stream from which we read next frames (no ownership, has link)
AVFrame * _frame
Libav object to store decoded data (has ownership)
bool _isSetup
Detailed Description
Definition at line 13 of file VideoDecoder.hpp.
Constructor & Destructor Documentation
avtranscoder::VideoDecoder::VideoDecoder (InputStream & inputStream)
Definition at line 19 of file VideoDecoder.cpp.
References _frame.
avtranscoder::VideoDecoder::~VideoDecoder ()
Definition at line 35 of file VideoDecoder.cpp.
References _frame.
Member Function Documentation
bool avtranscoder::VideoDecoder::decodeNextFrame (Frame & frameBuffer) [virtual]
Decode next frame.
Parameters:
frameBuffer,: the frame decoded
Returns:
status of decoding
Implements avtranscoder::IDecoder.
Definition at line 98 of file VideoDecoder.cpp.
References _frame, AVPixelFormat, decodeNextFrame(), avtranscoder::Frame::getData(), avtranscoder::Frame::getSize(), and avtranscoder::Frame::resize().
bool avtranscoder::VideoDecoder::decodeNextFrame (Frame & frameBuffer, const size_t subStreamIndex) [virtual]
Decode substream of next frame.
Parameters:
frameBuffer,: the frame decoded
subStreamIndex,: index of substream to extract
Returns:
status of decoding
Implements avtranscoder::IDecoder.
Definition at line 116 of file VideoDecoder.cpp.
bool avtranscoder::VideoDecoder::decodeNextFrame () [private]
Definition at line 121 of file VideoDecoder.cpp.
References _frame, _inputStream, _isSetup, avtranscoder::Frame::clear(), avtranscoder::ICodec::getAVCodecContext(), avtranscoder::Frame::getAVPacket(), avtranscoder::getDescriptionFromErrorCode(), avtranscoder::InputStream::getVideoCodec(), avtranscoder::InputStream::readNextPacket(), and setupDecoder().
Referenced by decodeNextFrame().
void avtranscoder::VideoDecoder::flushDecoder () [virtual]
Reset the internal decoder state / flush internal buffers.
Note:
Should be called when seeking or when switching to a different stream.
Not sense for generators.
Reimplemented from avtranscoder::IDecoder.
Definition at line 147 of file VideoDecoder.cpp.
References _inputStream, avtranscoder::ICodec::getAVCodecContext(), and avtranscoder::InputStream::getVideoCodec().
void avtranscoder::VideoDecoder::setupDecoder (const ProfileLoader::Profile & profile = ProfileLoader::Profile()) [virtual]
Setup the decoder.
Parameters:
profile,: set decoder parameters from the given profile
Note:
Open the decoder.
Reimplemented from avtranscoder::IDecoder.
Definition at line 52 of file VideoDecoder.cpp.
References _inputStream, _isSetup, avtranscoder::constants::avProfileIdentificator, avtranscoder::constants::avProfileIdentificatorHuman, avtranscoder::constants::avProfileThreads, avtranscoder::constants::avProfileType, avtranscoder::ProfileLoader::checkVideoProfile(), avtranscoder::ICodec::getAVCodecContext(), avtranscoder::ICodec::getOption(), avtranscoder::InputStream::getVideoCodec(), LOG_ERROR, LOG_INFO, LOG_WARN, avtranscoder::ICodec::openCodec(), avtranscoder::Option::setInt(), and avtranscoder::Option::setString().
Referenced by decodeNextFrame(), and avtranscoder::StreamTranscoder::StreamTranscoder().
Field Documentation
AVFrame* avtranscoder::VideoDecoder::_frame [private]
Libav object to store decoded data (has ownership)
Definition at line 31 of file VideoDecoder.hpp.
Referenced by decodeNextFrame(), VideoDecoder(), and ~VideoDecoder().
InputStream* avtranscoder::VideoDecoder::_inputStream [private]
Stream from which we read next frames (no ownership, has link)
Definition at line 30 of file VideoDecoder.hpp.
Referenced by decodeNextFrame(), flushDecoder(), and setupDecoder().
bool avtranscoder::VideoDecoder::_isSetup [private]
Definition at line 33 of file VideoDecoder.hpp.
Referenced by decodeNextFrame(), and setupDecoder().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/decoder/VideoDecoder.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/decoder/VideoDecoder.cpp