AvTranscoder: avtranscoder::VideoEssenceTransform Class Reference
avtranscoder::VideoEssenceTransform Class Reference
#include <VideoEssenceTransform.hpp>
Public Member Functions
VideoEssenceTransform ()
void convert (const Frame &srcFrame, Frame &dstFrame)
void setVerbose (bool verbose=false)
Public Member Functions inherited from avtranscoder::EssenceTransform
EssenceTransform ()
virtual ~EssenceTransform ()
Private Member Functions
bool init (const Frame &srcFrame, const Frame &dstFrame)
Private Attributes
SwsContext * _imageConvertContext
std::vector< uint8_t * > _srcData
std::vector< uint8_t * > _dstData
std::vector< int > _srcLineSize
std::vector< int > _dstLineSize
std::vector< size_t > _srcOffsets
std::vector< size_t > _dstOffsets
bool _isInit
bool _verbose
Additional Inherited Members
Protected Member Functions inherited from avtranscoder::EssenceTransform
virtual bool init (const Frame &src, const Frame &dst)=0
Detailed Description
Definition at line 15 of file VideoEssenceTransform.hpp.
Constructor & Destructor Documentation
avtranscoder::VideoEssenceTransform::VideoEssenceTransform ()
Definition at line 28 of file VideoEssenceTransform.cpp.
Member Function Documentation
void avtranscoder::VideoEssenceTransform::convert (const Frame & srcFrame, Frame & dstFrame) virtual
Implements avtranscoder::EssenceTransform.
Definition at line 114 of file VideoEssenceTransform.cpp.
References _dstData, _dstLineSize, _dstOffsets, _imageConvertContext, _isInit, _srcData, _srcLineSize, _srcOffsets, _verbose, avtranscoder::VideoFrame::desc(), avtranscoder::Pixel::getComponents(), avtranscoder::VideoFrameDesc::getHeight(), avtranscoder::VideoFrameDesc::getPixelDesc(), avtranscoder::Frame::getPtr(), avtranscoder::VideoFrameDesc::getWidth(), init(), and MAX_SWS_PLANE.
Referenced by avtranscoder::DummyVideo::readNextFrame(), AvReader::readNextFrame(), and transcodeVideo().
bool avtranscoder::VideoEssenceTransform::init (const Frame & srcFrame, const Frame & dstFrame) private
Definition at line 41 of file VideoEssenceTransform.cpp.
References _dstLineSize, _dstOffsets, _imageConvertContext, _srcLineSize, _srcOffsets, _verbose, avtranscoder::VideoFrame::desc(), avtranscoder::Pixel::findPixel(), avtranscoder::VideoFrameDesc::getHeight(), avtranscoder::VideoFrameDesc::getPixelDesc(), avtranscoder::VideoFrameDesc::getWidth(), and MAX_SWS_PLANE.
Referenced by convert().
void avtranscoder::VideoEssenceTransform::setVerbose (bool verbose = false) inline
Definition at line 22 of file VideoEssenceTransform.hpp.
References verbose.
Field Documentation
std::vector<uint8_t *> avtranscoder::VideoEssenceTransform::_dstData private
Definition at line 30 of file VideoEssenceTransform.hpp.
Referenced by convert().
std::vector<int> avtranscoder::VideoEssenceTransform::_dstLineSize private
Definition at line 32 of file VideoEssenceTransform.hpp.
Referenced by convert(), and init().
std::vector<size_t> avtranscoder::VideoEssenceTransform::_dstOffsets private
Definition at line 34 of file VideoEssenceTransform.hpp.
Referenced by convert(), and init().
SwsContext* avtranscoder::VideoEssenceTransform::_imageConvertContext private
Definition at line 27 of file VideoEssenceTransform.hpp.
Referenced by convert(), and init().
bool avtranscoder::VideoEssenceTransform::_isInit private
Definition at line 36 of file VideoEssenceTransform.hpp.
Referenced by convert().
std::vector<uint8_t *> avtranscoder::VideoEssenceTransform::_srcData private
Definition at line 29 of file VideoEssenceTransform.hpp.
Referenced by convert().
std::vector<int> avtranscoder::VideoEssenceTransform::_srcLineSize private
Definition at line 31 of file VideoEssenceTransform.hpp.
Referenced by convert(), and init().
std::vector<size_t> avtranscoder::VideoEssenceTransform::_srcOffsets private
Definition at line 33 of file VideoEssenceTransform.hpp.
Referenced by convert(), and init().
bool avtranscoder::VideoEssenceTransform::_verbose private
Definition at line 38 of file VideoEssenceTransform.hpp.
Referenced by convert(), and init().
The documentation for this class was generated from the following files:
src/AvTranscoder/EssenceTransform/VideoEssenceTransform.hpp
src/AvTranscoder/EssenceTransform/VideoEssenceTransform.cpp