AvTranscoder: avtranscoder::VideoFrameDesc Class Reference
avtranscoder::VideoFrameDesc Class Reference
#include <VideoFrame.hpp>
Public Member Functions
VideoFrameDesc (const size_t width=0, const size_t height=0, const AVPixelFormat pixelFormat=AV_PIX_FMT_NONE)
VideoFrameDesc (const size_t width, const size_t height, const std::string &pixelFormat)
size_t getWidth () const
size_t getHeight () const
AVPixelFormat getPixelFormat () const
std::string getPixelFormatName () const
double getFps () const
size_t getDataSize () const
void setWidth (const size_t width)
void setHeight (const size_t height)
void setPixelFormat (const std::string &pixelFormat)
void setPixelFormat (const AVPixelFormat pixelFormat)
void setFps (const double fps)
void setParameters (const ProfileLoader::Profile &profile)
Private Attributes
size_t _width
size_t _height
AVPixelFormat _pixelFormat
double _fps
Detailed Description
Definition at line 14 of file VideoFrame.hpp.
Constructor & Destructor Documentation
avtranscoder::VideoFrameDesc::VideoFrameDesc (const size_t width = 0, const size_t height = 0, const AVPixelFormat pixelFormat = AV_PIX_FMT_NONE)
Definition at line 14 of file VideoFrame.cpp.
avtranscoder::VideoFrameDesc::VideoFrameDesc (const size_t width, const size_t height, const std::string & pixelFormat)
Definition at line 21 of file VideoFrame.cpp.
Member Function Documentation
size_t avtranscoder::VideoFrameDesc::getDataSize () const
Definition at line 35 of file VideoFrame.cpp.
References _height, _pixelFormat, _width, and AV_PIX_FMT_NONE.
Referenced by avtranscoder::VideoGenerator::decodeNextFrame().
double avtranscoder::VideoFrameDesc::getFps () const [inline]
Definition at line 24 of file VideoFrame.hpp.
Referenced by avtranscoder::VideoCodec::setImageParameters().
size_t avtranscoder::VideoFrameDesc::getHeight () const [inline]
Definition at line 21 of file VideoFrame.hpp.
Referenced by avtranscoder::VideoTransform::convert(), avtranscoder::VideoTransform::init(), and avtranscoder::VideoCodec::setImageParameters().
AVPixelFormat avtranscoder::VideoFrameDesc::getPixelFormat () const [inline]
Definition at line 22 of file VideoFrame.hpp.
Referenced by avtranscoder::VideoTransform::convert(), avtranscoder::VideoTransform::init(), and avtranscoder::VideoCodec::setImageParameters().
std::string avtranscoder::VideoFrameDesc::getPixelFormatName () const
Definition at line 29 of file VideoFrame.cpp.
References _pixelFormat.
size_t avtranscoder::VideoFrameDesc::getWidth () const [inline]
Definition at line 20 of file VideoFrame.hpp.
Referenced by avtranscoder::VideoTransform::convert(), avtranscoder::VideoTransform::init(), and avtranscoder::VideoCodec::setImageParameters().
void avtranscoder::VideoFrameDesc::setFps (const double fps) [inline]
Definition at line 32 of file VideoFrame.hpp.
Referenced by avtranscoder::VideoCodec::getVideoFrameDesc(), and setParameters().
void avtranscoder::VideoFrameDesc::setHeight (const size_t height) [inline]
Definition at line 29 of file VideoFrame.hpp.
Referenced by setParameters().
void avtranscoder::VideoFrameDesc::setParameters (const ProfileLoader::Profile & profile)
Definition at line 52 of file VideoFrame.cpp.
References avtranscoder::constants::avProfileFrameRate, avtranscoder::constants::avProfileHeight, avtranscoder::constants::avProfilePixelFormat, avtranscoder::constants::avProfileWidth, setFps(), setHeight(), setPixelFormat(), and setWidth().
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::VideoFrameDesc::setPixelFormat (const std::string & pixelFormat)
Definition at line 47 of file VideoFrame.cpp.
References _pixelFormat.
Referenced by avtranscoder::VideoGenerator::decodeNextFrame(), and setParameters().
void avtranscoder::VideoFrameDesc::setPixelFormat (const AVPixelFormat pixelFormat) [inline]
Definition at line 31 of file VideoFrame.hpp.
void avtranscoder::VideoFrameDesc::setWidth (const size_t width) [inline]
Definition at line 28 of file VideoFrame.hpp.
Referenced by setParameters().
Field Documentation
double avtranscoder::VideoFrameDesc::_fps [private]
Definition at line 40 of file VideoFrame.hpp.
size_t avtranscoder::VideoFrameDesc::_height [private]
Definition at line 38 of file VideoFrame.hpp.
Referenced by getDataSize().
AVPixelFormat avtranscoder::VideoFrameDesc::_pixelFormat [private]
Definition at line 39 of file VideoFrame.hpp.
Referenced by getDataSize(), getPixelFormatName(), and setPixelFormat().
size_t avtranscoder::VideoFrameDesc::_width [private]
Definition at line 37 of file VideoFrame.hpp.
Referenced by getDataSize().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/frame/VideoFrame.hpp
/datas/cnt/workspace/avTranscoder_dev/avTranscoder/src/AvTranscoder/frame/VideoFrame.cpp