AvTranscoder: avtranscoder::detail Namespace Reference
avtranscoder::detail Namespace Reference
Functions
template<>
void add (PropertyVector &propertyVector, const std::string &key, const size_t &value)
template<>
void add (PropertyVector &propertyVector, const std::string &key, const float &value)
template<>
void add (PropertyVector &propertyVector, const std::string &key, const std::string &value)
template<>
void add (PropertyVector &propertyVector, const std::string &key, const bool &value)
template<>
void add (PropertyVector &propertyVector, const std::string &key, const Rational &value)
void fillMetadataDictionnary (AVDictionary *avdictionnary, PropertyVector &metadata)
Fill metadata parameter with the given AVDictionary.
template<typename T >
void add (PropertyVector &propertyVector, const std::string &key, const T &value)
Variables
const size_t keyWidth = 32
const std::string separator = "===================="
const std::string propertyValueIfError = "null"
Function Documentation
template<> void avtranscoder::detail::add (PropertyVector & propertyVector, const std::string & key, const size_t & value)
Definition at line 16 of file util.cpp.
Referenced by add(), avtranscoder::AudioProperties::addProperty(), avtranscoder::StreamProperties::addProperty(), avtranscoder::PixelProperties::addProperty(), avtranscoder::FileProperties::addProperty(), avtranscoder::VideoProperties::addProperty(), avtranscoder::StreamProperties::fillVector(), avtranscoder::PixelProperties::fillVector(), avtranscoder::VideoProperties::fillVector(), and avtranscoder::FileProperties::fillVector().
template<> void avtranscoder::detail::add (PropertyVector & propertyVector, const std::string & key, const float & value)
Definition at line 27 of file util.cpp.
References add().
template<> void avtranscoder::detail::add (PropertyVector & propertyVector, const std::string & key, const std::string & value)
Definition at line 38 of file util.cpp.
template<typename T > void avtranscoder::detail::add (PropertyVector & propertyVector, const std::string & key, const T & value)
Definition at line 41 of file util.hpp.
References add().
template<> void avtranscoder::detail::add (PropertyVector & propertyVector, const std::string & key, const bool & value)
Definition at line 44 of file util.cpp.
References add().
template<> void avtranscoder::detail::add (PropertyVector & propertyVector, const std::string & key, const Rational & value)
Definition at line 50 of file util.cpp.
References add().
void AvExport avtranscoder::detail::fillMetadataDictionnary (AVDictionary * avdictionnary, PropertyVector & metadata)
Fill metadata parameter with the given AVDictionary.
Definition at line 55 of file util.cpp.
Referenced by avtranscoder::FileProperties::FileProperties(), and avtranscoder::StreamProperties::StreamProperties().
Variable Documentation
const size_t avtranscoder::detail::keyWidth = 32
Variables to print properties class to the terminal.
Definition at line 32 of file util.hpp.
Referenced by avtranscoder::operator<<().
const std::string avtranscoder::detail::propertyValueIfError = "null"
If cannot access the property, get this value.
Definition at line 38 of file util.hpp.
Referenced by avtranscoder::AudioProperties::addProperty(), avtranscoder::StreamProperties::addProperty(), avtranscoder::PixelProperties::addProperty(), avtranscoder::FileProperties::addProperty(), avtranscoder::VideoProperties::addProperty(), avtranscoder::PixelProperties::fillVector(), and avtranscoder::VideoProperties::fillVector().
const std::string avtranscoder::detail::separator = "===================="
Definition at line 33 of file util.hpp.
Referenced by avtranscoder::operator<<(), and parseConfigFile().