AvTranscoder: avtranscoder::DummyVideo Class Reference
avtranscoder::DummyVideo Class Reference
#include <DummyVideo.hpp>
Public Member Functions
DummyVideo ()
~DummyVideo ()
void setVideoDesc (const VideoDesc &videoDesc)
VideoDesc getVideoDesc () const
void setup ()
void setFrame (Frame &inputFrame)
bool readNextFrame (Frame &frameBuffer)
bool readNextFrame (Frame &frameBuffer, const size_t subStreamIndex)
Public Member Functions inherited from avtranscoder::InputEssence
InputEssence ()
virtual ~InputEssence ()
Private Attributes
Frame * _inputFrame
VideoDesc _videoDesc
VideoFrameDesc _videoFrameDesc
size_t _numberOfView
Detailed Description
Definition at line 13 of file DummyVideo.hpp.
Constructor & Destructor Documentation
avtranscoder::DummyVideo::DummyVideo ()
Definition at line 8 of file DummyVideo.cpp.
avtranscoder::DummyVideo::~DummyVideo ()
Definition at line 17 of file DummyVideo.cpp.
Member Function Documentation
VideoDesc avtranscoder::DummyVideo::getVideoDesc () const
Definition at line 27 of file DummyVideo.cpp.
References _videoDesc.
bool avtranscoder::DummyVideo::readNextFrame (Frame & frameBuffer) virtual
Implements avtranscoder::InputEssence.
Definition at line 37 of file DummyVideo.cpp.
References _inputFrame, _videoDesc, _videoFrameDesc, avtranscoder::VideoEssenceTransform::convert(), avtranscoder::eComponentRgb, avtranscoder::Frame::getBuffer(), avtranscoder::VideoFrameDesc::getDataSize(), avtranscoder::Frame::getPtr(), avtranscoder::Frame::getSize(), avtranscoder::VideoDesc::getVideoFrameDesc(), and avtranscoder::Pixel::setColorComponents().
bool avtranscoder::DummyVideo::readNextFrame (Frame & frameBuffer, const size_t subStreamIndex) virtual
Implements avtranscoder::InputEssence.
Definition at line 69 of file DummyVideo.cpp.
void avtranscoder::DummyVideo::setFrame (Frame & inputFrame)
Definition at line 32 of file DummyVideo.cpp.
References _inputFrame.
void avtranscoder::DummyVideo::setup () inline virtual
Implements avtranscoder::InputEssence.
Definition at line 25 of file DummyVideo.hpp.
void avtranscoder::DummyVideo::setVideoDesc (const VideoDesc & videoDesc)
Definition at line 21 of file DummyVideo.cpp.
References _videoDesc, _videoFrameDesc, and avtranscoder::VideoDesc::getVideoFrameDesc().
Referenced by avtranscoder::StreamTranscoder::StreamTranscoder().
Field Documentation
Frame* avtranscoder::DummyVideo::_inputFrame private
Definition at line 33 of file DummyVideo.hpp.
Referenced by readNextFrame(), and setFrame().
size_t avtranscoder::DummyVideo::_numberOfView private
Definition at line 37 of file DummyVideo.hpp.
VideoDesc avtranscoder::DummyVideo::_videoDesc private
Definition at line 34 of file DummyVideo.hpp.
Referenced by getVideoDesc(), readNextFrame(), and setVideoDesc().
VideoFrameDesc avtranscoder::DummyVideo::_videoFrameDesc private
Definition at line 35 of file DummyVideo.hpp.
Referenced by readNextFrame(), and setVideoDesc().
The documentation for this class was generated from the following files:
src/AvTranscoder/EssenceStream/DummyVideo.hpp
src/AvTranscoder/EssenceStream/DummyVideo.cpp