AvTranscoder: avtranscoder::OptionLoader Class Reference
avtranscoder::OptionLoader Class Reference
Manage Options. Get a list of options by calling a load****Options(), depending on which FFMpeg / LibAV object you want to analyse.
#include <OptionLoader.hpp>
Public Types
typedef std::vector< Option > OptionArray
typedef std::map< std::string,
std::vector< Option > > OptionMap
Public Member Functions
OptionLoader ()
~OptionLoader ()
const AVFormatContext * getFormatContext () const
const AVCodecContext * getCodecContext () const
const AVOutputFormat * getOutputFormat () const
const AVCodec * getCodec () const
OptionArray loadFormatContextOptions (int req_flags=0)
OptionArray loadCodecContextOptions (int req_flags=0)
OptionMap loadOutputFormatOptions ()
OptionMap loadVideoCodecOptions ()
OptionMap loadAudioCodecOptions ()
std::vector< std::string > & getFormatsLongNames ()
std::vector< std::string > & getFormatsShortNames ()
std::vector< std::string > & getVideoCodecsLongNames ()
std::vector< std::string > & getVideoCodecsShortNames ()
std::vector< std::string > & getAudioCodecsLongNames ()
std::vector< std::string > & getAudioCodecsShortNames ()
Static Public Member Functions
static std::vector< std::string > getPixelFormats (const std::string &videoCodecName="")
Get array of pixel format supported by video codec.
static std::vector< std::string > getSampleFormats (const std::string &audioCodecName="")
Get array of sample format supported by an audio codec.
static AVPixelFormat getAVPixelFormat (const std::string &pixelFormat)
Get the corresponding AVPixelFormat from the pixel format name.
static AVSampleFormat getAVSampleFormat (const std::string &sampleFormat)
Get the corresponding AVSampleFormat from the sample format name.
Private Member Functions
OptionArray loadOptions (void *av_class, int req_flags=0)
: load array of Option depending on the flags.
Private Attributes
AVFormatContext * _avFormatContext
AVCodecContext * _avCodecContext
AVOutputFormat * _outputFormat
AVCodec * _codec
std::vector< std::string > _formatsLongNames
std::vector< std::string > _formatsShortNames
std::vector< std::string > _videoCodecsLongNames
std::vector< std::string > _videoCodecsShortNames
std::vector< std::string > _audioCodecsLongNames
std::vector< std::string > _audioCodecsShortNames
Detailed Description
Manage Options. Get a list of options by calling a load****Options(), depending on which FFMpeg / LibAV object you want to analyse.
Definition at line 25 of file OptionLoader.hpp.
Member Typedef Documentation
typedef std::vector<Option> avtranscoder::OptionLoader::OptionArray
Definition at line 28 of file OptionLoader.hpp.
typedef std::map< std::string, std::vector<Option> > avtranscoder::OptionLoader::OptionMap
Definition at line 29 of file OptionLoader.hpp.
Constructor & Destructor Documentation
avtranscoder::OptionLoader::OptionLoader ()
Definition at line 27 of file OptionLoader.cpp.
References _audioCodecsLongNames, _audioCodecsShortNames, _avCodecContext, _avFormatContext, _formatsLongNames, _formatsShortNames, _videoCodecsLongNames, _videoCodecsShortNames, and AV_CODEC_ID_NONE.
avtranscoder::OptionLoader::~OptionLoader ()
Definition at line 104 of file OptionLoader.cpp.
References _avCodecContext, and _avFormatContext.
Member Function Documentation
std::vector<std::string>& avtranscoder::OptionLoader::getAudioCodecsLongNames () inline
Definition at line 60 of file OptionLoader.hpp.
References _audioCodecsLongNames.
std::vector<std::string>& avtranscoder::OptionLoader::getAudioCodecsShortNames () inline
Definition at line 61 of file OptionLoader.hpp.
References _audioCodecsShortNames.
AVPixelFormat avtranscoder::OptionLoader::getAVPixelFormat (const std::string & pixelFormat) static
Get the corresponding AVPixelFormat from the pixel format name.
Parameters
pixelFormat the name of the pixel format
Definition at line 362 of file OptionLoader.cpp.
AVSampleFormat avtranscoder::OptionLoader::getAVSampleFormat (const std::string & sampleFormat) static
Get the corresponding AVSampleFormat from the sample format name.
Parameters
sampleFormat the name of the sample format
Definition at line 367 of file OptionLoader.cpp.
const AVCodec* avtranscoder::OptionLoader::getCodec () const inline
Definition at line 38 of file OptionLoader.hpp.
References _codec.
const AVCodecContext* avtranscoder::OptionLoader::getCodecContext () const inline
Definition at line 36 of file OptionLoader.hpp.
References _avCodecContext.
const AVFormatContext* avtranscoder::OptionLoader::getFormatContext () const inline
Definition at line 35 of file OptionLoader.hpp.
References _avFormatContext.
std::vector<std::string>& avtranscoder::OptionLoader::getFormatsLongNames () inline
Definition at line 54 of file OptionLoader.hpp.
References _formatsLongNames.
std::vector<std::string>& avtranscoder::OptionLoader::getFormatsShortNames () inline
Definition at line 55 of file OptionLoader.hpp.
References _formatsShortNames.
const AVOutputFormat* avtranscoder::OptionLoader::getOutputFormat () const inline
Definition at line 37 of file OptionLoader.hpp.
References _outputFormat.
std::vector< std::string > avtranscoder::OptionLoader::getPixelFormats (const std::string & videoCodecName = "") static
Get array of pixel format supported by video codec.
Parameters
videoCodecName,: the video codec name (empty if not indicated, and so get all pixel formats supported by all video codecs).
Definition at line 286 of file OptionLoader.cpp.
std::vector< std::string > avtranscoder::OptionLoader::getSampleFormats (const std::string & audioCodecName = "") static
Get array of sample format supported by an audio codec.
Parameters
audioCodecName,: the audio codec name (empty if not indicated, and so get all sample formats supported by all audio codecs).
Definition at line 332 of file OptionLoader.cpp.
std::vector<std::string>& avtranscoder::OptionLoader::getVideoCodecsLongNames () inline
Definition at line 57 of file OptionLoader.hpp.
References _videoCodecsLongNames.
std::vector<std::string>& avtranscoder::OptionLoader::getVideoCodecsShortNames () inline
Definition at line 58 of file OptionLoader.hpp.
References _videoCodecsShortNames.
OptionLoader::OptionMap avtranscoder::OptionLoader::loadAudioCodecOptions ()
Definition at line 186 of file OptionLoader.cpp.
References _codec, and loadOptions().
OptionLoader::OptionArray avtranscoder::OptionLoader::loadCodecContextOptions (int req_flags = 0)
Parameters
req_flags,: AVOption flags (default = 0: no flag restriction)
Definition at line 115 of file OptionLoader.cpp.
References _avCodecContext, and loadOptions().
OptionLoader::OptionArray avtranscoder::OptionLoader::loadFormatContextOptions (int req_flags = 0)
Parameters
req_flags,: AVOption flags (default = 0: no flag restriction)
Definition at line 110 of file OptionLoader.cpp.
References _avFormatContext, and loadOptions().
OptionLoader::OptionArray avtranscoder::OptionLoader::loadOptions (void * av_class, int req_flags = 0) private
: load array of Option depending on the flags.
Parameters
req_flags,: AVOption flags we want to load.
Definition at line 222 of file OptionLoader.cpp.
References avtranscoder::Option::appendChild(), avtranscoder::Option::getDefaultValueInt(), avtranscoder::Option::getNbChilds(), avtranscoder::Option::getType(), avtranscoder::Option::getTypeFromAVOption(), avtranscoder::Option::setDefaultChildIndex(), avtranscoder::TypeChild, and avtranscoder::TypeChoice.
Referenced by loadAudioCodecOptions(), loadCodecContextOptions(), loadFormatContextOptions(), loadOutputFormatOptions(), and loadVideoCodecOptions().
OptionLoader::OptionMap avtranscoder::OptionLoader::loadOutputFormatOptions ()
Definition at line 120 of file OptionLoader.cpp.
References _outputFormat, AV_CODEC_ID_NONE, and loadOptions().
Referenced by optionChecker().
OptionLoader::OptionMap avtranscoder::OptionLoader::loadVideoCodecOptions ()
Definition at line 150 of file OptionLoader.cpp.
References _codec, and loadOptions().
Field Documentation
std::vector<std::string> avtranscoder::OptionLoader::_audioCodecsLongNames private
Definition at line 107 of file OptionLoader.hpp.
Referenced by getAudioCodecsLongNames(), and OptionLoader().
std::vector<std::string> avtranscoder::OptionLoader::_audioCodecsShortNames private
Definition at line 108 of file OptionLoader.hpp.
Referenced by getAudioCodecsShortNames(), and OptionLoader().
AVCodecContext* avtranscoder::OptionLoader::_avCodecContext private
Definition at line 96 of file OptionLoader.hpp.
Referenced by getCodecContext(), loadCodecContextOptions(), OptionLoader(), and ~OptionLoader().
AVFormatContext* avtranscoder::OptionLoader::_avFormatContext private
Definition at line 95 of file OptionLoader.hpp.
Referenced by getFormatContext(), loadFormatContextOptions(), OptionLoader(), and ~OptionLoader().
AVCodec* avtranscoder::OptionLoader::_codec private
Definition at line 99 of file OptionLoader.hpp.
Referenced by getCodec(), loadAudioCodecOptions(), and loadVideoCodecOptions().
std::vector<std::string> avtranscoder::OptionLoader::_formatsLongNames private
Definition at line 101 of file OptionLoader.hpp.
Referenced by getFormatsLongNames(), and OptionLoader().
std::vector<std::string> avtranscoder::OptionLoader::_formatsShortNames private
Definition at line 102 of file OptionLoader.hpp.
Referenced by getFormatsShortNames(), and OptionLoader().
AVOutputFormat* avtranscoder::OptionLoader::_outputFormat private
Definition at line 98 of file OptionLoader.hpp.
Referenced by getOutputFormat(), and loadOutputFormatOptions().
std::vector<std::string> avtranscoder::OptionLoader::_videoCodecsLongNames private
Definition at line 104 of file OptionLoader.hpp.
Referenced by getVideoCodecsLongNames(), and OptionLoader().
std::vector<std::string> avtranscoder::OptionLoader::_videoCodecsShortNames private
Definition at line 105 of file OptionLoader.hpp.
Referenced by getVideoCodecsShortNames(), and OptionLoader().
The documentation for this class was generated from the following files:
src/AvTranscoder/OptionLoader.hpp
src/AvTranscoder/OptionLoader.cpp