AvTranscoder: avtranscoder::AudioCodec Class Reference
avtranscoder::AudioCodec Class Reference
#include <AudioCodec.hpp>
Public Member Functions
AudioCodec (const ECodecType type, const std::string &codecName="")
AudioCodec (const ECodecType type, const AVCodecID codecId)
AudioCodec (const ECodecType type, AVCodecContext &avCodecContext)
AudioFrameDesc getAudioFrameDesc () const
void setAudioParameters (const AudioFrameDesc &audioFrameDesc)
Public Member Functions inherited from avtranscoder::ICodec
ICodec (const ECodecType type, const std::string &codecName)
ICodec (const ECodecType type, const AVCodecID codecId)
ICodec (const ECodecType type, AVCodecContext &avCodecContext)
virtual ~ICodec ()=0
void openCodec ()
Initialize the codec context.
std::string getCodecName () const
AVCodecID getCodecId () const
ECodecType getCodecType () const
int getLatency () const
OptionArray getOptions ()
Get options as array.
OptionMap & getOptionsMap ()
Get options as map.
Option & getOption (const std::string &optionName)
AVCodecContext & getAVCodecContext ()
const AVCodecContext & getAVCodecContext () const
AVCodec & getAVCodec ()
const AVCodec & getAVCodec () const
Additional Inherited Members
Protected Attributes inherited from avtranscoder::ICodec
AVCodecContext * _avCodecContext
Full codec instance description (has ownership)
AVCodec * _avCodec
Codec abstract description.
const bool _isCodecContextAllocated
Is the AVCodecContext allocated by the class.
ECodecType _type
OptionMap _options
Detailed Description
Definition at line 10 of file AudioCodec.hpp.
Constructor & Destructor Documentation
avtranscoder::AudioCodec::AudioCodec (const ECodecType type, const std::string & codecName = "")
Definition at line 9 of file AudioCodec.cpp.
avtranscoder::AudioCodec::AudioCodec (const ECodecType type, const AVCodecID codecId)
Definition at line 14 of file AudioCodec.cpp.
avtranscoder::AudioCodec::AudioCodec (const ECodecType type, AVCodecContext & avCodecContext)
Definition at line 19 of file AudioCodec.cpp.
Member Function Documentation
AudioFrameDesc avtranscoder::AudioCodec::getAudioFrameDesc () const
Definition at line 24 of file AudioCodec.cpp.
References avtranscoder::ICodec::_avCodecContext.
Referenced by avtranscoder::AudioReader::init(), and avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::AudioCodec::setAudioParameters (const AudioFrameDesc & audioFrameDesc)
Definition at line 30 of file AudioCodec.cpp.
References avtranscoder::ICodec::_avCodecContext, avtranscoder::AudioFrameDesc::_nbChannels, avtranscoder::AudioFrameDesc::_sampleFormat, and avtranscoder::AudioFrameDesc::_sampleRate.
Referenced by parseConfigFile(), and avtranscoder::AudioEncoder::setupAudioEncoder().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/codec/AudioCodec.hpp
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/codec/AudioCodec.cpp