AvTranscoder: avtranscoder::VideoCodec Class Reference
avtranscoder::VideoCodec Class Reference
#include <VideoCodec.hpp>
Public Member Functions
VideoCodec (const ECodecType type, const std::string &codecName="")
VideoCodec (const ECodecType type, const AVCodecID codecId)
VideoCodec (const ECodecType type, AVCodecContext &avCodecContext)
VideoFrameDesc getVideoFrameDesc () const
void setImageParameters (const VideoFrameDesc &videoFrameDesc)
Public Member Functions inherited from avtranscoder::ICodec
ICodec (const ECodecType type, const std::string &codecName)
ICodec (const ECodecType type, const AVCodecID codecId)
ICodec (const ECodecType type, AVCodecContext &avCodecContext)
virtual ~ICodec ()=0
void openCodec ()
Initialize the codec context.
std::string getCodecName () const
AVCodecID getCodecId () const
ECodecType getCodecType () const
int getLatency () const
OptionArray getOptions ()
Get options as array.
OptionMap & getOptionsMap ()
Get options as map.
Option & getOption (const std::string &optionName)
AVCodecContext & getAVCodecContext ()
const AVCodecContext & getAVCodecContext () const
AVCodec & getAVCodec ()
const AVCodec & getAVCodec () const
Additional Inherited Members
Protected Attributes inherited from avtranscoder::ICodec
AVCodecContext * _avCodecContext
Full codec instance description (has ownership)
AVCodec * _avCodec
Codec abstract description.
const bool _isCodecContextAllocated
Is the AVCodecContext allocated by the class.
ECodecType _type
OptionMap _options
Detailed Description
Definition at line 10 of file VideoCodec.hpp.
Constructor & Destructor Documentation
avtranscoder::VideoCodec::VideoCodec (const ECodecType type, const std::string & codecName = "")
Definition at line 9 of file VideoCodec.cpp.
avtranscoder::VideoCodec::VideoCodec (const ECodecType type, const AVCodecID codecId)
Definition at line 14 of file VideoCodec.cpp.
avtranscoder::VideoCodec::VideoCodec (const ECodecType type, AVCodecContext & avCodecContext)
Definition at line 19 of file VideoCodec.cpp.
Member Function Documentation
VideoFrameDesc avtranscoder::VideoCodec::getVideoFrameDesc () const
Definition at line 24 of file VideoCodec.cpp.
References avtranscoder::ICodec::_avCodecContext, and avtranscoder::VideoFrameDesc::_fps.
Referenced by avtranscoder::VideoReader::init(), and avtranscoder::StreamTranscoder::StreamTranscoder().
void avtranscoder::VideoCodec::setImageParameters (const VideoFrameDesc & videoFrameDesc)
Definition at line 34 of file VideoCodec.cpp.
References avtranscoder::ICodec::_avCodecContext, avtranscoder::VideoFrameDesc::_fps, avtranscoder::VideoFrameDesc::_height, avtranscoder::VideoFrameDesc::_pixelFormat, and avtranscoder::VideoFrameDesc::_width.
Referenced by parseConfigFile(), and avtranscoder::VideoEncoder::setupVideoEncoder().
The documentation for this class was generated from the following files:
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/codec/VideoCodec.hpp
/datas/cnt/workspace/avTranscoder/src/AvTranscoder/codec/VideoCodec.cpp